// WEEKS 1-2 CONTENT
module.exports = function(h1,h2,h3,p,b,bullet,code,study,codetag,tip,warn,done,market,sep,pageBreak,empty,tag,C) {
const items = [];
const push = (...x) => x.forEach(i => items.push(i));

push(

  // ══════════════════════════════════════════════
  // PROJECT MAP — READ THIS FIRST
  // ══════════════════════════════════════════════
  h1("Project Map — payment-wallet end state after Phase 1"),
  tag("Read this before Day 1. Every file you write over the next 7 weeks lives somewhere in this structure. You are not building isolated exercises. You are building one real system.", C.tealLight, C.teal),
  empty(),
  p("Package root: src/main/java/com/wallet/"),
  code("com.wallet"),
  code("├── PaymentWalletApplication.java          // entry point"),
  code("├── config/"),
  code("│   ├── SecurityConfig.java                // Spring Security + JWT filter chain"),
  code("│   └── AppConfig.java                     // ThreadPoolExecutor, WebClient beans"),
  code("├── controller/"),
  code("│   ├── AuthController.java                // /api/v1/auth/register, /login"),
  code("│   └── PaymentController.java             // /api/v1/payments"),
  code("├── service/"),
  code("│   ├── AuthService.java                   // registration, JWT generation"),
  code("│   ├── PaymentService.java                // core payment logic + @Transactional"),
  code("│   ├── BalanceManager.java                // thread-safe CAS balance operations"),
  code("│   ├── PaymentBatchProcessor.java         // CompletableFuture async pipeline"),
  code("│   ├── IdempotencyService.java            // dedup via idempotency keys"),
  code("│   └── ExternalPaymentGateway.java        // RestTemplate + retry logic"),
  code("├── repository/"),
  code("│   ├── UserRepository.java"),
  code("│   ├── WalletRepository.java"),
  code("│   └── TransactionRepository.java"),
  code("├── model/"),
  code("│   ├── User.java                          // JPA entity"),
  code("│   ├── Wallet.java                        // JPA entity, version field for optimistic lock"),
  code("│   └── Transaction.java                   // JPA entity, idempotency key, soft delete"),
  code("├── payment/"),
  code("│   ├── PaymentStrategy.java               // interface — Strategy pattern"),
  code("│   ├── UPIPayment.java                    // implements PaymentStrategy"),
  code("│   ├── CardPayment.java                   // implements PaymentStrategy"),
  code("│   └── PaymentContext.java                // holds current strategy — Context"),
  code("├── filter/"),
  code("│   ├── JwtAuthFilter.java                 // OncePerRequestFilter"),
  code("│   └── RequestIdFilter.java               // MDC correlation ID"),
  code("├── aspect/"),
  code("│   └── LoggingAspect.java                 // @Around service method timing"),
  code("├── exception/"),
  code("│   ├── GlobalExceptionHandler.java        // @RestControllerAdvice"),
  code("│   ├── InsufficientBalanceException.java"),
  code("│   └── IdempotencyConflictException.java"),
  code("└── dto/"),
  code("    ├── PaymentRequest.java                // Bean Validation annotations"),
  code("    └── PaymentResponse.java"),
  empty(),
  p("src/test/java/com/wallet/ mirrors the same structure. Every service class has a test class."),
  p("Root files: Dockerfile, docker-compose.yml, .env.example, .gitignore, README.md"),
  empty(),
  b("What this project does by end of Phase 1:"),
  bullet("User registers and logs in via JWT"),
  bullet("User has a wallet with a balance"),
  bullet("User can deposit and withdraw — thread-safe, idempotent"),
  bullet("All transactions are recorded with audit trail"),
  bullet("Concurrent requests handled correctly — no race conditions"),
  bullet("All endpoints protected by JWT auth"),
  bullet("Structured logging with correlation ID on every request"),
  bullet("Full Docker Compose setup — one command to run everything"),
  bullet("20+ tests covering core flows and edge cases"),
  sep(), pageBreak(),

  // ══════════════════════════════════════════════
  // WEEK 1
  // ══════════════════════════════════════════════
  h1("WEEK 1 — Java OOP Depth + Git + Maven + Testing Habit"),
  tag("Goal: Set up the project correctly. Understand OOP at the depth product companies test. Write your first real tests. Every concept broken deliberately before it is considered understood.", C.tealLight, C.teal),
  empty(),
  b("What gets built this week:"),
  bullet("payment-wallet project initialised on GitHub with clean structure"),
  bullet("PaymentStrategy interface + UPIPayment + CardPayment — Strategy pattern"),
  bullet("PaymentContext — holds and executes the current strategy"),
  bullet("Singleton JwtTokenProvider with volatile double-checked locking"),
  bullet("PaymentFactory — Factory pattern"),
  bullet("First 8 JUnit tests covering all classes built this week"),
  sep(),

  // DAY 1
  h2("DAY 1 — Monday (1.5 hrs)"),
  h3("Git workflow + Maven basics — Project: repository initialised"),
  empty(),
  p("📚 Study Guide:"),
  b("Git — what you must understand:"),
  bullet("What git is actually for — not backup, but communication between engineers over time"),
  bullet("What an atomic commit is — one logical change, one commit, one clear message"),
  bullet("Conventional commits format — type: description — and what each type means: feat, fix, refactor, chore, test, docs"),
  bullet("Why commit history matters — senior engineers read history before reading code"),
  bullet("What git rebase -i does — combining messy local commits before pushing to remote"),
  bullet("What HEAD~3 means — referring to the last 3 commits relative to current position"),
  bullet("Why squashing exists — keeping history readable and meaningful for the team"),
  empty(),
  b("Maven — what you must understand:"),
  bullet("What Maven actually does — dependency management, build lifecycle management, packaging"),
  bullet("What each dependency scope means:"),
  bullet("  - compile — default. Available everywhere including the production jar."),
  bullet("  - test — JUnit and Mockito go here. NOT included in the production jar."),
  bullet("  - provided — container (e.g. Tomcat) provides it at runtime, not packaged."),
  bullet("  - runtime — not needed to compile, but needed at runtime."),
  bullet("What a transitive dependency is — when you add spring-boot-starter-web, it pulls in Tomcat, Jackson, Spring MVC and many more"),
  bullet("What mvn dependency:tree shows — every dependency and exactly where it came from"),
  bullet("What a fat jar is — Spring Boot packages ALL dependencies inside the jar as a zip file"),
  bullet("Why the fat jar runs anywhere — no separate classpath or installation needed"),
  bullet("What BOOT-INF/lib/ contains — every dependency jar bundled inside your jar"),
  tip("When a NoClassDefFoundError hits in production, mvn dependency:tree is how you find the cause. This is a real debugging tool."),
  empty(),
  study("20 mins"),
  p("Git is not a backup tool. It is a communication tool. Every commit tells the next engineer — including yourself in 3 months — what changed and why. Senior engineers read commit history before reading code. Start correctly."),
  codetag("45 mins — Git setup"),
  code("# Initialise the project"),
  code("git init payment-wallet"),
  code("cd payment-wallet"),
  code("git commit --allow-empty -m \"chore: initialise repository\""),
  empty(),
  p("From today every commit message follows this exact format:"),
  code("type: what changed in one sentence"),
  empty(),
  p("Types: feat (new feature), fix (bug fix), refactor (restructure without behaviour change), chore (config/tooling), test (adding or fixing tests), docs (README or comments)."),
  empty(),
  b("Atomic commits — one logical change per commit:"),
  code("# Wrong — do not do this"),
  code("git commit -m \"added payment classes and tests and fixed bug and updated pom\""),
  code(""),
  code("# Right — one thing per commit"),
  code("git commit -m \"feat: add UPIPayment strategy class\""),
  code("git commit -m \"test: add UPIPayment unit tests\""),
  empty(),
  b("Squashing — combine messy local commits before pushing:"),
  code("git rebase -i HEAD~3"),
  code("# In the editor: change 'pick' to 'squash' on commits to merge"),
  code("# The top commit stays as 'pick' — it becomes the final commit"),
  empty(),
  b("Failure simulation — what bad history looks like:"),
  code("git commit -m \"fix\""),
  code("git commit -m \"fix2\""),
  code("git commit -m \"asdf\""),
  code("git log --oneline"),
  code("# This is what juniors push. Squash it before it reaches GitHub."),
  code("git rebase -i HEAD~3   # squash all three into one meaningful commit"),
  empty(),
  codetag("25 mins — Maven basics"),
  p("Create a Spring Boot project at start.spring.io — Java 21, Maven, Spring Web, Spring Data JPA, MySQL Driver, Spring Security, Lombok, Validation. Download and open in IntelliJ."),
  empty(),
  b("Understand dependency scopes — read your pom.xml:"),
  code("<dependency>"),
  code("  <scope>compile</scope>   <!-- default: available everywhere -->"),
  code("  <scope>test</scope>      <!-- JUnit, Mockito go here — not in production jar -->"),
  code("  <scope>provided</scope>  <!-- container provides it at runtime -->"),
  code("  <scope>runtime</scope>   <!-- not needed to compile, needed to run -->"),
  code("</dependency>"),
  empty(),
  b("Run this and read every line of output:"),
  code("mvn dependency:tree"),
  code("# This shows every transitive dependency — where versions come from"),
  code("# When you get a NoClassDefFoundError in production, this is how you debug it"),
  empty(),
  b("Build the jar and look inside:"),
  code("mvn clean package -DskipTests"),
  code("cd target"),
  code("unzip -l payment-wallet-0.0.1-SNAPSHOT.jar | head -40"),
  code("# A jar is a zip file. Spring Boot fat jar contains all dependencies inside."),
  code("# BOOT-INF/lib/ contains every dependency jar."),
  code("# This is why it runs anywhere — no separate classpath setup needed."),
  empty(),
  b("Failure simulation — wrong scope:"),
  code("# Move spring-boot-starter-web from compile to test scope"),
  code("# Run: mvn clean package"),
  code("# Try to run the jar: java -jar target/payment-wallet.jar"),
  code("# Observe: ClassNotFoundException at startup"),
  code("# Restore compile scope. Understand why scope matters."),
  empty(),
  code("git add ."),
  code("git commit -m \"chore: initialise Spring Boot project structure\""),
  code("# Push to GitHub. Verify commit message is clean."),
  done("Project is on GitHub. You explain dependency scope, read a dependency tree, and explain what a fat jar contains."),
  empty(),

  // DAY 2
  h2("DAY 2 — Tuesday (1.5 hrs)"),
  h3("Interfaces vs Abstract Classes + Strategy Pattern — Project: payment/PaymentStrategy.java"),
  empty(),
  p("📚 Study Guide:"),
  b("Interfaces vs Abstract Classes — what you must understand:"),
  bullet("What an interface is — a contract defining capabilities, not implementation or data"),
  bullet("What an abstract class is — partial implementation that cannot be instantiated directly"),
  bullet("What changed in Java 8 — default methods added to interfaces for backward compatibility"),
  bullet("What changed in Java 9 — private methods inside interfaces for shared internal logic"),
  bullet("What \"instance state\" means — fields that belong to a specific object instance (e.g. upiId, maskedCard)"),
  bullet("Why interfaces CANNOT hold instance state — an interface is a contract shared by all implementors. State belongs to instances, not contracts."),
  bullet("Why abstract classes CAN hold instance state — they represent a base object with shared data"),
  bullet("Multiple inheritance — Java allows implementing multiple interfaces but extending only one class. Why this is safe for interfaces but dangerous for classes."),
  bullet("The one real post-Java-8 rule: if you need instance state, use abstract class. Otherwise, prefer interface."),
  empty(),
  b("Strategy Pattern — what you must understand:"),
  bullet("What problem Strategy solves — eliminates if-else chains that grow every time a new payment type is added"),
  bullet("What the three parts of Strategy are: interface (strategy contract), concrete classes (UPI, Card), context (PaymentContext which holds and runs the strategy)"),
  bullet("Why Strategy satisfies OCP — you add new payment types without ever modifying PaymentService"),
  bullet("How Strategy enables testability — you can pass a mock strategy in tests instead of making a real UPI network call"),
  bullet("Why UPIPayment implements the interface rather than extending a class — it has its own instance state (upiId) that no other payment type shares"),
  tip("The connection to testing: code depending on an interface can be tested with a mock. Code depending on a concrete class cannot. This is why Strategy matters."),
  empty(),
  study("40 mins"),
  p("The real post-Java-8 answer is one word: state. An interface cannot hold instance state. An abstract class can. Everything else — default methods, multiple inheritance — is secondary to this line."),
  empty(),
  code("// File: src/main/java/com/wallet/payment/PaymentStrategy.java"),
  code("public interface PaymentStrategy {"),
  code("    void processPayment(double amount);"),
  code("    // Java 8 default method — backward compatibility, not state"),
  code("    default void logPayment(double amount) {"),
  code("        System.out.println(\"Processing payment: \" + amount);"),
  code("    }"),
  code("    // Java 9 private method — shared logic inside interface"),
  code("    private void validate(double amount) {"),
  code("        if (amount <= 0) throw new IllegalArgumentException(\"Amount must be positive\");"),
  code("    }"),
  code("}"),
  empty(),
  code("// File: src/main/java/com/wallet/payment/UPIPayment.java"),
  code("public class UPIPayment implements PaymentStrategy {"),
  code("    private final String upiId; // STATE — why this cannot be in the interface"),
  code("    public UPIPayment(String upiId) { this.upiId = upiId; }"),
  code("    @Override"),
  code("    public void processPayment(double amount) {"),
  code("        System.out.println(\"UPI \" + upiId + \": processing \" + amount);"),
  code("        logPayment(amount);"),
  code("    }"),
  code("}"),
  empty(),
  code("// File: src/main/java/com/wallet/payment/CardPayment.java"),
  code("public class CardPayment implements PaymentStrategy {"),
  code("    private final String maskedCard; // STATE"),
  code("    private final String cardType;   // STATE"),
  code("    public CardPayment(String maskedCard, String cardType) {"),
  code("        this.maskedCard = maskedCard;"),
  code("        this.cardType = cardType;"),
  code("    }"),
  code("    @Override"),
  code("    public void processPayment(double amount) {"),
  code("        System.out.println(cardType + \" \" + maskedCard + \": processing \" + amount);"),
  code("    }"),
  code("}"),
  empty(),
  b("Failure simulation — try to add state to the interface:"),
  code("// Inside PaymentStrategy interface, add:"),
  code("private String processorId = \"DEFAULT\"; // try this"),
  code("// Compile. Read the exact error message."),
  code("// 'interface abstract methods cannot have body'"),
  code("// Now you have seen why the rule exists — not just read about it."),
  empty(),
  codetag("50 mins — First JUnit tests"),
  p("File: src/test/java/com/wallet/payment/UPIPaymentTest.java"),
  code("class UPIPaymentTest {"),
  code("    private UPIPayment payment;"),
  code(""),
  code("    @BeforeEach"),
  code("    void setUp() { payment = new UPIPayment(\"user@upi\"); }"),
  code(""),
  code("    @Test"),
  code("    void processPayment_validAmount_doesNotThrow() {"),
  code("        assertDoesNotThrow(() -> payment.processPayment(500.0));"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void processPayment_zeroAmount_shouldBeHandled() {"),
  code("        // documents current behaviour — update when validation added"),
  code("        assertDoesNotThrow(() -> payment.processPayment(0.0));"),
  code("    }"),
  code("}"),
  empty(),
  code("git commit -m \"feat: add PaymentStrategy interface with UPI and Card implementations\""),
  code("git commit -m \"test: add UPIPayment unit tests\""),
  done("PaymentStrategy, UPIPayment, CardPayment exist in the project. 2 tests are green. You explain why interface cannot hold state."),
  empty(),

  // DAY 3
  h2("DAY 3 — Wednesday (1.5 hrs)"),
  h3("SOLID principles — applied to payment-wallet, not textbook examples"),
  empty(),
  p("📚 Study Guide:"),
  b("Why SOLID exists — before learning the rules:"),
  bullet("The real problem SOLID solves — code that is hard to change, hard to test, and breaks unexpectedly when modified"),
  bullet("How SOLID violations show up in code review — the exact vocabulary senior engineers use: \"this class has too many responsibilities\", \"this is tightly coupled\", \"this cannot be tested\""),
  empty(),
  b("SRP — Single Responsibility Principle:"),
  bullet("What \"responsibility\" actually means — a reason to change, not just \"does one thing\""),
  bullet("Why multiple responsibilities in one class cause problems — two different teams can conflict editing the same file"),
  bullet("How to identify an SRP violation — ask \"how many different reasons could make me change this class?\""),
  bullet("Project example — PaymentService doing payment logic AND email AND logging is 3 responsibilities, 3 reasons to change"),
  empty(),
  b("OCP — Open/Closed Principle:"),
  bullet("What \"open for extension, closed for modification\" means in plain language"),
  bullet("How your PaymentStrategy interface already implements OCP — adding NetBanking payment never requires touching PaymentService"),
  bullet("What an OCP violation looks like — a switch or if-else block that must grow every time a new type is added"),
  empty(),
  b("LSP — Liskov Substitution Principle:"),
  bullet("What \"honouring the contract\" means — every implementation must behave as the interface promises for all valid inputs"),
  bullet("What an LSP violation looks like — a subclass that throws exceptions for inputs the interface declares are valid"),
  bullet("Why LSP violations break caller code — callers trust the abstraction and cannot know which implementation will behave correctly"),
  empty(),
  b("ISP — Interface Segregation Principle:"),
  bullet("What a \"fat interface\" is — forces implementations to provide methods they do not use"),
  bullet("Why fat interfaces create silent bugs — implementations must throw UnsupportedOperationException or return dummy values"),
  bullet("How to split interfaces — by what each specific caller actually needs"),
  empty(),
  b("DIP — Dependency Inversion Principle:"),
  bullet("What \"depend on abstraction, not concrete class\" means and why it matters"),
  bullet("Why depending on UPIPayment directly makes PaymentService untestable — you cannot replace a hardcoded dependency with a mock"),
  bullet("How constructor injection enables DIP — the interface is passed in from outside, not created inside the class"),
  bullet("Why DIP is the principle that makes mocking and unit testing possible at all"),
  tip("SOLID is interview vocabulary. Know all 5 principles using your own project as the example, not textbook definitions."),
  empty(),
  study("30 mins"),
  p("SOLID is not academic. It is the vocabulary senior engineers use in code review. When your code violates SRP, a senior will say 'this class has too many responsibilities.' Know what that means before they say it."),
  empty(),
  b("SRP — Single Responsibility Principle:"),
  code("// WRONG — PaymentService doing too many things"),
  code("class PaymentService {"),
  code("    void processPayment() { }   // payment logic"),
  code("    void sendEmail() { }        // notification — separate responsibility"),
  code("    void writeLog() { }         // logging — separate responsibility"),
  code("    void validateUser() { }     // auth — separate responsibility"),
  code("}"),
  code("// RIGHT — one class, one reason to change"),
  code("class PaymentService    { void processPayment() { } }"),
  code("class NotificationService { void sendEmail() { } }"),
  code("class PaymentValidator  { void validateUser() { } }"),
  empty(),
  b("OCP — Open/Closed Principle — your PaymentStrategy already does this:"),
  code("// Adding NetBanking payment does NOT modify PaymentService"),
  code("// It EXTENDS by adding a new class: NetBankingPayment implements PaymentStrategy"),
  code("// PaymentService is closed for modification, open for extension"),
  empty(),
  b("LSP — Liskov Substitution:"),
  code("// Every PaymentStrategy implementation must honour the contract"),
  code("// If UPIPayment.processPayment() throws for valid amounts — LSP violation"),
  code("// Callers of PaymentStrategy cannot trust the abstraction"),
  empty(),
  b("ISP — Interface Segregation:"),
  code("// WRONG — fat interface"),
  code("interface PaymentProcessor {"),
  code("    void processPayment(double amount);"),
  code("    void refund(double amount);          // not all processors support refund"),
  code("    void generateStatement();            // not payment-related"),
  code("}"),
  code("// RIGHT — split by what callers actually need"),
  code("interface PaymentProcessor { void processPayment(double amount); }"),
  code("interface Refundable        { void refund(double amount); }"),
  empty(),
  b("DIP — Dependency Inversion:"),
  code("// WRONG — high level depends on low level"),
  code("class PaymentService {"),
  code("    private UPIPayment payment = new UPIPayment(\"id\"); // concrete"),
  code("}"),
  code("// RIGHT — depend on abstraction"),
  code("class PaymentService {"),
  code("    private final PaymentStrategy payment; // interface"),
  code("    public PaymentService(PaymentStrategy payment) { this.payment = payment; }"),
  code("}"),
  empty(),
  codetag("60 mins — Refactor existing code to follow SOLID"),
  p("Refactor PaymentService (create it if not yet done) to depend on PaymentStrategy interface, not on UPIPayment directly. This is DIP applied to your actual project."),
  code("// File: src/main/java/com/wallet/service/PaymentService.java"),
  code("public class PaymentService {"),
  code("    private final PaymentStrategy strategy;"),
  code("    // injected — does not know or care which implementation"),
  code("    public PaymentService(PaymentStrategy strategy) {"),
  code("        this.strategy = strategy;"),
  code("    }"),
  code("    public void executePayment(double amount) {"),
  code("        strategy.processPayment(amount);"),
  code("    }"),
  code("}"),
  empty(),
  b("Failure simulation — violate DIP and feel the pain:"),
  code("// Change PaymentService to new UPIPayment() directly"),
  code("// Now try to test PaymentService without making a real UPI call"),
  code("// You cannot — the dependency is hardcoded"),
  code("// Restore the interface dependency. Now you can pass a mock in tests."),
  code("git commit -m \"refactor: apply SOLID principles to PaymentService\""),
  done("You apply all 5 SOLID principles to real classes in the project. You explain each one using payment-wallet as the example, not a textbook definition."),
  empty(),

  // DAY 4
  h2("DAY 4 — Thursday (1.5 hrs)"),
  h3("Design Patterns: Strategy (complete) + Factory — Project: payment/PaymentContext.java + payment/PaymentFactory.java"),
  empty(),
  p("📚 Study Guide:"),
  b("Strategy Pattern — completing your understanding:"),
  bullet("What PaymentContext is and why it exists — the holder of the current strategy, delegates execution to it"),
  bullet("What runtime switching means — user can switch from UPI to Card within the same session without app restart"),
  bullet("Why a null strategy check is necessary — defensive programming: fail fast with a clear error instead of a NullPointerException deep in the stack"),
  empty(),
  b("Factory Pattern — what you must understand:"),
  bullet("What problem Factory solves — the caller should not need to know which concrete class to instantiate"),
  bullet("What \"factory decides which class to create\" means — based on runtime input, not compile-time hardcoding"),
  bullet("Why a static factory method is common — no need to instantiate the factory itself, simpler to call"),
  bullet("Why the default/unknown case must always be handled explicitly — missing it causes runtime MatchException with no useful message to the caller"),
  bullet("How Factory and Strategy work together in your project — Factory creates the right strategy, Context holds and runs it"),
  tip("Interview question: what is the difference between Factory and Strategy? Factory decides what to create. Strategy decides how to behave at runtime."),
  empty(),
  study("30 mins"),
  p("Strategy pattern: define a family of algorithms, encapsulate each one, make them interchangeable. Your PaymentStrategy interface is already the strategy. PaymentContext holds the current strategy and delegates to it."),
  empty(),
  code("// File: src/main/java/com/wallet/payment/PaymentContext.java"),
  code("public class PaymentContext {"),
  code("    private PaymentStrategy strategy;"),
  code(""),
  code("    public PaymentContext(PaymentStrategy strategy) {"),
  code("        this.strategy = strategy;"),
  code("    }"),
  code(""),
  code("    // Runtime switching — key feature of Strategy pattern"),
  code("    public void setStrategy(PaymentStrategy strategy) {"),
  code("        this.strategy = strategy;"),
  code("    }"),
  code(""),
  code("    public void executePayment(double amount) {"),
  code("        if (strategy == null) throw new IllegalStateException(\"No payment strategy set\");"),
  code("        strategy.processPayment(amount);"),
  code("    }"),
  code("}"),
  empty(),
  p("Factory pattern: create objects without specifying the exact class. Caller says what it wants, factory decides which class to instantiate."),
  code("// File: src/main/java/com/wallet/payment/PaymentFactory.java"),
  code("public class PaymentFactory {"),
  code("    public static PaymentStrategy create(String type, String identifier) {"),
  code("        return switch (type.toUpperCase()) {"),
  code("            case \"UPI\"  -> new UPIPayment(identifier);"),
  code("            case \"CARD\" -> new CardPayment(identifier, \"VISA\");"),
  code("            default -> throw new IllegalArgumentException(\"Unknown payment type: \" + type);"),
  code("        };"),
  code("    }"),
  code("}"),
  empty(),
  b("Failure simulation — no default in factory:"),
  code("// Remove the default case from the switch"),
  code("// Call PaymentFactory.create(\"CRYPTO\", \"addr\")"),
  code("// Observe: no compile error, runtime MatchException"),
  code("// Restore the default with a clear exception message"),
  code("// Production rule: always handle the unknown case explicitly"),
  empty(),
  codetag("60 mins — Tests for Context and Factory"),
  p("File: src/test/java/com/wallet/payment/PaymentContextTest.java"),
  code("class PaymentContextTest {"),
  code(""),
  code("    @Test"),
  code("    void executePayment_withUPIStrategy_doesNotThrow() {"),
  code("        PaymentContext ctx = new PaymentContext(new UPIPayment(\"a@upi\"));"),
  code("        assertDoesNotThrow(() -> ctx.executePayment(100.0));"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void executePayment_strategySwitch_usesNewStrategy() {"),
  code("        PaymentContext ctx = new PaymentContext(new UPIPayment(\"a@upi\"));"),
  code("        ctx.setStrategy(new CardPayment(\"**** 1234\", \"VISA\"));"),
  code("        assertDoesNotThrow(() -> ctx.executePayment(200.0));"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void executePayment_noStrategy_throwsIllegalState() {"),
  code("        PaymentContext ctx = new PaymentContext(null);"),
  code("        assertThrows(IllegalStateException.class, () -> ctx.executePayment(100.0));"),
  code("    }"),
  code("}"),
  empty(),
  code("git commit -m \"feat: add PaymentContext and PaymentFactory with Strategy pattern\""),
  code("git commit -m \"test: add PaymentContext tests including null strategy edge case\""),
  done("PaymentContext and PaymentFactory exist and are tested. You explain Strategy pattern using your own code, not a definition."),
  empty(),

  // DAY 5
  h2("DAY 5 — Friday (1.5 hrs)"),
  h3("Design Patterns: Singleton + Builder — Project: JwtTokenProvider.java + PaymentRequest builder"),
  empty(),
  p("📚 Study Guide:"),
  b("Singleton Pattern — what you must understand:"),
  bullet("What Singleton guarantees — only one instance of the class exists in the entire JVM"),
  bullet("Real use cases — config holders, connection pools, JWT token providers, thread pools"),
  bullet("Why the naive version is broken under concurrency — Thread A and B both see null, both create separate instances"),
  bullet("What volatile does in this context — prevents the JVM from reordering the write to the instance field before the constructor finishes"),
  bullet("Why reordering is dangerous — Thread B can see a non-null reference to a partially constructed object and use it"),
  bullet("What double-checked locking is — first check without lock (fast path), second check inside synchronized (safe path)"),
  bullet("Why both checks are needed — first check avoids acquiring the lock on every call. Second check prevents duplicate creation under concurrent access."),
  empty(),
  b("Builder Pattern — what you must understand:"),
  bullet("What problem Builder solves — telescoping constructors with many parameters become unreadable and error-prone"),
  bullet("What telescoping constructors look like — new PaymentRequest(\"u1\",\"u2\",500.0,\"INR\",\"\",\"\") — which parameter is which?"),
  bullet("How Builder separates required from optional fields — required fields in Builder constructor, optional fields as named fluent methods"),
  bullet("What method chaining (fluent API) means — each setter returns \"this\" so calls can be chained: .currency(\"INR\").description(\"rent\")"),
  bullet("Why the resulting object is immutable — private constructor, all fields final, only Builder can create it"),
  bullet("Where Lombok @Builder saves time — generates all this boilerplate automatically in Spring Boot projects"),
  tip("PaymentRequest is the perfect Builder use case — 3 required fields and 3+ optional fields. The readability difference vs a constructor is obvious."),
  empty(),
  study("35 mins"),
  p("Singleton: only one instance of a class exists in the JVM. Common use: config holders, connection pools, token providers. The naive version is broken under concurrency. The correct version uses volatile + double-checked locking."),
  empty(),
  code("// WRONG — not thread safe"),
  code("public class JwtTokenProvider {"),
  code("    private static JwtTokenProvider instance;"),
  code("    public static JwtTokenProvider getInstance() {"),
  code("        if (instance == null) {              // Thread A and B both see null"),
  code("            instance = new JwtTokenProvider(); // both create instances"),
  code("        }"),
  code("        return instance; // two different instances returned"),
  code("    }"),
  code("}"),
  empty(),
  code("// CORRECT — volatile + double-checked locking"),
  code("// File: src/main/java/com/wallet/config/JwtTokenProvider.java"),
  code("public class JwtTokenProvider {"),
  code("    private static volatile JwtTokenProvider instance;"),
  code("    private final String secretKey;"),
  code(""),
  code("    private JwtTokenProvider() {"),
  code("        this.secretKey = \"your-256-bit-secret-key-for-hs256-algorithm\";"),
  code("    }"),
  code(""),
  code("    public static JwtTokenProvider getInstance() {"),
  code("        if (instance == null) {                      // first check — no lock"),
  code("            synchronized (JwtTokenProvider.class) {  // lock only if needed"),
  code("                if (instance == null) {              // second check — under lock"),
  code("                    instance = new JwtTokenProvider();"),
  code("                }"),
  code("            }"),
  code("        }"),
  code("        return instance;"),
  code("    }"),
  code(""),
  code("    public String generateToken(String userId) {"),
  code("        return \"token-\" + userId + \"-\" + System.currentTimeMillis();"),
  code("    }"),
  code("}"),
  empty(),
  p("Why volatile here: without volatile, the JVM can reorder the write to instance before the constructor finishes. Thread B sees a non-null but partially constructed object. volatile prevents this reordering."),
  empty(),
  p("Builder pattern: construct complex objects step by step. Useful when a class has many optional fields and telescoping constructors become unreadable."),
  code("// File: src/main/java/com/wallet/dto/PaymentRequest.java"),
  code("public class PaymentRequest {"),
  code("    private final String fromUserId;"),
  code("    private final String toUserId;"),
  code("    private final double amount;"),
  code("    private final String currency;"),
  code("    private final String idempotencyKey;"),
  code("    private final String description;"),
  code(""),
  code("    private PaymentRequest(Builder builder) {"),
  code("        this.fromUserId     = builder.fromUserId;"),
  code("        this.toUserId       = builder.toUserId;"),
  code("        this.amount         = builder.amount;"),
  code("        this.currency       = builder.currency;"),
  code("        this.idempotencyKey = builder.idempotencyKey;"),
  code("        this.description    = builder.description;"),
  code("    }"),
  code(""),
  code("    public static class Builder {"),
  code("        private final String fromUserId;  // required"),
  code("        private final String toUserId;    // required"),
  code("        private final double amount;      // required"),
  code("        private String currency     = \"INR\";  // optional with default"),
  code("        private String idempotencyKey = \"\";   // optional"),
  code("        private String description  = \"\";     // optional"),
  code(""),
  code("        public Builder(String fromUserId, String toUserId, double amount) {"),
  code("            this.fromUserId = fromUserId;"),
  code("            this.toUserId   = toUserId;"),
  code("            this.amount     = amount;"),
  code("        }"),
  code("        public Builder currency(String c)      { this.currency = c; return this; }"),
  code("        public Builder idempotencyKey(String k){ this.idempotencyKey = k; return this; }"),
  code("        public Builder description(String d)   { this.description = d; return this; }"),
  code("        public PaymentRequest build()          { return new PaymentRequest(this); }"),
  code("    }"),
  code("}"),
  empty(),
  b("Failure simulation — remove volatile from Singleton:"),
  code("// Remove volatile keyword from instance field"),
  code("// Run 1000 threads all calling getInstance() simultaneously"),
  code("// Under high concurrency you may get multiple instances"),
  code("// The bug is intermittent — this is why concurrency bugs are hard"),
  code("// Restore volatile. The second check inside synchronized is also required."),
  code("git commit -m \"feat: add Singleton JwtTokenProvider and Builder PaymentRequest\""),
  done("JwtTokenProvider is a correct thread-safe Singleton. PaymentRequest uses Builder. You explain why volatile is required in double-checked locking."),
  empty(),

  // DAY 6
  h2("DAY 6 — Saturday (2-3 hrs)"),
  h3("Observer Pattern + Week 1 integration — Project: observer/ package"),
  empty(),
  p("📚 Study Guide:"),
  b("Observer Pattern — what you must understand:"),
  bullet("What problem Observer solves — when one event must notify multiple independent handlers without the source knowing who they are"),
  bullet("The wallet example: payment success must trigger audit log, fraud check, and notification. Without Observer, PaymentService calls all three directly — tight coupling."),
  bullet("Why direct coupling is a problem — adding a fourth handler requires modifying PaymentService. OCP violated every time."),
  bullet("What the three parts of Observer are: subject/publisher (fires events), observer interface (contract for handlers), concrete observers (AuditLogger, FraudDetector)"),
  bullet("How Observer satisfies OCP — adding a new observer never requires modifying PaymentEventPublisher"),
  bullet("How Observer relates to the real world — Spring ApplicationEvents, Kafka consumers, and webhook notification systems all use this same pattern"),
  bullet("What unsubscribe is for — removing observers when no longer needed, preventing memory leaks"),
  empty(),
  b("Week 1 integration — what to verify:"),
  bullet("Every class built this week exists in the correct package inside payment-wallet"),
  bullet("Every class has at least one corresponding test that is green"),
  bullet("All commit messages follow the type: description format without exception"),
  bullet("No WIP, fix, fix2, or asdf commits anywhere in the GitHub history"),
  empty(),
  study("40 mins"),
  p("Observer pattern: when one object changes state, all dependents are notified automatically. In your wallet: when a payment succeeds, the notification service, the audit logger, and the fraud detector all need to know. Without Observer, PaymentService calls each one directly — tight coupling. With Observer, PaymentService fires an event and does not know who handles it."),
  empty(),
  code("// File: src/main/java/com/wallet/observer/PaymentObserver.java"),
  code("public interface PaymentObserver {"),
  code("    void onPaymentProcessed(String userId, double amount, String status);"),
  code("}"),
  empty(),
  code("// File: src/main/java/com/wallet/observer/AuditLogger.java"),
  code("public class AuditLogger implements PaymentObserver {"),
  code("    private static final Logger log = LoggerFactory.getLogger(AuditLogger.class);"),
  code("    @Override"),
  code("    public void onPaymentProcessed(String userId, double amount, String status) {"),
  code("        log.info(\"AUDIT userId={} amount={} status={}\", userId, amount, status);"),
  code("    }"),
  code("}"),
  empty(),
  code("// File: src/main/java/com/wallet/observer/FraudDetector.java"),
  code("public class FraudDetector implements PaymentObserver {"),
  code("    private static final Logger log = LoggerFactory.getLogger(FraudDetector.class);"),
  code("    @Override"),
  code("    public void onPaymentProcessed(String userId, double amount, String status) {"),
  code("        if (amount > 50000) {"),
  code("            log.warn(\"FRAUD ALERT userId={} amount={} exceeds threshold\", userId, amount);"),
  code("        }"),
  code("    }"),
  code("}"),
  empty(),
  code("// File: src/main/java/com/wallet/observer/PaymentEventPublisher.java"),
  code("public class PaymentEventPublisher {"),
  code("    private final List<PaymentObserver> observers = new ArrayList<>();"),
  code(""),
  code("    public void subscribe(PaymentObserver observer) {"),
  code("        observers.add(observer);"),
  code("    }"),
  code(""),
  code("    public void unsubscribe(PaymentObserver observer) {"),
  code("        observers.remove(observer);"),
  code("    }"),
  code(""),
  code("    public void publish(String userId, double amount, String status) {"),
  code("        observers.forEach(o -> o.onPaymentProcessed(userId, amount, status));"),
  code("    }"),
  code("}"),
  empty(),
  b("Failure simulation — no observer pattern, direct coupling:"),
  code("// In PaymentService, call AuditLogger and FraudDetector directly"),
  code("// Now add a third notifier — you must modify PaymentService"),
  code("// OCP violation — PaymentService is not closed for modification"),
  code("// Restore the Observer pattern — PaymentService only calls publisher.publish()"),
  code("// Adding new observers never touches PaymentService"),
  empty(),
  codetag("Build 3 Observer tests — 60 mins"),
  p("File: src/test/java/com/wallet/observer/PaymentEventPublisherTest.java"),
  code("class PaymentEventPublisherTest {"),
  code("    private PaymentEventPublisher publisher;"),
  code(""),
  code("    @BeforeEach"),
  code("    void setUp() { publisher = new PaymentEventPublisher(); }"),
  code(""),
  code("    @Test"),
  code("    void publish_withOneObserver_callsObserver() {"),
  code("        List<String> received = new ArrayList<>();"),
  code("        publisher.subscribe((u, a, s) -> received.add(u + \"|\" + s));"),
  code("        publisher.publish(\"user1\", 500.0, \"SUCCESS\");"),
  code("        assertEquals(1, received.size());"),
  code("        assertEquals(\"user1|SUCCESS\", received.get(0));"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void publish_withMultipleObservers_allReceiveEvent() {"),
  code("        AtomicInteger count = new AtomicInteger(0);"),
  code("        publisher.subscribe((u, a, s) -> count.incrementAndGet());"),
  code("        publisher.subscribe((u, a, s) -> count.incrementAndGet());"),
  code("        publisher.publish(\"user1\", 100.0, \"SUCCESS\");"),
  code("        assertEquals(2, count.get());"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void publish_afterUnsubscribe_observerNotCalled() {"),
  code("        AtomicInteger count = new AtomicInteger(0);"),
  code("        PaymentObserver obs = (u, a, s) -> count.incrementAndGet();"),
  code("        publisher.subscribe(obs);"),
  code("        publisher.unsubscribe(obs);"),
  code("        publisher.publish(\"user1\", 100.0, \"SUCCESS\");"),
  code("        assertEquals(0, count.get());"),
  code("    }"),
  code("}"),
  empty(),
  code("git commit -m \"feat: add Observer pattern for payment event publishing\""),
  code("git commit -m \"test: add PaymentEventPublisher tests\""),
  done("Observer pattern implemented. 3 tests green. You explain why Observer satisfies OCP without touching PaymentService."),
  empty(),

  // DAY 7
  h2("DAY 7 — Sunday (2-3 hrs)"),
  h3("Week 1 Checkpoint — answer from memory, no notes"),
  empty(),
  p("📚 Study Guide:"),
  b("Answer every question from memory. No notes. No IDE."),
  bullet("Why can an interface not hold instance state? What exactly happens at compile time if you try?"),
  bullet("After Java 8, what is the one remaining reason to choose an abstract class over an interface?"),
  bullet("Explain LSP using your PaymentStrategy implementations as the example"),
  bullet("Walk through Strategy pattern using PaymentContext — what problem does it solve?"),
  bullet("Why does JwtTokenProvider need volatile? What breaks without it under concurrent access?"),
  bullet("Why does Builder exist? Show a PaymentRequest construction with 5 fields — would a constructor be readable?"),
  bullet("How does Observer satisfy OCP? What would violate OCP in the same scenario?"),
  bullet("What does git rebase -i do and when would you use it before pushing?"),
  bullet("What is inside a fat jar and why does Spring Boot package it that way?"),
  warn("If you cannot answer any question without notes — do not move to Week 2. Spend the remaining time on the weak area. Week 2 builds directly on this foundation."),
  empty(),
  b("Run the full test suite first:"),
  code("mvn clean test"),
  code("# All tests must be green before attempting the checkpoint"),
  empty(),
  b("Checkpoint questions — answer each one out loud:"),
  empty(),
  b("OOP:"),
  bullet("Why can an interface not hold instance state? What exactly happens if you try?"),
  bullet("After Java 8, what is the one remaining reason to use an abstract class over an interface?"),
  bullet("Explain LSP using your PaymentStrategy implementations as the example"),
  empty(),
  b("Design patterns:"),
  bullet("Walk through Strategy pattern using PaymentContext — what problem does it solve?"),
  bullet("Why does PaymentFactory use a static method? What would be different if it were an instance method?"),
  bullet("Why does JwtTokenProvider need volatile? What breaks without it?"),
  bullet("Why does Builder exist? Show a PaymentRequest construction with 5 fields — would a constructor be readable?"),
  bullet("How does Observer satisfy OCP? What would violate OCP in the same scenario?"),
  empty(),
  b("Git and Maven:"),
  bullet("What does git rebase -i do and when would you use it before pushing?"),
  bullet("What is the difference between test scope and compile scope in Maven?"),
  bullet("What is inside a fat jar and why does Spring Boot package it that way?"),
  empty(),
  b("GitHub check:"),
  bullet("Every commit message follows the type: description format"),
  bullet("No WIP, fix, fix2, or asdf commits in history"),
  bullet("All 8+ tests are committed"),
  empty(),
  warn("If you cannot answer any checkpoint question without notes — do not move to Week 2. Spend the remaining time on the weak area. Week 2 builds directly on top of this."),
  market("Passing Week 1 means you understand OOP at the depth that separates candidates in product company interviews. Most 1 YOE developers cannot explain volatile in Singleton or Observer's relationship to OCP. You now can."),
  sep(), pageBreak(),

  // ══════════════════════════════════════════════
  // WEEK 2
  // ══════════════════════════════════════════════
  h1("WEEK 2 — Java Internals: Collections + JVM Memory + LRU Cache"),
  tag("Goal: Understand how Java's core data structures work internally. Not just what they do — how they do it. Read the actual JDK source. Verify everything in code.", C.tealLight, C.teal),
  empty(),
  b("What gets built this week:"),
  bullet("HashMap collision demonstrator — verifies bucket behaviour"),
  bullet("LRUCache implementation using LinkedHashMap"),
  bullet("JVM memory analyser — heap vs stack demonstration"),
  bullet("Mockito introduced — all Week 1 service tests upgraded"),
  sep(),

  // DAY 8
  h2("DAY 8 — Monday (1.5 hrs)"),
  h3("HashMap internals Part 1 — hashCode, buckets, collision — Project: internals/HashMapDemo.java"),
  empty(),
  p("📚 Study Guide:"),
  b("Internal structure — what you must understand:"),
  bullet("What a hash function is — converts any object into an integer. Not necessarily unique."),
  bullet("Internal structure of HashMap — an array of Node objects. Each Node holds: key, value, hash, and next pointer for chaining."),
  bullet("Default initial capacity — 16 buckets. What this means physically in memory."),
  bullet("How put() decides which bucket — (capacity - 1) & hash. Bitwise AND, not modulo."),
  bullet("Why bitwise AND instead of modulo — faster operation at CPU level. Works because capacity is always a power of 2."),
  empty(),
  b("Collision handling — what you must understand:"),
  bullet("What a collision is — two different keys producing the same bucket index"),
  bullet("How collisions are handled — linked list chaining: new node added to the chain in that bucket"),
  bullet("How get() finds a value when there is a collision — walks the chain, uses equals() to compare each key"),
  bullet("The equals() + hashCode() contract — if two objects are equal by equals(), they must produce the same hashCode"),
  bullet("What breaks when you override equals() without overriding hashCode() — get() cannot find the key. Returns null for a key you just put in."),
  bullet("Null key handling — always stored in bucket 0. Special case in putVal()."),
  tip("\"FB\".hashCode() == \"Ea\".hashCode() == 2236. This is the classic collision demo. Run it and see it happen."),
  empty(),
  study("40 mins"),
  p("HashMap is the most common Java interview topic at product companies. Not because it is trivia. Because how you answer reveals whether you understand your tools or just use them."),
  empty(),
  p("Internal structure: an array of Node objects. Each Node holds key, value, hash, and a pointer to the next Node (for collision chaining). Default capacity: 16 buckets. Load factor: 0.75 — resize when 75% full."),
  empty(),
  code("// How put() decides which bucket:"),
  code("int hash = key.hashCode();"),
  code("int bucket = (capacity - 1) & hash;  // bitwise AND — faster than modulo"),
  code("// For capacity=16: bucket = hash & 15 = last 4 bits of hash"),
  empty(),
  p("Collision: two keys land in the same bucket. HashMap chains them as a linked list. Before Java 8: always linked list. Java 8+: when a single bucket's chain exceeds 8 nodes, it converts to a Red-Black TreeNode — O(n) lookup becomes O(log n)."),
  empty(),
  b("Read the actual source — open this in IntelliJ:"),
  code("// In IntelliJ: Ctrl+N → HashMap → find putVal() method"),
  code("// Read lines 628-700 in OpenJDK 21 source"),
  code("// Key lines to understand:"),
  code("// if ((p = tab[i = (n - 1) & hash]) == null)  — empty bucket, insert"),
  code("// else — collision, walk the chain"),
  code("// if (binCount >= TREEIFY_THRESHOLD - 1)      — convert to tree at 8"),
  empty(),
  codetag("50 mins — build and verify"),
  p("File: src/test/java/com/wallet/internals/HashMapInternalsTest.java"),
  code("class HashMapInternalsTest {"),
  code(""),
  code("    @Test"),
  code("    void hashCollision_twoKeys_sameBucket() {"),
  code("        // \"FB\" and \"Ea\" have the same hashCode in Java"),
  code("        System.out.println(\"FB\".hashCode());   // 2236"),
  code("        System.out.println(\"Ea\".hashCode());   // 2236 — same"),
  code("        assertEquals(\"FB\".hashCode(), \"Ea\".hashCode());"),
  code(""),
  code("        HashMap<String, String> map = new HashMap<>();"),
  code("        map.put(\"FB\", \"value1\");"),
  code("        map.put(\"Ea\", \"value2\");"),
  code(""),
  code("        // Both keys exist — HashMap handles collision correctly"),
  code("        assertEquals(\"value1\", map.get(\"FB\"));"),
  code("        assertEquals(\"value2\", map.get(\"Ea\"));"),
  code("        assertEquals(2, map.size());"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void nullKey_alwaysBucket0() {"),
  code("        HashMap<String, String> map = new HashMap<>();"),
  code("        map.put(null, \"nullValue\");"),
  code("        assertEquals(\"nullValue\", map.get(null));"),
  code("        // null key is always stored in bucket 0 — special case in putVal()"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void duplicateKey_overwritesValue() {"),
  code("        HashMap<String, String> map = new HashMap<>();"),
  code("        map.put(\"key\", \"first\");"),
  code("        map.put(\"key\", \"second\");"),
  code("        assertEquals(\"second\", map.get(\"key\"));"),
  code("        assertEquals(1, map.size()); // not 2"),
  code("    }"),
  code("}"),
  empty(),
  b("Failure simulation — broken equals without hashCode:"),
  code("class BrokenKey {"),
  code("    String value;"),
  code("    BrokenKey(String v) { this.value = v; }"),
  code("    @Override public boolean equals(Object o) {"),
  code("        return o instanceof BrokenKey bk && bk.value.equals(this.value);"),
  code("    }"),
  code("    // hashCode NOT overridden — uses Object identity"),
  code("}"),
  code("// Test:"),
  code("HashMap<BrokenKey, String> map = new HashMap<>();"),
  code("map.put(new BrokenKey(\"x\"), \"val\");"),
  code("System.out.println(map.get(new BrokenKey(\"x\"))); // null — cannot find it"),
  code("// Rule: if you override equals you MUST override hashCode"),
  code("git commit -m \"test: add HashMap internals tests with collision verification\""),
  done("You run the FB/Ea collision test and it passes. You explain hashCode, buckets, and collision handling without notes."),
  empty(),

  // DAY 9
  h2("DAY 9 — Tuesday (1.5 hrs)"),
  h3("HashMap internals Part 2 — treeification + resize + ConcurrentHashMap"),
  empty(),
  p("📚 Study Guide:"),
  b("Treeification — what you must understand:"),
  bullet("What treeification is — converting a bucket\'s linked list into a Red-Black TreeNode when it gets too long"),
  bullet("When it triggers — TREEIFY_THRESHOLD = 8 nodes in one bucket"),
  bullet("Why it exists — O(n) linked list lookup becomes O(log n) tree lookup. Protects against hash collision attacks."),
  bullet("When it matters — malicious input designed to force all keys into one bucket (hash flooding attack)"),
  empty(),
  b("Resize — what you must understand:"),
  bullet("When resize triggers — size exceeds capacity × loadFactor (default 0.75)"),
  bullet("What happens during resize — capacity doubles, every entry rehashed into the new larger array. O(n) operation."),
  bullet("Why resize is expensive — every entry must be recalculated and moved. Avoid it for known-size maps."),
  bullet("How to avoid resize — set initial capacity to expectedSize / 0.75 + 1 when you know the size upfront"),
  empty(),
  b("ConcurrentHashMap — what you must understand:"),
  bullet("Why HashMap is not thread-safe — two threads calling put() simultaneously can corrupt the internal array structure"),
  bullet("How ConcurrentHashMap achieves thread safety — CAS + synchronized on individual buckets (Java 8+). No global lock."),
  bullet("Why ConcurrentHashMap forbids null keys and null values — null is ambiguous under concurrent access"),
  bullet("The null ambiguity problem — get(null)==null could mean the key is not present OR the value is null. Indistinguishable concurrently."),
  bullet("When to choose which — single-threaded: HashMap. Multi-threaded: ConcurrentHashMap."),
  tip("This is the most common Java internals interview topic at product companies. Know every piece of it."),
  empty(),
  study("50 mins"),
  p("Treeification: when one bucket's linked list exceeds TREEIFY_THRESHOLD (8), HashMap converts it to a TreeNode Red-Black tree. get() on a bucket with 8+ entries goes from O(n) to O(log n). This matters when many keys collide — possible with a malicious input designed to force all keys into one bucket."),
  empty(),
  p("Resize: when size > capacity * loadFactor (default 0.75), HashMap doubles capacity and rehashes every entry into the new array. This is O(n) — expensive. If you know the size upfront, set initial capacity to avoid resize."),
  code("// Avoid resize for known-size maps"),
  code("int expectedSize = 1000;"),
  code("HashMap<String, String> map = new HashMap<>(expectedSize * 4 / 3 + 1);"),
  code("// capacity = size / loadFactor — ensures no resize"),
  empty(),
  p("ConcurrentHashMap vs HashMap: HashMap is not thread-safe. Two threads calling put() simultaneously can corrupt the internal array. ConcurrentHashMap uses segment-level locking (Java 7) or CAS + synchronized on individual buckets (Java 8+) — no global lock, high concurrency."),
  code("// ConcurrentHashMap does NOT allow null keys or null values"),
  code("ConcurrentHashMap<String, String> map = new ConcurrentHashMap<>();"),
  code("map.put(null, \"v\"); // throws NullPointerException — intentional design"),
  code("// Why: null key is ambiguous in concurrent context —"),
  code("// get(null)==null could mean key not present OR value is null"),
  empty(),
  codetag("40 mins — verify in code"),
  code("class ConcurrentHashMapTest {"),
  code(""),
  code("    @Test"),
  code("    void concurrentHashMap_nullKey_throwsNPE() {"),
  code("        ConcurrentHashMap<String, String> map = new ConcurrentHashMap<>();"),
  code("        assertThrows(NullPointerException.class, () -> map.put(null, \"v\"));"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void hashMap_concurrentWrite_canCorrupt() throws InterruptedException {"),
  code("        HashMap<Integer, Integer> map = new HashMap<>();"),
  code("        ExecutorService exec = Executors.newFixedThreadPool(10);"),
  code("        for (int i = 0; i < 1000; i++) {"),
  code("            final int key = i;"),
  code("            exec.submit(() -> map.put(key, key));"),
  code("        }"),
  code("        exec.shutdown();"),
  code("        exec.awaitTermination(5, TimeUnit.SECONDS);"),
  code("        // size may NOT be 1000 — race condition in HashMap"),
  code("        // run multiple times — you will see different sizes"),
  code("        System.out.println(\"HashMap size after concurrent writes: \" + map.size());"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void concurrentHashMap_concurrentWrite_alwaysCorrect() throws InterruptedException {"),
  code("        ConcurrentHashMap<Integer, Integer> map = new ConcurrentHashMap<>();"),
  code("        ExecutorService exec = Executors.newFixedThreadPool(10);"),
  code("        for (int i = 0; i < 1000; i++) {"),
  code("            final int key = i;"),
  code("            exec.submit(() -> map.put(key, key));"),
  code("        }"),
  code("        exec.shutdown();"),
  code("        exec.awaitTermination(5, TimeUnit.SECONDS);"),
  code("        assertEquals(1000, map.size()); // always correct"),
  code("    }"),
  code("}"),
  empty(),
  code("git commit -m \"test: verify HashMap vs ConcurrentHashMap thread safety\""),
  done("You explain treeification, resize cost, and why ConcurrentHashMap forbids null keys. The concurrent corruption test produces inconsistent results — you observe and explain why."),
  empty(),

  // DAY 10
  h2("DAY 10 — Wednesday (1.5 hrs)"),
  h3("ArrayList vs LinkedList + JVM Memory basics"),
  empty(),
  p("📚 Study Guide:"),
  b("ArrayList — what you must understand:"),
  bullet("Internal structure — backed by a plain Object array in contiguous memory"),
  bullet("Random access O(1) — index directly into the array, one operation regardless of size"),
  bullet("Add to end O(1) amortised — array doubles in size when full. Occasional O(n) copy, amortised O(1)."),
  bullet("Add/remove in middle O(n) — every element after the insertion point must shift right or left"),
  bullet("Why ArrayList is cache-friendly — contiguous memory means CPU prefetcher can load nearby elements proactively"),
  empty(),
  b("LinkedList — what you must understand:"),
  bullet("Internal structure — doubly-linked nodes. Each node holds: value, prev pointer, next pointer."),
  bullet("Add/remove at head or tail O(1) — just update the relevant pointers"),
  bullet("Random access O(n) — must walk from head node to find the element at index n"),
  bullet("Why LinkedList is cache-unfriendly — nodes are scattered across heap memory. Pointer chasing defeats CPU cache."),
  bullet("The real-world rule — use ArrayList almost always. Use LinkedList only for frequent head/tail operations with no random access."),
  bullet("Why ArrayDeque beats LinkedList for queue behaviour — cache-friendly, no per-node allocation overhead"),
  empty(),
  b("JVM Memory — four areas you must know:"),
  bullet("Heap — all objects live here. Shared across all threads. GC manages this."),
  bullet("Stack — one stack per thread. Holds stack frames. Each frame holds local variables and method call context. StackOverflowError when exceeded."),
  bullet("Metaspace — class metadata, static fields. Not garbage collected normally. OutOfMemoryError if uncapped."),
  bullet("PC Register — current instruction pointer per thread."),
  bullet("Stack vs Heap in a method — the variable reference lives on the stack. The object it points to lives on the heap."),
  bullet("When an object becomes eligible for GC — when no live references from any thread can reach it"),
  tip("Interview question: where does a local variable live? Stack. Where does the object it references live? Heap."),
  empty(),
  study("50 mins"),
  p("ArrayList: backed by an array. Random access O(1) — index directly into array. Add to end O(1) amortised — doubles array when full. Add to middle O(n) — shifts every element right. Cache-friendly — contiguous memory means CPU prefetcher works efficiently."),
  empty(),
  p("LinkedList: doubly-linked nodes. Each node holds value + prev pointer + next pointer. Add/remove at head or tail O(1). Random access O(n) — must walk from head. Cache-unfriendly — nodes scattered in heap, pointer chasing defeats CPU cache."),
  empty(),
  b("The real-world rule:"),
  bullet("Use ArrayList almost always — cache performance dominates"),
  bullet("Use LinkedList only for frequent head/tail operations with no random access"),
  bullet("In practice LinkedList is rarely the right choice — ArrayDeque is better for queue behaviour"),
  empty(),
  p("JVM memory — four areas you must know:"),
  bullet("Heap: all objects live here. GC manages this. Shared across threads."),
  bullet("Stack: one per thread. Holds stack frames — local variables, method calls. Fixed size. StackOverflowError when exceeded."),
  bullet("Metaspace: class metadata, static fields. Not GC'd normally. OutOfMemoryError if unlimited."),
  bullet("PC Register: current instruction pointer per thread."),
  empty(),
  code("// Stack vs Heap — trace this mentally:"),
  code("void processPayment(double amount) {   // amount lives on stack"),
  code("    PaymentRequest req = new PaymentRequest(...); // req reference on stack"),
  code("                                                   // PaymentRequest object on heap"),
  code("    submitToGateway(req);              // new stack frame pushed"),
  code("}                                      // frame popped, req reference gone"),
  code("// PaymentRequest object on heap is now eligible for GC"),
  empty(),
  codetag("40 mins — verify performance difference"),
  code("class CollectionPerformanceTest {"),
  code(""),
  code("    @Test"),
  code("    void arrayList_randomAccess_faster() {"),
  code("        List<Integer> list = new ArrayList<>();"),
  code("        for (int i = 0; i < 100_000; i++) list.add(i);"),
  code(""),
  code("        long start = System.nanoTime();"),
  code("        for (int i = 0; i < 100_000; i++) list.get(i);"),
  code("        long arrayListTime = System.nanoTime() - start;"),
  code(""),
  code("        List<Integer> linked = new LinkedList<>();"),
  code("        for (int i = 0; i < 100_000; i++) linked.add(i);"),
  code(""),
  code("        start = System.nanoTime();"),
  code("        for (int i = 0; i < 100_000; i++) linked.get(i);"),
  code("        long linkedListTime = System.nanoTime() - start;"),
  code(""),
  code("        System.out.printf(\"ArrayList: %dms%n\", arrayListTime / 1_000_000);"),
  code("        System.out.printf(\"LinkedList: %dms%n\", linkedListTime / 1_000_000);"),
  code("        assertTrue(arrayListTime < linkedListTime,"),
  code("            \"ArrayList random access must be faster than LinkedList\");"),
  code("    }"),
  code("}"),
  empty(),
  code("git commit -m \"test: verify ArrayList vs LinkedList performance characteristics\""),
  done("You explain why ArrayList beats LinkedList for random access using cache behaviour, not just Big-O. You trace which variables live on stack vs heap for a given method."),
  empty(),

  // DAY 11
  h2("DAY 11 — Thursday (1.5 hrs)"),
  h3("GC basics + Mockito introduced — Project: service tests upgraded"),
  empty(),
  p("📚 Study Guide:"),
  b("Garbage Collection — what you must understand:"),
  bullet("What GC does — automatically reclaims heap memory for objects with no live references. You never call free()."),
  bullet("Generational hypothesis — most objects die young. JVM exploits this by dividing the heap into generations."),
  bullet("Young Generation (Eden + Survivor) — new objects born here. Minor GC is frequent and fast."),
  bullet("Old Generation (Tenured) — objects that survive multiple minor GCs are promoted here. Major GC is rare but slow."),
  bullet("Stop-The-World pause — JVM freezes ALL application threads to run GC. Real production latency spike."),
  bullet("G1GC (Java 9+ default) — divides heap into regions, collects highest-garbage regions first. Predictable pause times."),
  bullet("Memory leak pattern — a static collection holding object references forever. Those objects can never be GC\'d."),
  empty(),
  b("Mockito — what you must understand:"),
  bullet("What Mockito does — creates fake (mock) implementations of dependencies for isolated unit testing"),
  bullet("Why mocks are necessary — without them, testing PaymentService requires a real UPI gateway, real database, real email server"),
  bullet("What @Mock does — creates a fake object that records all calls but does nothing by default"),
  bullet("What @InjectMocks does — creates the real object under test and injects all @Mock fields into it automatically"),
  bullet("What when().thenReturn() does — programs the mock to return a specific value when a specific method is called"),
  bullet("What verify() does — asserts that a mock method was called with specific arguments the expected number of times"),
  bullet("The key difference — mocks give you complete control over dependency behaviour. Real objects do what they do."),
  empty(),
  study("30 mins"),
  p("Garbage Collection: JVM automatically reclaims heap memory for objects with no live references. You do not call free(). GC does it for you. Understanding GC matters because Stop-The-World pauses are real production problems."),
  empty(),
  p("Generational hypothesis: most objects die young. JVM exploits this:"),
  bullet("Young Generation (Eden + Survivor spaces): new objects born here. Minor GC is frequent and fast."),
  bullet("Old Generation (Tenured): objects that survive several minor GCs are promoted here. Major GC is infrequent but slow — Stop-The-World."),
  bullet("G1GC (Java 9+ default): divides heap into regions, collects highest-garbage regions first. Predictable pause times."),
  empty(),
  code("// Objects eligible for GC when no references reach them"),
  code("void example() {"),
  code("    PaymentRequest req = new PaymentRequest(...); // ref on stack"),
  code("    process(req);"),
  code("}  // req goes out of scope — object eligible for GC"),
  code(""),
  code("// Memory leak pattern — static collection holds references forever"),
  code("static List<PaymentRequest> audit = new ArrayList<>();"),
  code("audit.add(req); // req never eligible for GC — leak"),
  empty(),
  p("Mockito: create fake implementations of dependencies so you can test a class in isolation without needing a database, HTTP server, or real external service."),
  empty(),
  codetag("60 mins — upgrade Week 1 tests with Mockito"),
  p("Add to pom.xml (test scope — already included with spring-boot-starter-test):"),
  code("<dependency>"),
  code("    <groupId>org.mockito</groupId>"),
  code("    <artifactId>mockito-core</artifactId>"),
  code("    <scope>test</scope>"),
  code("</dependency>"),
  empty(),
  p("File: src/test/java/com/wallet/service/PaymentServiceTest.java"),
  code("@ExtendWith(MockitoExtension.class)"),
  code("class PaymentServiceTest {"),
  code(""),
  code("    @Mock"),
  code("    PaymentStrategy mockStrategy; // Mockito creates a fake implementation"),
  code(""),
  code("    @InjectMocks"),
  code("    PaymentService paymentService; // Mockito injects mockStrategy into this"),
  code(""),
  code("    @Test"),
  code("    void executePayment_validAmount_callsStrategy() {"),
  code("        paymentService.executePayment(500.0);"),
  code("        // verify the mock was called with exactly 500.0"),
  code("        verify(mockStrategy, times(1)).processPayment(500.0);"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void executePayment_strategyThrows_exceptionPropagates() {"),
  code("        doThrow(new RuntimeException(\"Gateway down\"))"),
  code("            .when(mockStrategy).processPayment(anyDouble());"),
  code("        assertThrows(RuntimeException.class,"),
  code("            () -> paymentService.executePayment(500.0));"),
  code("    }"),
  code("}"),
  empty(),
  b("Failure simulation — mock vs real:"),
  code("// Remove @Mock and create real UPIPayment instead"),
  code("PaymentStrategy realStrategy = new UPIPayment(\"user@upi\");"),
  code("// Now simulate gateway failure — you cannot"),
  code("// Real objects do what they do — you cannot control their behaviour in tests"),
  code("// Restore @Mock — mocks give you full control over dependency behaviour"),
  code("git commit -m \"test: add Mockito-based PaymentService tests\""),
  done("PaymentServiceTest uses @Mock and @InjectMocks. You explain what Mockito does and why mocks are necessary for isolated unit testing."),
  empty(),

  // DAY 12
  h2("DAY 12 — Friday (1.5 hrs)"),
  h3("LRU Cache implementation — Project: internals/LRUCache.java"),
  empty(),
  p("📚 Study Guide:"),
  b("LRU Cache — what you must understand:"),
  bullet("What LRU means — Least Recently Used. When cache is full, evict the entry that was accessed least recently."),
  bullet("Where LRU is used in real systems — Spring @Cacheable eviction, Redis eviction policies, CPU cache, browser cache"),
  bullet("Why LRU needs two data structures — HashMap for O(1) lookup + doubly-linked list for O(1) move-to-front and O(1) remove-from-tail"),
  bullet("What LinkedHashMap does internally — maintains a HashMap AND a doubly-linked list simultaneously. Both access order and FIFO modes available."),
  bullet("What accessOrder=true means — every get() moves the accessed entry to the tail (most recently used end)"),
  bullet("What accessOrder=false means (default) — insertion order only. get() does not reorder entries. This gives FIFO, not LRU."),
  bullet("What removeEldestEntry() does — called after every put(). Override to return true when size exceeds capacity to trigger eviction."),
  bullet("Why the eldest entry is the LRU entry — because get() moves accessed entries to the tail, the head is always least recently used"),
  tip("This is a common interview coding question. You must be able to implement it from memory using LinkedHashMap. Know why accessOrder=true makes it LRU vs FIFO."),
  empty(),
  study("20 mins"),
  p("LRU Cache: Least Recently Used. When cache is full, evict the entry that was used least recently. Used everywhere — Spring's @Cacheable, Redis eviction, CPU cache. Common interview question because it requires combining two data structures correctly."),
  empty(),
  p("Implementation: HashMap for O(1) lookup + doubly-linked list for O(1) move-to-front and O(1) remove-from-tail. Java's LinkedHashMap does both internally — use it unless asked to implement from scratch."),
  empty(),
  codetag("70 mins — build and test"),
  p("File: src/main/java/com/wallet/internals/LRUCache.java"),
  code("public class LRUCache<K, V> {"),
  code("    private final int capacity;"),
  code("    private final LinkedHashMap<K, V> cache;"),
  code(""),
  code("    public LRUCache(int capacity) {"),
  code("        this.capacity = capacity;"),
  code("        // accessOrder=true: get() moves entry to end (most recently used)"),
  code("        this.cache = new LinkedHashMap<>(capacity, 0.75f, true) {"),
  code("            @Override"),
  code("            protected boolean removeEldestEntry(Map.Entry<K, V> eldest) {"),
  code("                return size() > capacity; // evict when over capacity"),
  code("            }"),
  code("        };"),
  code("    }"),
  code(""),
  code("    public V get(K key) {"),
  code("        return cache.getOrDefault(key, null);"),
  code("    }"),
  code(""),
  code("    public void put(K key, V value) {"),
  code("        cache.put(key, value);"),
  code("    }"),
  code(""),
  code("    public int size() { return cache.size(); }"),
  code("}"),
  empty(),
  p("File: src/test/java/com/wallet/internals/LRUCacheTest.java"),
  code("class LRUCacheTest {"),
  code(""),
  code("    @Test"),
  code("    void get_existingKey_returnsValue() {"),
  code("        LRUCache<String, String> cache = new LRUCache<>(3);"),
  code("        cache.put(\"user1\", \"wallet-A\");"),
  code("        assertEquals(\"wallet-A\", cache.get(\"user1\"));"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void put_overCapacity_evictsLRUEntry() {"),
  code("        LRUCache<String, String> cache = new LRUCache<>(2);"),
  code("        cache.put(\"a\", \"1\");"),
  code("        cache.put(\"b\", \"2\");"),
  code("        cache.get(\"a\");          // access a — b is now LRU"),
  code("        cache.put(\"c\", \"3\");    // capacity exceeded — evict b"),
  code("        assertNull(cache.get(\"b\"));        // b evicted"),
  code("        assertNotNull(cache.get(\"a\"));     // a still present"),
  code("        assertNotNull(cache.get(\"c\"));     // c still present"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void put_withinCapacity_nothingEvicted() {"),
  code("        LRUCache<String, String> cache = new LRUCache<>(3);"),
  code("        cache.put(\"a\", \"1\");"),
  code("        cache.put(\"b\", \"2\");"),
  code("        cache.put(\"c\", \"3\");"),
  code("        assertEquals(3, cache.size());"),
  code("    }"),
  code("}"),
  empty(),
  b("Failure simulation — use accessOrder=false:"),
  code("// Change LinkedHashMap constructor to accessOrder=false"),
  code("// Run the eviction test"),
  code("// Now get() does NOT move entry to front — FIFO eviction instead of LRU"),
  code("// The test fails — b is not evicted even though a was accessed more recently"),
  code("// Restore accessOrder=true. This is what makes it LRU, not FIFO."),
  code("git commit -m \"feat: add LRU cache using LinkedHashMap with eviction test\""),
  done("LRUCache is implemented and all 3 tests pass. You explain why LinkedHashMap with accessOrder=true gives LRU behaviour. You can code this from memory on paper."),
  empty(),

  // DAY 13
  h2("DAY 13 — Saturday (2-3 hrs)"),
  h3("Mockito depth + integration testing groundwork"),
  empty(),
  p("📚 Study Guide:"),
  b("ArgumentCaptor — what you must understand:"),
  bullet("What ArgumentCaptor does — captures the actual argument that was passed to a mock method so you can assert on it"),
  bullet("When to use it — when you cannot predict the exact argument value upfront (e.g. auto-generated timestamps, UUIDs)"),
  bullet("How to use it — declare captor, pass captor.capture() inside verify(), then call captor.getValue() to get what was actually passed"),
  bullet("Real use case — verifying the exact PaymentRequest sent to a payment gateway, including auto-generated fields like timestamp or transaction ID"),
  empty(),
  b("@Spy — what you must understand:"),
  bullet("What @Spy does — wraps a REAL object but lets you verify calls on it and stub specific methods if needed"),
  bullet("The key difference from @Mock — @Mock creates a complete fake (all methods do nothing). @Spy wraps a real object (methods execute normally unless stubbed)."),
  bullet("When to use @Spy — when you want mostly real behaviour but need to verify that a method was called or stub one specific method"),
  bullet("When to use @Mock instead — almost always. Use @Spy only when the real implementation genuinely matters for the test."),
  tip("Interview question: what is the difference between @Mock and @Spy? Know this answer cold."),
  empty(),
  study("40 mins"),
  p("Mockito beyond @Mock: argument captors let you inspect what was passed to a mock. Spy lets you wrap a real object and verify calls on it. These two are the most commonly needed Mockito features beyond the basics."),
  empty(),
  code("// ArgumentCaptor — capture what was passed to a mock"),
  code("@Test"),
  code("void executePayment_captureAmount() {"),
  code("    ArgumentCaptor<Double> captor = ArgumentCaptor.forClass(Double.class);"),
  code("    paymentService.executePayment(750.0);"),
  code("    verify(mockStrategy).processPayment(captor.capture());"),
  code("    assertEquals(750.0, captor.getValue());"),
  code("}"),
  empty(),
  code("// @Spy — real object, verify calls on it"),
  code("@Spy"),
  code("PaymentEventPublisher publisher = new PaymentEventPublisher();"),
  code("// calls real methods unless stubbed"),
  code("// verify(publisher).publish(anyString(), anyDouble(), anyString());"),
  empty(),
  codetag("Build comprehensive test suite — 80 mins"),
  p("Write Mockito tests for PaymentContext and PaymentFactory covering:"),
  bullet("Verify strategy is called with correct amount via ArgumentCaptor"),
  bullet("Verify exception from strategy propagates correctly"),
  bullet("Verify factory creates correct implementation for each type"),
  bullet("Verify factory throws for unknown type"),
  empty(),
  p("File: src/test/java/com/wallet/payment/PaymentFactoryTest.java"),
  code("class PaymentFactoryTest {"),
  code(""),
  code("    @Test"),
  code("    void create_upiType_returnsUPIPayment() {"),
  code("        PaymentStrategy strategy = PaymentFactory.create(\"UPI\", \"user@upi\");"),
  code("        assertInstanceOf(UPIPayment.class, strategy);"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void create_cardType_returnsCardPayment() {"),
  code("        PaymentStrategy strategy = PaymentFactory.create(\"CARD\", \"**** 4242\");"),
  code("        assertInstanceOf(CardPayment.class, strategy);"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void create_unknownType_throwsIllegalArgument() {"),
  code("        assertThrows(IllegalArgumentException.class,"),
  code("            () -> PaymentFactory.create(\"CRYPTO\", \"addr\"));"),
  code("    }"),
  code(""),
  code("    @Test"),
  code("    void create_caseInsensitive_works() {"),
  code("        assertDoesNotThrow(() -> PaymentFactory.create(\"upi\", \"user@upi\"));"),
  code("    }"),
  code("}"),
  empty(),
  code("git commit -m \"test: add comprehensive PaymentFactory and PaymentContext tests\""),
  done("Test suite has 15+ tests. All green. You use ArgumentCaptor correctly. You explain the difference between @Mock and @Spy."),
  empty(),

  // DAY 14
  h2("DAY 14 — Sunday (2-3 hrs)"),
  h3("Week 2 Checkpoint — answer from memory, no notes"),
  empty(),
  p("📚 Study Guide:"),
  b("Answer every question from memory. No notes. No IDE."),
  bullet("Walk through HashMap.put() step by step — hashCode, bucket calculation, collision handling, equals check"),
  bullet("What is treeification? When does it trigger? Why does it exist?"),
  bullet("Why does ConcurrentHashMap not allow null keys? What would go wrong if it did?"),
  bullet("You have 1 million entries going into a HashMap. What initial capacity do you set and why?"),
  bullet("Why is ArrayList faster than LinkedList for random access? Use the word \"cache\" in your answer."),
  bullet("When would you choose LinkedList over ArrayList? Be specific about the access pattern."),
  bullet("Code an LRU cache from memory on paper using LinkedHashMap. What does accessOrder=true do?"),
  bullet("Where does a local variable live? Where does the object it references live?"),
  bullet("What is a Stop-The-World pause? Which GC generation causes longer pauses and why?"),
  bullet("What is the difference between @Mock and @Spy? When would you use each?"),
  warn("If you cannot code LRU from memory or explain HashMap collision handling without notes — do not move to Week 3. Concurrency builds directly on these internals."),
  empty(),
  b("Run the full test suite first:"),
  code("mvn clean test"),
  code("# Target: 15+ tests, all green, zero ignored"),
  empty(),
  b("Checkpoint questions — answer each out loud:"),
  empty(),
  b("HashMap internals:"),
  bullet("Walk through HashMap.put() step by step — hashCode, bucket calculation, collision handling"),
  bullet("What is treeification? When does it trigger? Why does it exist?"),
  bullet("Why does ConcurrentHashMap not allow null keys? What would go wrong if it did?"),
  bullet("You have 1 million entries going into a HashMap. What initial capacity do you set and why?"),
  empty(),
  b("Collections:"),
  bullet("Why is ArrayList faster than LinkedList for random access? Use the word 'cache' in your answer."),
  bullet("When would you choose LinkedList over ArrayList? Be specific."),
  bullet("Code an LRU cache from memory — no IDE. What does accessOrder=true do?"),
  empty(),
  b("JVM memory:"),
  bullet("Where does a local variable live? Where does the object it points to live?"),
  bullet("What is a Stop-The-World pause? Which GC generation causes longer ones?"),
  bullet("Show a memory leak pattern using a static collection."),
  empty(),
  b("Mockito:"),
  bullet("What is the difference between @Mock and @Spy?"),
  bullet("When would you use ArgumentCaptor instead of verify(mock).method(exactValue)?"),
  bullet("Why do mocks exist — what problem do they solve?"),
  empty(),
  b("GitHub check:"),
  bullet("15+ tests committed and green"),
  bullet("All commit messages follow type: description format"),
  bullet("LRUCache, HashMapInternalsTest, ConcurrentHashMapTest all present"),
  empty(),
  warn("If you cannot code LRU from memory or explain HashMap collision handling without notes — do not move to Week 3. These are Week 3 prerequisites. Concurrency builds on top of this foundation."),
  market("Passing Week 2 means you understand Java internals at the depth that product company interviewers specifically probe. Most 1 YOE developers cannot explain treeification or LinkedHashMap's accessOrder parameter. You now can — and you have working code that proves it."),
  sep()

);

return items;
};
