const { Document, Packer, Paragraph, TextRun, HeadingLevel, LevelFormat, AlignmentType, BorderStyle } = require('docx');
const fs = require('fs');

// ─── Style helpers ───────────────────────────────────────────
const weekHeading = (text) => new Paragraph({
  spacing: { before: 400, after: 160 },
  children: [new TextRun({ text, bold: true, size: 36, color: '1F4E79', font: 'Arial' })]
});

const dayHeading = (text) => new Paragraph({
  spacing: { before: 300, after: 100 },
  border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: '2E75B6', space: 4 } },
  children: [new TextRun({ text, bold: true, size: 28, color: '2E75B6', font: 'Arial' })]
});

const topicGroupLabel = (text) => new Paragraph({
  spacing: { before: 180, after: 60 },
  children: [new TextRun({ text, bold: true, size: 22, color: '404040', font: 'Arial' })]
});

const topicItem = (text) => new Paragraph({
  numbering: { reference: 'bullets', level: 0 },
  spacing: { before: 40, after: 40 },
  children: [new TextRun({ text, size: 20, font: 'Arial', color: '222222' })]
});

const subItem = (text) => new Paragraph({
  numbering: { reference: 'subbullets', level: 0 },
  spacing: { before: 20, after: 20 },
  children: [new TextRun({ text, size: 19, font: 'Arial', color: '444444' })]
});

const note = (text) => new Paragraph({
  spacing: { before: 80, after: 80 },
  children: [new TextRun({ text: `📌 ${text}`, italics: true, size: 19, font: 'Arial', color: '555555' })]
});

const spacer = () => new Paragraph({ spacing: { before: 60, after: 60 }, children: [new TextRun('')] });

const pageBreak = () => new Paragraph({
  pageBreakBefore: true,
  children: [new TextRun('')]
});

// ─── CONTENT ─────────────────────────────────────────────────
const content = [

  // TITLE
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 0, after: 80 },
    children: [new TextRun({ text: 'Phase 1 Study Guide', bold: true, size: 52, color: '1F4E79', font: 'Arial' })]
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 0, after: 60 },
    children: [new TextRun({ text: 'Payment Wallet System — Java Backend Roadmap', size: 26, color: '555555', font: 'Arial' })]
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 0, after: 300 },
    children: [new TextRun({ text: 'What to understand on each day — before opening your IDE', italics: true, size: 22, color: '888888', font: 'Arial' })]
  }),

  // ══════════════════════════════════════
  // WEEK 1
  // ══════════════════════════════════════
  weekHeading('WEEK 1 — Java OOP Depth + Git + Maven + Testing Habit'),

  // DAY 1
  dayHeading('DAY 1 — Git Workflow + Maven Basics'),
  topicGroupLabel('Git — what you must understand:'),
  topicItem('What git is actually for — not backup, but communication between engineers'),
  topicItem('What an atomic commit is — one logical change, one commit, one clear message'),
  topicItem('Conventional commits format — type: description — and what each type means (feat, fix, refactor, chore, test, docs)'),
  topicItem('Why commit history matters — senior engineers read history before code'),
  topicItem('What git rebase -i does — combining messy local commits before pushing'),
  topicItem('What HEAD~3 means — referring to the last 3 commits'),
  topicItem('Why squashing exists — keeping history readable for the team'),
  spacer(),
  topicGroupLabel('Maven — what you must understand:'),
  topicItem('What Maven actually does — dependency management, build lifecycle, packaging'),
  topicItem('Dependency scopes and what each means:'),
  subItem('compile — default, available everywhere including production jar'),
  subItem('test — JUnit and Mockito go here, NOT included in production jar'),
  subItem('provided — container provides it at runtime, not packaged'),
  subItem('runtime — not needed to compile but needed to run'),
  topicItem('What a transitive dependency is — when you add spring-boot-starter-web, what else comes with it'),
  topicItem('What mvn dependency:tree shows — every dependency and where it came from'),
  topicItem('What a fat jar is — Spring Boot packages ALL dependencies inside the jar'),
  topicItem('Why the fat jar runs anywhere — no separate classpath setup needed'),
  topicItem('What BOOT-INF/lib/ contains inside the jar'),
  note('When a NoClassDefFoundError hits in production, mvn dependency:tree is how you find the cause.'),
  spacer(),

  // DAY 2
  dayHeading('DAY 2 — Interfaces vs Abstract Classes + Strategy Pattern'),
  topicGroupLabel('Interfaces vs Abstract Classes — what you must understand:'),
  topicItem('What an interface is — a contract defining capabilities, not implementation'),
  topicItem('What an abstract class is — partial implementation, cannot be instantiated'),
  topicItem('What changed in Java 8 — default methods added to interfaces, why'),
  topicItem('What changed in Java 9 — private methods inside interfaces'),
  topicItem('What "instance state" means — fields that belong to a specific object instance'),
  topicItem('Why interfaces CANNOT hold instance state — the fundamental reason, not just the rule'),
  topicItem('Why abstract classes CAN hold instance state — they represent a base object'),
  topicItem('Multiple inheritance — why Java allows multiple interface implementation but not multiple class extension'),
  topicItem('The one real post-Java-8 rule: if you need instance state, use abstract class. Otherwise, prefer interface.'),
  spacer(),
  topicGroupLabel('Strategy Pattern — what you must understand:'),
  topicItem('What problem Strategy pattern solves — eliminating if-else chains that grow with every new payment type'),
  topicItem('What the three parts of Strategy are — interface (strategy), concrete classes (implementations), context (holder)'),
  topicItem('Why Strategy satisfies OCP — you add new payment types without modifying existing PaymentService code'),
  topicItem('How Strategy enables testability — you can pass a mock strategy in tests instead of a real UPI call'),
  topicItem('Why UPIPayment and CardPayment implement the interface not extend a class — because they have their own state (upiId, maskedCard)'),
  note('The connection to test: code that depends on an interface can be tested with a mock. Code that depends on a concrete class cannot.'),
  spacer(),

  // DAY 3
  dayHeading('DAY 3 — SOLID Principles'),
  topicGroupLabel('Why SOLID exists — before learning the rules:'),
  topicItem('The real problem SOLID solves — code that is hard to change, hard to test, and breaks in unexpected places when modified'),
  topicItem('How SOLID violations show up in code review — the exact language senior engineers use'),
  spacer(),
  topicGroupLabel('SRP — Single Responsibility Principle:'),
  topicItem('What "responsibility" actually means — a reason to change, not "does one thing"'),
  topicItem('Why a class with multiple responsibilities is a problem — two teams can conflict on the same file'),
  topicItem('How to identify an SRP violation — ask "how many different reasons could make me change this class?"'),
  topicItem('Example in your project — PaymentService doing payment logic AND email AND logging is 3 responsibilities'),
  spacer(),
  topicGroupLabel('OCP — Open/Closed Principle:'),
  topicItem('What "open for extension, closed for modification" means in plain English'),
  topicItem('How your PaymentStrategy interface already implements OCP — adding NetBanking never touches PaymentService'),
  topicItem('What an OCP violation looks like — a switch/if-else that grows every time a new type is added'),
  spacer(),
  topicGroupLabel('LSP — Liskov Substitution Principle:'),
  topicItem('What "honouring the contract" means — every implementation must behave as the interface promises'),
  topicItem('What an LSP violation looks like — a subclass that throws for inputs the interface says are valid'),
  topicItem('Why LSP violations break caller code — callers trust the abstraction, not the implementation'),
  spacer(),
  topicGroupLabel('ISP — Interface Segregation Principle:'),
  topicItem('What a "fat interface" is — an interface that forces implementations to provide methods they do not use'),
  topicItem('Why fat interfaces create silent bugs — implementations throw UnsupportedOperationException or return garbage'),
  topicItem('How to split interfaces — by what each caller actually needs, not by what seems logical to group together'),
  spacer(),
  topicGroupLabel('DIP — Dependency Inversion Principle:'),
  topicItem('What "depend on abstraction, not concrete class" means'),
  topicItem('Why depending on UPIPayment directly makes PaymentService untestable — you cannot mock a hardcoded dependency'),
  topicItem('How constructor injection enables DIP — the interface is passed in, not created inside'),
  topicItem('Why DIP is the principle that makes mocking and testing possible'),
  note('SOLID is interview vocabulary. Know all 5 using your own project as the example, not a textbook definition.'),
  spacer(),

  // DAY 4
  dayHeading('DAY 4 — Strategy Pattern (complete) + Factory Pattern'),
  topicGroupLabel('Strategy Pattern — completing your understanding:'),
  topicItem('What PaymentContext is — the holder of the current strategy, the part that executes it'),
  topicItem('Why runtime switching matters — a user can switch from UPI to Card without restarting the app'),
  topicItem('What happens if no strategy is set — defensive check with IllegalStateException'),
  topicItem('How Strategy, Context, and Interface relate to each other — draw the relationship'),
  spacer(),
  topicGroupLabel('Factory Pattern — what you must understand:'),
  topicItem('What problem Factory solves — the caller should not need to know which class to instantiate'),
  topicItem('What "factory decides which class to create" means — based on input, not hardcoded'),
  topicItem('Why a static factory method is common — no need to instantiate the factory itself'),
  topicItem('Why the default/unknown case must always be handled — missing it causes runtime MatchException with no useful message'),
  topicItem('How Factory and Strategy work together — Factory creates the right strategy, Context holds and runs it'),
  note('Interview question: what is the difference between Factory and Strategy? Factory decides what to create. Strategy decides how to behave.'),
  spacer(),

  // DAY 5
  dayHeading('DAY 5 — Singleton Pattern + Builder Pattern'),
  topicGroupLabel('Singleton Pattern — what you must understand:'),
  topicItem('What Singleton is — only one instance of a class exists in the entire JVM'),
  topicItem('Real use cases — config holders, connection pools, token providers, thread pools'),
  topicItem('Why the naive version is broken under concurrency — Thread A and B both see null, both create instances'),
  topicItem('What volatile does in this context — prevents instruction reordering during object construction'),
  topicItem('Why reordering is dangerous without volatile — Thread B can see a non-null but partially constructed object'),
  topicItem('What double-checked locking is — check without lock, then check again inside lock'),
  topicItem('Why both checks are needed — the first avoids locking on every call, the second prevents duplicate creation'),
  topicItem('Why synchronized alone is not enough — it prevents concurrent creation but not reordering'),
  spacer(),
  topicGroupLabel('Builder Pattern — what you must understand:'),
  topicItem('What problem Builder solves — telescoping constructors with many optional parameters become unreadable'),
  topicItem('What telescoping constructors look like — new PaymentRequest("u1","u2",500.0,"INR","","") — unreadable'),
  topicItem('How Builder separates required from optional fields — required in Builder constructor, optional as fluent methods'),
  topicItem('What method chaining (fluent API) is — each setter returns this so calls can be chained'),
  topicItem('Why the object is immutable — private constructor, final fields, only Builder can create it'),
  topicItem('Where Lombok @Builder saves time — generates all of this automatically in Spring Boot projects'),
  note('PaymentRequest is exactly the right use case for Builder — it has 3 required fields and 3+ optional ones.'),
  spacer(),

  // DAY 6
  dayHeading('DAY 6 — Observer Pattern + Week 1 Integration'),
  topicGroupLabel('Observer Pattern — what you must understand:'),
  topicItem('What problem Observer solves — when one event needs to notify multiple independent handlers'),
  topicItem('The wallet example — payment success must trigger: audit log, fraud check, notification. Without Observer, PaymentService calls all three directly.'),
  topicItem('Why direct coupling is a problem — adding a fourth handler means modifying PaymentService'),
  topicItem('What the three parts of Observer are — subject (publisher), observer (interface), concrete observers (handlers)'),
  topicItem('How Observer satisfies OCP — adding a new observer never modifies PaymentEventPublisher'),
  topicItem('How Observer relates to the real world — Spring ApplicationEvents, Kafka consumers, and webhook systems all use this pattern'),
  topicItem('What unsubscribe means and when you need it — preventing memory leaks when observers are removed'),
  spacer(),
  topicGroupLabel('Week 1 integration — what to verify:'),
  topicItem('Every class built this week exists in the correct package inside payment-wallet'),
  topicItem('Every class has at least one test'),
  topicItem('All commit messages follow the type: description format'),
  topicItem('No WIP, fix, fix2, or asdf commits in GitHub history'),
  spacer(),

  // DAY 7
  dayHeading('DAY 7 — Week 1 Checkpoint'),
  topicGroupLabel('Questions you must answer from memory, no notes:'),
  topicItem('Why can an interface not hold instance state? What exactly happens if you try?'),
  topicItem('After Java 8, what is the one remaining reason to use an abstract class over an interface?'),
  topicItem('Explain LSP using your PaymentStrategy implementations as the example'),
  topicItem('Walk through Strategy pattern using PaymentContext — what problem does it solve?'),
  topicItem('Why does JwtTokenProvider need volatile? What breaks without it?'),
  topicItem('Why does Builder exist? Show a PaymentRequest construction with 5 fields — would a constructor be readable?'),
  topicItem('How does Observer satisfy OCP? What would violate OCP in the same scenario?'),
  topicItem('What does git rebase -i do and when would you use it?'),
  topicItem('What is inside a fat jar and why does Spring Boot package it that way?'),
  note('If you cannot answer any question without notes — do not move to Week 2. Spend the remaining time on the weak area.'),
  spacer(),

  pageBreak(),

  // ══════════════════════════════════════
  // WEEK 2
  // ══════════════════════════════════════
  weekHeading('WEEK 2 — Java Internals: Collections + JVM Memory'),

  // DAY 8
  dayHeading('DAY 8 — HashMap Internals Part 1: hashCode, buckets, collision'),
  topicGroupLabel('What you must understand before touching code:'),
  topicItem('What a hash function is — converts any object into an integer'),
  topicItem('What hashCode() returns — an integer, not necessarily unique'),
  topicItem('Internal structure of HashMap — an array of Node objects, each Node holds key, value, hash, next pointer'),
  topicItem('Default capacity — 16 buckets. What this means physically.'),
  topicItem('How put() decides which bucket — (capacity - 1) & hash — bitwise AND, not modulo'),
  topicItem('Why bitwise AND instead of modulo — faster at CPU level'),
  topicItem('What a collision is — two different keys producing the same bucket index'),
  topicItem('How collisions are handled — linked list chaining inside the bucket'),
  topicItem('How get() finds a value when there is a collision — walks the chain, compares with equals()'),
  topicItem('The equals() + hashCode() contract — if two objects are equal, they must have the same hashCode'),
  topicItem('What breaks when you override equals() without overriding hashCode() — get() returns null for a key you just put'),
  topicItem('Null key handling — always stored in bucket 0, special case in putVal()'),
  note('The FB and Ea hash collision ("FB".hashCode() == "Ea".hashCode()) is the classic interview verification. Know this.'),
  spacer(),

  // DAY 9
  dayHeading('DAY 9 — HashMap Internals Part 2: treeification, resize, ConcurrentHashMap'),
  topicGroupLabel('Treeification — what you must understand:'),
  topicItem('What treeification is — converting a bucket\'s linked list into a Red-Black TreeNode'),
  topicItem('When it triggers — TREEIFY_THRESHOLD = 8 nodes in one bucket'),
  topicItem('Why it exists — O(n) list lookup becomes O(log n) tree lookup when many keys collide'),
  topicItem('When it matters in production — malicious input designed to force all keys into one bucket (hash collision attack)'),
  spacer(),
  topicGroupLabel('Resize — what you must understand:'),
  topicItem('When resize triggers — size > capacity × loadFactor (default 0.75)'),
  topicItem('What happens during resize — capacity doubles, every entry rehashed into new array — O(n)'),
  topicItem('Why resize is expensive — every entry must be recalculated and moved'),
  topicItem('How to avoid resize — set initial capacity to expectedSize / 0.75 + 1 when size is known upfront'),
  spacer(),
  topicGroupLabel('ConcurrentHashMap — what you must understand:'),
  topicItem('Why HashMap is not thread-safe — two threads calling put() can corrupt the internal array'),
  topicItem('How ConcurrentHashMap achieves thread safety — CAS + synchronized on individual buckets (Java 8+), no global lock'),
  topicItem('Why ConcurrentHashMap does NOT allow null keys or null values — ambiguity in concurrent context'),
  topicItem('The null ambiguity problem — get(null)==null could mean key not present OR value is null, indistinguishable concurrently'),
  topicItem('When to use HashMap vs ConcurrentHashMap — single thread: HashMap. Multiple threads: ConcurrentHashMap.'),
  note('This is the most common Java internals interview topic at product companies. Know all of it.'),
  spacer(),

  // DAY 10
  dayHeading('DAY 10 — ArrayList vs LinkedList + JVM Memory Basics'),
  topicGroupLabel('ArrayList — what you must understand:'),
  topicItem('Internal structure — backed by an Object array'),
  topicItem('Random access O(1) — index directly into array, one operation'),
  topicItem('Add to end O(1) amortised — array doubles when full, occasional O(n) copy'),
  topicItem('Add to middle O(n) — every element after insertion point must shift right'),
  topicItem('Why ArrayList is cache-friendly — contiguous memory means CPU prefetcher works efficiently'),
  spacer(),
  topicGroupLabel('LinkedList — what you must understand:'),
  topicItem('Internal structure — doubly-linked nodes, each holds value + prev pointer + next pointer'),
  topicItem('Add/remove at head or tail O(1) — just update pointers'),
  topicItem('Random access O(n) — must walk from head to find index'),
  topicItem('Why LinkedList is cache-unfriendly — nodes scattered in heap, pointer chasing defeats CPU cache'),
  topicItem('The real-world rule — use ArrayList almost always. Use LinkedList only for frequent head/tail operations with no random access.'),
  topicItem('Why ArrayDeque is better than LinkedList for queue behaviour — cache-friendly, no node allocation overhead'),
  spacer(),
  topicGroupLabel('JVM Memory — four areas you must know:'),
  topicItem('Heap — all objects live here. GC manages this. Shared across all threads.'),
  topicItem('Stack — one per thread. Holds stack frames. Each frame holds local variables and method call info. StackOverflowError when exceeded.'),
  topicItem('Metaspace — class metadata and static fields. Not GC\'d normally. OutOfMemoryError if unlimited.'),
  topicItem('PC Register — current instruction pointer per thread.'),
  topicItem('Stack vs Heap in a method — the reference lives on the stack, the object it points to lives on the heap'),
  topicItem('When an object becomes eligible for GC — when no live references reach it'),
  note('Interview question: where does a local variable live? Stack. Where does the object it references live? Heap.'),
  spacer(),

  // DAY 11
  dayHeading('DAY 11 — Garbage Collection Basics + Mockito Introduced'),
  topicGroupLabel('Garbage Collection — what you must understand:'),
  topicItem('What GC does — automatically reclaims heap memory for objects with no live references'),
  topicItem('Generational hypothesis — most objects die young. JVM exploits this with different GC strategies per generation.'),
  topicItem('Young Generation (Eden + Survivor spaces) — new objects born here. Minor GC is frequent and fast.'),
  topicItem('Old Generation (Tenured) — objects that survive several minor GCs are promoted here. Major GC is infrequent but slow.'),
  topicItem('Stop-The-World pause — JVM freezes all threads to run GC. This is a real production problem.'),
  topicItem('G1GC — Java 9+ default. Divides heap into regions, collects highest-garbage regions first. Predictable pause times.'),
  topicItem('Memory leak pattern — static collection holding references forever. Objects never become eligible for GC.'),
  spacer(),
  topicGroupLabel('Mockito — what you must understand:'),
  topicItem('What Mockito does — creates fake implementations of dependencies so you can test a class in isolation'),
  topicItem('Why mocks are necessary — without them, testing PaymentService requires a real UPI gateway, a real database, a real email server'),
  topicItem('What @Mock does — creates a fake object that records calls but does nothing by default'),
  topicItem('What @InjectMocks does — creates the real object under test and injects all @Mock fields into it'),
  topicItem('What when/thenReturn does — tells the mock what to return when a specific method is called'),
  topicItem('What verify() does — asserts that a mock method was called with specific arguments'),
  topicItem('The difference between a mock and a real object — you control mock behaviour completely, real objects do what they do'),
  spacer(),

  // DAY 12
  dayHeading('DAY 12 — LRU Cache Implementation'),
  topicGroupLabel('LRU Cache — what you must understand:'),
  topicItem('What LRU means — Least Recently Used. When cache is full, evict the entry used least recently.'),
  topicItem('Where LRU is used in real systems — Spring @Cacheable, Redis eviction policy, CPU cache, browser cache'),
  topicItem('Why LRU requires two data structures — HashMap for O(1) lookup + doubly-linked list for O(1) move-to-front and remove-from-tail'),
  topicItem('What LinkedHashMap does internally — maintains insertion order OR access order depending on constructor'),
  topicItem('What accessOrder=true means — get() moves the accessed entry to the end (most recently used position)'),
  topicItem('What accessOrder=false means — FIFO order, not LRU. get() does not move entries.'),
  topicItem('What removeEldestEntry() does — called after every put(), return true to evict the oldest entry'),
  topicItem('Why the eldest entry is the LRU entry — because get() moves accessed entries to the end'),
  topicItem('The capacity formula — evict when size() > capacity'),
  note('This is a common interview coding question. You must be able to implement it from memory on paper using LinkedHashMap.'),
  spacer(),

  // DAY 13
  dayHeading('DAY 13 — Mockito Depth: ArgumentCaptor + @Spy'),
  topicGroupLabel('ArgumentCaptor — what you must understand:'),
  topicItem('What ArgumentCaptor does — captures the actual argument passed to a mock method so you can assert on it'),
  topicItem('When to use it vs verify(mock).method(exactValue) — use captor when you cannot predict the exact argument upfront'),
  topicItem('How to use it — declare captor, pass captor.capture() to verify(), then call captor.getValue()'),
  topicItem('Real use case — verifying the exact PaymentRequest passed to a payment gateway, including auto-generated fields'),
  spacer(),
  topicGroupLabel('@Spy — what you must understand:'),
  topicItem('What @Spy does — wraps a REAL object but lets you verify calls and stub specific methods'),
  topicItem('The difference between @Mock and @Spy — @Mock creates a fake (all methods do nothing). @Spy wraps a real object (methods execute normally unless stubbed).'),
  topicItem('When to use @Spy — when you want mostly real behaviour but need to verify that a method was called'),
  topicItem('When NOT to use @Spy — if you can use @Mock, use @Mock. Spies are for cases where the real implementation matters.'),
  note('Interview question: what is the difference between @Mock and @Spy? Know this cold.'),
  spacer(),

  // DAY 14
  dayHeading('DAY 14 — Week 2 Checkpoint'),
  topicGroupLabel('Questions you must answer from memory, no notes:'),
  topicItem('Walk through HashMap.put() step by step — hashCode, bucket calculation, collision handling'),
  topicItem('What is treeification? When does it trigger? Why does it exist?'),
  topicItem('Why does ConcurrentHashMap not allow null keys? What would go wrong if it did?'),
  topicItem('You have 1 million entries going into a HashMap. What initial capacity do you set and why?'),
  topicItem('Why is ArrayList faster than LinkedList for random access? Use the word "cache" in your answer.'),
  topicItem('When would you choose LinkedList over ArrayList? Be specific.'),
  topicItem('Code an LRU cache from memory — no IDE. What does accessOrder=true do?'),
  topicItem('Where does a local variable live? Where does the object it points to live?'),
  topicItem('What is a Stop-The-World pause? Which GC generation causes longer ones?'),
  topicItem('What is the difference between @Mock and @Spy?'),
  note('If you cannot code LRU from memory or explain HashMap collision handling without notes — do not move to Week 3.'),
  spacer(),

  pageBreak(),

  // ══════════════════════════════════════
  // WEEK 3
  // ══════════════════════════════════════
  weekHeading('WEEK 3 — Java Concurrency Advanced + Docker Basics'),

  // DAY 15
  dayHeading('DAY 15 — Thread Lifecycle + ExecutorService'),
  topicGroupLabel('Thread lifecycle — what you must understand:'),
  topicItem('All 6 states and what each means: NEW → RUNNABLE → RUNNING → BLOCKED / WAITING / TIMED_WAITING → TERMINATED'),
  topicItem('What BLOCKED means — thread is waiting to acquire a synchronized lock held by another thread'),
  topicItem('What WAITING means — thread called wait() or join() with no timeout, waiting indefinitely'),
  topicItem('What TIMED_WAITING means — thread called sleep(n) or wait(n) with a timeout'),
  topicItem('Why a thread can be alive but not running — it is in BLOCKED or WAITING state'),
  spacer(),
  topicGroupLabel('Why raw threads are never used in production:'),
  topicItem('Memory cost — each thread needs ~1MB stack by default. 10,000 threads = ~10GB RAM for stacks alone.'),
  topicItem('OS scheduling overhead — creating and destroying threads is expensive'),
  topicItem('No control over pool size — unbounded thread creation can crash the JVM'),
  spacer(),
  topicGroupLabel('ExecutorService — what you must understand:'),
  topicItem('What ExecutorService is — manages a reusable pool of threads'),
  topicItem('newFixedThreadPool — bounded, predictable resource usage. Always prefer this over cached.'),
  topicItem('What Future is — a handle to an async result. get() blocks until result is ready.'),
  topicItem('Why future.get() without timeout is dangerous — it blocks forever if the task hangs'),
  topicItem('Why pool.shutdown() is always required — without it, JVM will not exit because pool threads are still alive'),
  topicItem('What awaitTermination() does — waits for in-flight tasks to complete before the JVM exits'),
  note('Production rule: always use future.get(timeout, unit). Never block forever.'),
  spacer(),

  // DAY 16
  dayHeading('DAY 16 — synchronized vs volatile vs AtomicInteger + Java Memory Model + BalanceManager with CAS'),
  topicGroupLabel('Java Memory Model — the root cause of all race conditions:'),
  topicItem('What the Java Memory Model is — each CPU thread has its own cache copy of variables'),
  topicItem('What a race condition is — two threads reading and writing the same data without coordination, producing wrong results'),
  topicItem('The lost update problem — Thread 1 reads balance=1000, Thread 2 reads balance=1000, both add 500, both write 1500. Money disappeared.'),
  spacer(),
  topicGroupLabel('synchronized — what you must understand:'),
  topicItem('What synchronized provides — mutual exclusion (only one thread at a time) AND memory visibility (changes flushed to main memory)'),
  topicItem('Method-level vs block-level synchronized — block-level is more granular, better for performance'),
  topicItem('What the monitor/lock is — every Java object has an intrinsic lock. synchronized acquires it.'),
  topicItem('The cost — threads queue up waiting for the lock. Too much synchronized = bottleneck.'),
  spacer(),
  topicGroupLabel('volatile — what you must understand:'),
  topicItem('What volatile provides — memory visibility only. Reads and writes go directly to main memory, not CPU cache.'),
  topicItem('What volatile does NOT provide — atomicity. count++ is three operations (read, increment, write). volatile does not protect this.'),
  topicItem('When volatile is correct — boolean flags like isRunning that are written by one thread and read by others'),
  topicItem('When volatile is wrong — any read-modify-write operation like counter++'),
  spacer(),
  topicGroupLabel('AtomicInteger and CAS — what you must understand:'),
  topicItem('What CAS means — Compare And Swap. Hardware-level atomic operation.'),
  topicItem('How CAS works — "if current value is X, set it to Y. Otherwise retry." All in one CPU instruction.'),
  topicItem('Why CAS is faster than synchronized — no lock, no thread queuing, no context switch'),
  topicItem('What AtomicLong.compareAndSet() does — returns false if value changed between read and write, caller retries'),
  topicItem('The CAS loop pattern — read current value, compute new value, CAS. If CAS fails, loop and retry.'),
  note('The BalanceManager debit() uses a CAS loop. This is exactly how real payment systems handle concurrent balance updates.'),
  spacer(),

  // DAY 17
  dayHeading('DAY 17 — CompletableFuture'),
  topicGroupLabel('Why CompletableFuture exists:'),
  topicItem('Problem with Future — get() blocks the calling thread. You cannot chain operations or handle failures elegantly.'),
  topicItem('What CompletableFuture adds — non-blocking chaining, parallel composition, and declarative error handling'),
  spacer(),
  topicGroupLabel('Core operations — what each does and when to use it:'),
  topicItem('supplyAsync() — runs a task asynchronously on the common ForkJoinPool (or a given executor), returns a CompletableFuture'),
  topicItem('thenApply() — transforms the result synchronously, like map(). Use when the transformation is not async.'),
  topicItem('thenCompose() — chains a dependent async step, like flatMap(). Use when Step 2 is also async and depends on Step 1\'s result.'),
  topicItem('thenCombine() — runs two independent futures in parallel and combines their results when both complete'),
  topicItem('exceptionally() — fallback value or recovery when any step in the chain throws an exception'),
  topicItem('join() — like get() but throws unchecked exception. Use inside lambdas where checked exceptions are not allowed.'),
  spacer(),
  topicGroupLabel('The key distinction to internalize:'),
  topicItem('thenCompose vs thenCombine — compose is sequential (Step 2 needs Step 1). combine is parallel (Step A and Step B are independent).'),
  topicItem('Wallet example — fraud check and bank validation are independent. Run with thenCombine. Sequential would waste time.'),
  note('If fraudCheck=500ms and bankValidation=700ms, sequential=1200ms, parallel=~700ms. This is the real performance win.'),
  spacer(),

  // DAY 18
  dayHeading('DAY 18 — Deadlocks + Docker Basics'),
  topicGroupLabel('Deadlocks — what you must understand:'),
  topicItem('What a deadlock is — Thread 1 holds lock A waiting for B. Thread 2 holds B waiting for A. Neither can proceed.'),
  topicItem('The four conditions required for deadlock — mutual exclusion, hold and wait, no preemption, circular wait'),
  topicItem('How to prevent deadlock — always acquire locks in the same global order (e.g. lowest account ID first)'),
  topicItem('Why lock ordering works — if all threads agree on order, circular wait becomes impossible'),
  topicItem('What a thread dump is — a snapshot of every thread\'s state and what lock it holds or waits for'),
  topicItem('How to read a thread dump — find threads in BLOCKED state, find what they are waiting on, trace the cycle'),
  topicItem('How to take a thread dump — kill -3 <pid> on Linux, or in IntelliJ: Run > Dump Threads'),
  note('Reading a thread dump is a real production skill. You will use this when a service hangs at 2am.'),
  spacer(),
  topicGroupLabel('Docker — what you must understand:'),
  topicItem('What problem Docker solves — "works on my machine". Docker packages app + all dependencies into a container.'),
  topicItem('What an image is — a read-only template. What a container is — a running instance of an image.'),
  topicItem('What a Dockerfile is — instructions to build an image layer by layer'),
  topicItem('What docker-compose is — defines and runs multiple containers together (app + MySQL + Redis)'),
  topicItem('Why volumes exist in docker-compose — MySQL data persists across container restarts'),
  topicItem('Essential commands: docker ps, docker logs, docker exec, docker-compose up -d, docker-compose stop'),
  spacer(),

  // DAY 19
  dayHeading('DAY 19 — ThreadPoolExecutor Deep + HTTP Fundamentals'),
  topicGroupLabel('ThreadPoolExecutor — what you must understand:'),
  topicItem('Why Executors factory methods hide important details — you cannot tune what you cannot see'),
  topicItem('corePoolSize — threads always alive even when idle'),
  topicItem('maximumPoolSize — maximum threads ever created'),
  topicItem('Queue — tasks wait here when all core threads are busy. ALWAYS use bounded queue. Unbounded queue = OOM risk.'),
  topicItem('RejectionPolicy — what happens when queue is full AND all threads are busy:'),
  subItem('CallerRunsPolicy — calling thread executes the task. Slows producer. Never drops tasks. Best for payments.'),
  subItem('AbortPolicy — throws RejectedExecutionException. Default. Drops the task.'),
  subItem('DiscardPolicy — silently drops. Never use for financial data.'),
  subItem('DiscardOldestPolicy — drops oldest queued task. Never use for financial data.'),
  topicItem('Pool sizing formula — connections = (core_count × 2) + 1 for IO-bound tasks'),
  spacer(),
  topicGroupLabel('HTTP fundamentals — what you must understand:'),
  topicItem('Full path of an HTTP request — DNS lookup → TCP handshake → TLS handshake (HTTPS) → HTTP request → server processes → response'),
  topicItem('What a TCP handshake is — 3-way handshake (SYN, SYN-ACK, ACK) before any data is sent'),
  topicItem('What a TLS handshake is — negotiating encryption keys before any HTTP data is sent. Expensive.'),
  topicItem('Why connection pooling exists — creating TCP+TLS connection for every request is too expensive. Reuse them.'),
  topicItem('How HTTP keep-alive works — connection stays open after response, reused for next request'),
  topicItem('Why HikariCP for DB and HttpClient pool for HTTP serve the same purpose — both avoid expensive connection creation per request'),
  note('curl -v shows you every step of the HTTP conversation. Run it on httpbin.org/get and read every line.'),
  spacer(),

  // DAY 20
  dayHeading('DAY 20 — Week 3 Integration + Debugging'),
  topicGroupLabel('What to understand before the integration day:'),
  topicItem('How all Week 3 pieces connect — ExecutorService manages threads, CompletableFuture chains async steps, BalanceManager uses CAS, batch processor ties them together'),
  topicItem('What a conditional breakpoint is — breakpoint that only fires when a condition is true (e.g. balance < 0)'),
  topicItem('Why conditional breakpoints are essential for concurrency debugging — you cannot step through 100 concurrent threads'),
  topicItem('How to use IntelliJ debugger for concurrency — set conditional breakpoint, run the concurrent test, wait for the bug to surface'),
  spacer(),

  // DAY 21
  dayHeading('DAY 21 — Week 3 Checkpoint'),
  topicGroupLabel('Questions you must answer from memory, no notes:'),
  topicItem('What is a race condition? Show one in code and fix it three ways.'),
  topicItem('Why is volatile not enough for count++?'),
  topicItem('What is a deadlock? How do you prevent it in a money transfer?'),
  topicItem('What is thenCompose vs thenCombine? When do you use each?'),
  topicItem('What happens when all threads are busy and the queue is full?'),
  topicItem('You need to process 1000 payment requests per second. Walk me through your approach.'),
  topicItem('How do you read a thread dump and identify a deadlock?'),
  note('If you cannot answer these confidently, do not move to Week 4.'),
  spacer(),

  pageBreak(),

  // ══════════════════════════════════════
  // WEEK 4
  // ══════════════════════════════════════
  weekHeading('WEEK 4 — Spring Boot Internals + JWT + AOP'),

  // DAY 22
  dayHeading('DAY 22 — Spring Boot Internals: @SpringBootApplication + Auto-Configuration'),
  topicGroupLabel('@SpringBootApplication — what you must understand:'),
  topicItem('What @SpringBootApplication expands to — exactly 3 annotations: @SpringBootConfiguration + @EnableAutoConfiguration + @ComponentScan'),
  topicItem('What @SpringBootConfiguration does — marks the class as a configuration source'),
  topicItem('What @ComponentScan does — scans the current package and all subpackages for Spring components'),
  topicItem('What @EnableAutoConfiguration does — triggers the auto-configuration mechanism'),
  spacer(),
  topicGroupLabel('SpringApplication.run() — step by step:'),
  topicItem('Step 1 — determines app type: SERVLET (web), REACTIVE, or NONE'),
  topicItem('Step 2 — loads SpringApplicationRunListeners'),
  topicItem('Step 3 — prepares Environment: reads application.yml, env variables, CLI args'),
  topicItem('Step 4 — creates ApplicationContext'),
  topicItem('Step 5 — refreshes context: processes @Configuration, runs auto-configuration, creates all beans, starts embedded Tomcat'),
  topicItem('Step 6 — calls ApplicationRunner and CommandLineRunner beans'),
  spacer(),
  topicGroupLabel('Auto-configuration — what you must understand:'),
  topicItem('What the auto-configuration imports file is — META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports lists ~150 classes'),
  topicItem('What @ConditionalOnClass does — auto-configuration only fires if a specific class is on the classpath'),
  topicItem('What @ConditionalOnMissingBean does — auto-configuration only fires if you have NOT defined your own bean'),
  topicItem('The full DataSource creation chain — add JPA starter → Hibernate on classpath → @ConditionalOnClass fires → DataSource created from application.yml'),
  topicItem('Why this matters — it demystifies the "magic". There is no magic. It is conditional class checking.'),
  note('Failure simulation: remove spring-boot-starter-web. App starts and immediately exits — no web server, no reason to stay alive.'),
  spacer(),

  // DAY 23
  dayHeading('DAY 23 — Bean Lifecycle + BeanPostProcessor'),
  topicGroupLabel('Bean lifecycle — memorise all 10 steps in order:'),
  topicItem('1. Constructor called — object created, no dependencies injected yet'),
  topicItem('2. @Autowired dependencies injected — field or setter injection happens here'),
  topicItem('3. Aware callbacks — BeanNameAware, ApplicationContextAware, etc.'),
  topicItem('4. BeanPostProcessor.postProcessBeforeInitialization() — runs before @PostConstruct'),
  topicItem('5. @PostConstruct method called — safe to use injected dependencies here'),
  topicItem('6. InitializingBean.afterPropertiesSet() — alternative to @PostConstruct'),
  topicItem('7. BeanPostProcessor.postProcessAfterInitialization() — THIS IS WHERE AOP PROXIES ARE CREATED'),
  topicItem('8. Bean is READY — starts handling requests'),
  topicItem('9. @PreDestroy on shutdown — clean up resources'),
  topicItem('10. DisposableBean.destroy() — alternative to @PreDestroy'),
  spacer(),
  topicGroupLabel('BeanPostProcessor — what you must understand:'),
  topicItem('What BeanPostProcessor is — an interface that runs code before and after every bean is initialized'),
  topicItem('Why step 7 is critical — AOP proxies are created here. Before step 7, the bean has no AOP. After step 7, it does.'),
  topicItem('How Spring uses BeanPostProcessor — @Transactional, @Async, and all AOP annotations are applied via BeanPostProcessor'),
  topicItem('Why you cannot use @Autowired dependencies in the constructor — they are not injected yet at step 1'),
  topicItem('Why @PostConstruct is the right place to use injected dependencies — injection is complete at step 5'),
  note('Critical: AOP proxies are created at step 7. This is why @Transactional only works on public methods called through the proxy.'),
  spacer(),

  // DAY 24
  dayHeading('DAY 24 — @Transactional Deeply: 3 Silent Failure Modes'),
  topicGroupLabel('How @Transactional works — the proxy model:'),
  topicItem('Spring wraps @Transactional beans with a proxy at step 7 of bean lifecycle'),
  topicItem('The proxy begins a transaction before your method, commits or rolls back after'),
  topicItem('Calling your method directly bypasses the proxy — no transaction'),
  spacer(),
  topicGroupLabel('Failure Mode 1 — Self-invocation (proxy bypass):'),
  topicItem('What happens — you call a @Transactional method from another method in the SAME class using "this"'),
  topicItem('Why it fails — "this" refers to the real object, not the proxy. The proxy is never involved. No transaction starts.'),
  topicItem('How to fix — inject the bean into itself via @Autowired, or move the method to a separate service class'),
  spacer(),
  topicGroupLabel('Failure Mode 2 — Checked exceptions do not trigger rollback:'),
  topicItem('Default behaviour — @Transactional only rolls back on RuntimeException and Error, not checked exceptions'),
  topicItem('Why — Java checked exceptions are considered "expected" failures. This was a design decision.'),
  topicItem('The danger — debit succeeds, checked exception thrown, no rollback. Account debited but payment not saved.'),
  topicItem('How to fix — @Transactional(rollbackFor = Exception.class)'),
  spacer(),
  topicGroupLabel('Failure Mode 3 — Private methods are silently ignored:'),
  topicItem('Why — the proxy cannot override private methods. @Transactional on a private method is completely ignored.'),
  topicItem('No error, no warning — it simply has no effect. This is the most dangerous failure mode.'),
  topicItem('Rule — always apply @Transactional to public methods only'),
  spacer(),
  topicGroupLabel('Propagation levels — the two you must know:'),
  topicItem('REQUIRED (default) — join existing transaction or create new one. 95% of cases.'),
  topicItem('REQUIRES_NEW — always create new transaction, suspend existing. Use for audit logs that must persist even if outer transaction rolls back.'),
  note('This is a high-frequency fintech interview topic. Know all 3 failure modes with fixes.'),
  spacer(),

  // DAY 25
  dayHeading('DAY 25 — Spring Security + JWT Filter + MDC Request ID Filter'),
  topicGroupLabel('Spring Security filter chain — what you must understand:'),
  topicItem('What the filter chain is — a sequence of filters that every HTTP request passes through before reaching your controller'),
  topicItem('Why OncePerRequestFilter — guarantees the filter runs exactly once per request, not once per dispatch'),
  topicItem('What SecurityContextHolder is — thread-local storage for the current authentication object'),
  topicItem('Why SecurityContextHolder is thread-local — each request thread has its own security context'),
  spacer(),
  topicGroupLabel('JWT — what you must understand:'),
  topicItem('What JWT is — a signed token encoding user identity and claims. No server-side session storage needed.'),
  topicItem('Three parts of a JWT — header (algorithm), payload (claims), signature'),
  topicItem('What the signature proves — the token was issued by your server and has not been tampered with'),
  topicItem('What the filter does — extracts JWT from Authorization header, validates signature, sets authentication in SecurityContextHolder'),
  topicItem('Why the token is validated on every request — stateless auth. Server trusts the signature, not a session.'),
  spacer(),
  topicGroupLabel('MDC — what you must understand:'),
  topicItem('What MDC is — Mapped Diagnostic Context. Thread-local key-value store that gets included in every log line.'),
  topicItem('Why requestId is stored in MDC — every log line for a request automatically includes the request ID'),
  topicItem('Why MDC.clear() must be in finally block — without it, requestId leaks into the next request handled by the same thread'),
  topicItem('The MDC leak bug — request 2 shows request 1\'s ID in logs. A real production bug pattern.'),
  note('MDC.clear() in finally is a production discipline. Skipping it causes incorrect log correlation in production.'),
  spacer(),

  // DAY 26
  dayHeading('DAY 26 — AOP + GlobalExceptionHandler'),
  topicGroupLabel('AOP — what you must understand:'),
  topicItem('What AOP is — Aspect Oriented Programming. Applies cross-cutting behaviour to multiple methods without modifying them.'),
  topicItem('What "cross-cutting concern" means — logging, timing, security, transactions — things that apply across many methods'),
  topicItem('What an Aspect is — the class containing the cross-cutting logic'),
  topicItem('What a Pointcut is — the expression that defines WHICH methods the aspect applies to'),
  topicItem('What @Around does — wraps the target method. You control what happens before, after, and on exception.'),
  topicItem('What ProceedingJoinPoint.proceed() does — calls the actual target method. Without this call, the method never executes.'),
  topicItem('What @Before and @After do — simpler than @Around. @Before runs before the method, @After runs after (always).'),
  topicItem('How Spring implements AOP — via BeanPostProcessor at step 7 of bean lifecycle, creating a proxy that intercepts calls'),
  spacer(),
  topicGroupLabel('GlobalExceptionHandler — what you must understand:'),
  topicItem('What @RestControllerAdvice does — intercepts exceptions thrown by any controller and converts them to responses'),
  topicItem('What RFC 7807 is — standard format for HTTP error responses. Fields: type, title, status, detail, instance.'),
  topicItem('Why a standard error format matters — clients can parse errors consistently. No guessing the error shape.'),
  topicItem('What ProblemDetail is — Spring\'s built-in RFC 7807 implementation available since Spring 6'),
  topicItem('Why including requestId in error responses matters — client can send it back so you can trace the exact request in logs'),
  spacer(),

  // DAY 27
  dayHeading('DAY 27 — REST API Design + PaymentController'),
  topicGroupLabel('REST API design principles — what you must understand:'),
  topicItem('Resource naming — nouns not verbs. POST /payments not POST /createPayment.'),
  topicItem('HTTP method semantics — GET (read), POST (create), PUT (replace), PATCH (partial update), DELETE (remove)'),
  topicItem('HTTP status codes to know cold:'),
  subItem('201 Created — POST success. Always include Location header with URL of new resource.'),
  subItem('200 OK — GET, PUT, PATCH success'),
  subItem('204 No Content — DELETE success'),
  subItem('400 Bad Request — validation failed (wrong format)'),
  subItem('401 Unauthorized — missing or invalid token'),
  subItem('403 Forbidden — authenticated but not authorised for this resource'),
  subItem('422 Unprocessable Entity — valid format but business rule violated (e.g. insufficient balance)'),
  subItem('429 Too Many Requests — rate limited'),
  topicItem('What idempotency means for a payment API — the same request sent twice must not create two payments'),
  topicItem('How the Idempotency-Key header works — client generates a UUID, sends it on every payment request, server deduplicates'),
  topicItem('What API versioning solves — breaking changes in v2 never affect clients on v1'),
  note('The difference between 400 and 422 matters in fintech. 400 = wrong format. 422 = valid format, business rule broken.'),
  spacer(),

  // DAY 28
  dayHeading('DAY 28 — Week 4 Checkpoint'),
  topicGroupLabel('Questions you must answer from memory, no notes:'),
  topicItem('What does @SpringBootApplication expand to and what does each part do?'),
  topicItem('Walk me through what SpringApplication.run() does step by step'),
  topicItem('How does auto-configuration decide to create a DataSource?'),
  topicItem('List all 10 bean lifecycle steps in order'),
  topicItem('I called a @Transactional method from within the same class. Will it roll back? Why?'),
  topicItem('What is BeanPostProcessor and what does Spring use it for?'),
  topicItem('Why must MDC.clear() be in a finally block?'),
  topicItem('What does @Around do and what happens if you forget to call proceed()?'),
  topicItem('What is the difference between 401 and 403?'),
  note('If you cannot answer confidently, stay on Week 4 topics for 2 more days before moving on.'),
  spacer(),

  pageBreak(),

  // ══════════════════════════════════════
  // WEEK 5
  // ══════════════════════════════════════
  weekHeading('WEEK 5 — JPA + SQL Depth + Indexes + Schema Patterns'),

  // DAY 29
  dayHeading('DAY 29 — JPA Entities + Hibernate Internals'),
  topicGroupLabel('N+1 problem — what you must understand:'),
  topicItem('What N+1 is — 1 query to fetch N entities, then N more queries to fetch their associations. Total: N+1 queries.'),
  topicItem('Why it is dangerous — fetching 1000 accounts triggers 1001 queries. Your app becomes slow and hammers the database.'),
  topicItem('What lazy loading is — associations are not loaded until accessed. Default for @OneToMany.'),
  topicItem('What eager loading is — associations are loaded immediately with the parent. @ManyToOne default.'),
  topicItem('How to fix N+1 — JOIN FETCH in JPQL, or @EntityGraph on the repository method'),
  spacer(),
  topicGroupLabel('Optimistic locking with @Version — what you must understand:'),
  topicItem('What optimistic locking assumes — conflicts are rare. Read freely, check before writing.'),
  topicItem('What the @Version field does — JPA increments it on every update. If version does not match at write time, throw OptimisticLockException.'),
  topicItem('The lost update scenario without @Version — Thread 1 reads version=5, Thread 2 reads version=5, Thread 1 writes (version=6), Thread 2 writes based on stale version=5. Thread 2 overwrites Thread 1\'s change.'),
  topicItem('With @Version — Thread 2\'s update fails because version=5 no longer exists (it is now 6). Thread 2 must retry.'),
  topicItem('Why optimistic locking is preferred over pessimistic for payment systems — better throughput, no deadlocks'),
  spacer(),
  topicGroupLabel('LazyInitializationException — what you must understand:'),
  topicItem('What causes it — accessing a lazy association AFTER the Hibernate session has closed'),
  topicItem('Why the session closes — @Transactional opens a session for the duration of the method. When method exits, session closes.'),
  topicItem('Why accessing the lazy field outside the transaction fails — no open session to execute the query'),
  topicItem('Fix 1 — add @Transactional to the service method to keep session open'),
  topicItem('Fix 2 — use JOIN FETCH in the repository query to load association eagerly in one query'),
  spacer(),

  // DAY 30
  dayHeading('DAY 30 — B-Tree Indexes + EXPLAIN Output'),
  topicGroupLabel('How B-Tree indexes work — what you must understand:'),
  topicItem('Without index — finding a row by email in 1 million rows scans all 1 million. O(n).'),
  topicItem('With B-Tree index — 3-4 disk reads maximum regardless of table size. O(log n).'),
  topicItem('What a B-Tree physically is — a balanced tree of sorted keys. Leaf nodes point to row data (or primary key for secondary indexes).'),
  topicItem('Clustered vs non-clustered in InnoDB:'),
  subItem('Primary key = clustered index. Row data IS the leaf node. The table IS the B-Tree.'),
  subItem('Secondary index leaf holds (indexed value, primary key). Finding the row requires two lookups.'),
  topicItem('What a covering index is — index includes all columns the query needs. Eliminates the second lookup entirely.'),
  spacer(),
  topicGroupLabel('Composite index rules — what you must understand:'),
  topicItem('Leftmost prefix rule — index (user_id, status, created_at) can be used by queries filtering on user_id alone, or user_id+status, or all three. Not status alone.'),
  topicItem('Why leftmost prefix — B-Tree is sorted by the first column first. Skipping it means the tree is not navigable.'),
  topicItem('Equality columns first, range columns last — (user_id, status) for equality, then (created_at) for range at the end'),
  topicItem('Why a function on a column destroys index usage — WHERE YEAR(created_at) = 2024 cannot use the index on created_at'),
  spacer(),
  topicGroupLabel('EXPLAIN output — what you must understand:'),
  topicItem('type=ALL — full table scan. Every row read. The worst case.'),
  topicItem('type=ref — index used. Only matching rows read. Good.'),
  topicItem('type=const — primary key or unique key lookup. Single row found. Best case.'),
  topicItem('key column — which index was used. NULL means no index used.'),
  topicItem('rows column — estimated number of rows examined. High number = slow query.'),
  topicItem('Extra column — "Using filesort" means no index for ORDER BY. "Using index" means covering index used.'),
  note('In interviews: "I added an index on status and query time went from 800ms to 12ms on 100k rows." Real numbers impress.'),
  spacer(),

  // DAY 31
  dayHeading('DAY 31 — ACID + Isolation Levels + Locking'),
  topicGroupLabel('ACID — how MySQL actually implements each property:'),
  topicItem('Atomicity — UNDO LOG. Before any change, old value is written here. Rollback = apply undo log in reverse.'),
  topicItem('Consistency — constraints (NOT NULL, UNIQUE, FK) + application-level rules enforced together'),
  topicItem('Isolation — configurable via isolation level (see below)'),
  topicItem('Durability — REDO LOG (Write-Ahead Log). Committed data written to redo log before returning to client. Survives crashes.'),
  spacer(),
  topicGroupLabel('All 4 isolation levels — what each prevents:'),
  topicItem('READ UNCOMMITTED — sees other transactions\' uncommitted data (dirty reads). Never use in production.'),
  topicItem('READ COMMITTED — no dirty reads. You only see committed data. PostgreSQL default.'),
  topicItem('REPEATABLE READ — no dirty reads, no non-repeatable reads. Same row read twice returns same value. MySQL InnoDB default.'),
  topicItem('SERIALIZABLE — full isolation. Transactions run as if sequential. Slowest. Use only for critical uniqueness (promo codes).'),
  spacer(),
  topicGroupLabel('Locking — what you must understand:'),
  topicItem('FOR SHARE — read lock. Blocks writers, allows other readers. Use when reading data that must not change until your read is done.'),
  topicItem('FOR UPDATE — exclusive lock. Blocks everyone including readers. Use when you will update based on the read.'),
  topicItem('Why FOR UPDATE is critical before a balance update — without it, another transaction can change the balance between your read and write'),
  topicItem('Optimistic locking (@Version) vs pessimistic locking (FOR UPDATE) — optimistic is faster under low contention, pessimistic is safer under high contention'),
  spacer(),

  // DAY 32
  dayHeading('DAY 32 — Fintech Schema Patterns'),
  topicGroupLabel('4 patterns you must understand deeply — these are in your production schema:'),
  spacer(),
  topicGroupLabel('Pattern 1 — Idempotency at DB level:'),
  topicItem('What it solves — if the client retries a payment request, the DB silently ignores the duplicate instead of creating two payments'),
  topicItem('How it works — UNIQUE constraint on idempotency_key column'),
  topicItem('ON DUPLICATE KEY UPDATE id=id — on duplicate, do nothing. No error, no new row.'),
  topicItem('Why this is necessary in addition to Redis idempotency — defense in depth. Redis can fail. DB constraint always holds.'),
  spacer(),
  topicGroupLabel('Pattern 2 — Optimistic locking with version column:'),
  topicItem('What it solves — concurrent updates to the same balance without using row locks'),
  topicItem('How it works — WHERE id=1 AND version=5. If 0 rows affected, someone else updated it. Fetch fresh data and retry.'),
  topicItem('Why version is in the WHERE clause, not just the SET clause'),
  spacer(),
  topicGroupLabel('Pattern 3 — Soft delete:'),
  topicItem('What it solves — financial records must never be permanently deleted. Regulatory requirement.'),
  topicItem('How it works — deleted_at TIMESTAMP NULL column. Delete = SET deleted_at=NOW(). All queries add WHERE deleted_at IS NULL.'),
  topicItem('Why hard DELETE is never used in financial systems'),
  spacer(),
  topicGroupLabel('Pattern 4 — Cursor-based pagination:'),
  topicItem('What OFFSET does — scans all preceding rows on every page. Page 1000 scans 20,000 rows to return 20. O(n) per page.'),
  topicItem('What cursor-based does — WHERE id < lastSeenId ORDER BY id DESC LIMIT 20. Always O(log n) via primary key index.'),
  topicItem('Why cursor pagination scales — page 1 and page 100,000 take the same time'),
  topicItem('The tradeoff — cursor pagination cannot jump to arbitrary pages. Use for infinite scroll, not page numbers.'),
  note('All 4 patterns appear in your production schema. Know why each one exists, not just what it does.'),
  spacer(),

  // DAY 33
  dayHeading('DAY 33 — HikariCP + System Design Framework'),
  topicGroupLabel('HikariCP — what you must understand:'),
  topicItem('What a connection pool is — pre-created database connections reused across requests'),
  topicItem('Why creating a new DB connection per request is too expensive — TCP handshake + auth + memory allocation on every request'),
  topicItem('minimum-idle — connections kept alive even when idle'),
  topicItem('maximum-pool-size — maximum connections ever open. More is NOT always better.'),
  topicItem('connection-timeout — how long to wait for a connection from the pool before throwing an exception'),
  topicItem('Pool sizing formula — (core_count × 2) + 1 for IO-bound workloads'),
  topicItem('What connection pool exhaustion looks like — all connections in use, new requests timeout. Real production outage pattern.'),
  spacer(),
  topicGroupLabel('System Design 7-step framework — what you must understand:'),
  topicItem('Step 1 — Clarify requirements (5 min): who uses it, what scale, latency budget, consistency needs'),
  topicItem('Step 2 — Estimate scale (5 min): req/sec, storage/year, peak multiplier, bandwidth'),
  topicItem('Step 3 — High-level design (10 min): draw the boxes — LB, app servers, DB, cache'),
  topicItem('Step 4 — API design (5 min): main endpoints, request/response shape'),
  topicItem('Step 5 — Data model (5 min): key tables or data structures'),
  topicItem('Step 6 — Deep dive (20 min): interviewer steers this. Go deep on the hardest part.'),
  topicItem('Step 7 — Bottlenecks (5 min): what breaks at 10x load and how to fix it'),
  note('Never jump to solutions before clarifying requirements. Interviewers mark you down for it.'),
  spacer(),

  // DAY 34-35
  dayHeading('DAY 34 — Week 5 Integration + EXPLAIN on Real Data'),
  topicGroupLabel('What to understand before this day:'),
  topicItem('How to insert bulk data efficiently — stored procedure with a loop. One transaction for 100k rows.'),
  topicItem('What SQL_NO_CACHE does — bypasses query cache so you measure real disk performance'),
  topicItem('Why recording before/after performance numbers matters — "index improved query from 800ms to 12ms" is an interview answer'),
  topicItem('How OptimisticLockException surfaces in a concurrent test — two threads update same row, one gets the exception'),
  spacer(),
  dayHeading('DAY 35 — Week 5 Checkpoint'),
  topicGroupLabel('Questions you must answer from memory, no notes:'),
  topicItem('B-Tree index — how does MySQL physically find a row by email?'),
  topicItem('EXPLAIN type=ALL — what does it mean and how do you fix it?'),
  topicItem('What is a covering index and when would you create one?'),
  topicItem('All 4 isolation levels and what each prevents'),
  topicItem('Cursor pagination vs OFFSET — why is OFFSET dangerous?'),
  topicItem('Explain optimistic vs pessimistic locking — when to use each'),
  note('If you cannot answer confidently, do not move to Week 6.'),
  spacer(),

  pageBreak(),

  // ══════════════════════════════════════
  // WEEK 6
  // ══════════════════════════════════════
  weekHeading('WEEK 6 — Redis Caching + Idempotency + Rate Limiting'),

  // DAY 36
  dayHeading('DAY 36 — Redis Caching: Cache-Aside Pattern'),
  topicGroupLabel('Redis — what you must understand before using it:'),
  topicItem('What Redis is — in-memory key-value store. Reads are microseconds. DB reads are milliseconds.'),
  topicItem('Why Redis is not a database — data is in memory. By default, restart = data loss. Use for data you can rebuild from DB.'),
  topicItem('What TTL (time-to-live) is — key expires automatically after N seconds. Prevents stale data from living forever.'),
  spacer(),
  topicGroupLabel('Cache-aside pattern — what you must understand:'),
  topicItem('How it works — check cache first. If miss, load from DB and store in cache. If hit, return from cache.'),
  topicItem('Why it is called "cache-aside" — the application manages the cache explicitly, not automatically'),
  topicItem('Cache invalidation on writes — when you update the DB, delete the cached value. Do not update it.'),
  topicItem('Why delete not update — updating a cached value correctly under concurrency is complex. Delete forces the next read to reload from DB.'),
  topicItem('The cache inconsistency bug — updating DB without deleting cache. Reads return stale data forever.'),
  topicItem('Why TTL alone is not enough — TTL-only means stale data for up to TTL seconds after every write. Bad for balance data.'),
  note('The cache inconsistency bug is the most common Redis mistake in production. Always delete on write.'),
  spacer(),

  // DAY 37
  dayHeading('DAY 37 — Idempotency Service + Rate Limiting with Lua'),
  topicGroupLabel('Idempotency service — what you must understand:'),
  topicItem('What idempotency means — the same operation performed multiple times has the same effect as performing it once'),
  topicItem('Why payments must be idempotent — network timeouts cause clients to retry. Without idempotency, one payment becomes two.'),
  topicItem('How Redis-backed idempotency works — store idempotency_key → response for 24 hours. On duplicate, return stored response.'),
  topicItem('Why 24 hours TTL — covers retry windows. After 24 hours, the key is safe to reuse.'),
  spacer(),
  topicGroupLabel('Rate limiting with Lua scripts — what you must understand:'),
  topicItem('What rate limiting is — restricting how many requests a user can make in a time window'),
  topicItem('The race condition without Lua — INCR key then EXPIRE key are two separate Redis calls. Between them, another thread can INCR and never get EXPIRE set. Key never expires.'),
  topicItem('What Lua scripts do in Redis — execute multiple Redis commands atomically in a single round trip'),
  topicItem('Why "atomic" matters here — INCR and EXPIRE are guaranteed to run together with no other commands in between'),
  topicItem('The sliding window counter algorithm — INCR on each request, EXPIRE on first request, check against MAX'),
  note('The race condition between INCR and EXPIRE without Lua is a common production bug. This is exactly why Lua exists.'),
  spacer(),

  // DAY 38
  dayHeading('DAY 38 — API Consumption: WebClient + Retry + Timeout'),
  topicGroupLabel('Why outbound HTTP calls need special handling:'),
  topicItem('External services fail — fraud check API, bank verification, SMS gateway can be down'),
  topicItem('External services are slow — a 10-second response from a fraud API blocks your thread for 10 seconds'),
  topicItem('Without timeouts — one slow external call holds a thread forever. Thread pool exhaustion follows.'),
  spacer(),
  topicGroupLabel('WebClient — what you must understand:'),
  topicItem('What WebClient is — Spring\'s non-blocking HTTP client. Replaces RestTemplate for new code.'),
  topicItem('responseTimeout — maximum time to wait for a response. After this, throw WebClientRequestException.'),
  topicItem('CONNECT_TIMEOUT — maximum time to wait for TCP connection. Set separately from response timeout.'),
  spacer(),
  topicGroupLabel('Retry with backoff — what you must understand:'),
  topicItem('What exponential backoff is — first retry after 200ms, second after 400ms, third after 800ms. Avoids hammering a struggling service.'),
  topicItem('What jitter is — random offset added to backoff to prevent all retries hitting at the same moment'),
  topicItem('What to retry and what not to retry:'),
  subItem('Retry — network errors (WebClientRequestException), 503 Service Unavailable'),
  subItem('Do NOT retry — 400 Bad Request (your fault), 422 business error (not a transient failure)'),
  topicItem('What onErrorReturn does — after all retries fail, return a safe fallback value instead of propagating the error'),
  spacer(),

  // DAY 39
  dayHeading('DAY 39 — Bean Validation + API Versioning + Graceful Shutdown'),
  topicGroupLabel('Bean Validation — what you must understand:'),
  topicItem('What Bean Validation is — JSR-380 standard. Annotations on DTO fields that auto-validate before the controller method runs.'),
  topicItem('Common annotations: @NotNull, @NotBlank, @Positive, @DecimalMax, @Pattern'),
  topicItem('What @Valid on the @RequestBody parameter does — triggers validation before the method is entered'),
  topicItem('What happens on validation failure — MethodArgumentNotValidException thrown, caught by GlobalExceptionHandler, returns 400'),
  spacer(),
  topicGroupLabel('API versioning — what you must understand:'),
  topicItem('Why versioning exists — breaking changes in the API must not break existing clients'),
  topicItem('URL versioning (/api/v1/, /api/v2/) — most common, most visible, easiest to route'),
  topicItem('The rule — never modify v1 in place. Add v2 alongside it. Clients on v1 continue working.'),
  spacer(),
  topicGroupLabel('Graceful shutdown — what you must understand:'),
  topicItem('What graceful shutdown means — stop accepting new requests, but finish in-flight requests before exiting'),
  topicItem('Why it matters for payments — without it, a deployment kills active payment transactions mid-flight. Money in unknown state.'),
  topicItem('What SIGTERM is — the signal Kubernetes and Docker send to stop a container. JVM receives it and starts graceful shutdown.'),
  topicItem('What server.shutdown=graceful does in Spring Boot — enables graceful shutdown. In-flight requests have up to timeout-per-shutdown-phase to complete.'),
  spacer(),

  // DAY 40
  dayHeading('DAY 40 — System Design: URL Shortener + Notification System'),
  topicGroupLabel('URL Shortener — topics to study before designing:'),
  topicItem('How Base62 encoding works — converts a number to a short alphanumeric string'),
  topicItem('Why 302 redirect is used instead of 301 — 302 hits server every time (trackable). 301 browser caches (untrackable).'),
  topicItem('Role of CDN in caching popular short URLs — popular URLs cached at edge, never hits your server'),
  topicItem('Why read replicas help — read:write ratio is 100:1. Reads can be distributed across replicas.'),
  spacer(),
  topicGroupLabel('Notification System — topics to study before designing:'),
  topicItem('Why Kafka decouples the notification sender from delivery channels'),
  topicItem('What a DLQ (Dead Letter Queue) is — failed messages go here for manual inspection, not silently dropped'),
  topicItem('Why different priority topics exist — OTP must deliver in <1 second. Marketing can wait minutes.'),
  topicItem('What each delivery channel requires — email (SendGrid), SMS (Twilio), push (FCM/APNs)'),
  spacer(),

  // DAY 41
  dayHeading('DAY 41 — Week 6 Integration: Full Payment Flow with Redis'),
  topicGroupLabel('What to understand before integration day:'),
  topicItem('The full payment flow order: idempotency check → rate limit check → async fraud check → balance debit → wait for fraud result → save payment → cache update → publish event'),
  topicItem('Why fraud check runs in parallel with balance debit — they are independent. Running sequentially wastes time.'),
  topicItem('Why idempotency is checked first — if it is a duplicate, skip all processing immediately'),
  topicItem('What happens when fraud check returns FLAGGED after debit — debit must be reversed. Order of operations matters.'),
  spacer(),

  pageBreak(),

  // ══════════════════════════════════════
  // WEEK 7
  // ══════════════════════════════════════
  weekHeading('WEEK 7 — Testcontainers + Observability + Project Polish'),

  // DAY 42
  dayHeading('DAY 42 — Testcontainers: Integration Tests Against Real MySQL and Redis'),
  topicGroupLabel('Why Testcontainers — what you must understand:'),
  topicItem('What Testcontainers is — starts real Docker containers (MySQL, Redis) during your test run, tears them down after'),
  topicItem('Why unit tests with mocks are not enough — mocks do not catch SQL syntax errors, index missing, transaction isolation issues'),
  topicItem('What integration tests catch that unit tests cannot — real query performance, real constraint violations, real Redis behaviour'),
  topicItem('Why an in-memory H2 database is not enough — H2 SQL dialect differs from MySQL. Queries that work in H2 fail in MySQL.'),
  spacer(),
  topicGroupLabel('How Testcontainers works — what you must understand:'),
  topicItem('@Testcontainers annotation — activates Testcontainers lifecycle management'),
  topicItem('@Container annotation — declares a container to start before tests and stop after'),
  topicItem('MySQLContainer — starts real MySQL 8.0. Has JDBC URL, username, password auto-configured.'),
  topicItem('@DynamicPropertySource — injects the container\'s dynamic connection details into Spring\'s application context'),
  topicItem('Why @DynamicPropertySource is needed — the container port is randomly assigned. You cannot hardcode it.'),
  spacer(),

  // DAY 43
  dayHeading('DAY 43 — Structured Logging: SLF4J + Logback'),
  topicGroupLabel('Why logging matters in production — what you must understand:'),
  topicItem('In production, you debug with logs. There is no debugger attached.'),
  topicItem('An engineer who cannot instrument their code properly cannot debug production issues independently.'),
  spacer(),
  topicGroupLabel('SLF4J — what you must understand:'),
  topicItem('What SLF4J is — a logging facade (interface), not an implementation. Your code depends on the interface, not the logger.'),
  topicItem('What Logback is — the implementation behind SLF4J in Spring Boot. You can swap it for Log4j2 without changing code.'),
  topicItem('How to declare a logger — private static final Logger log = LoggerFactory.getLogger(ClassName.class)'),
  topicItem('Why static and final — one logger per class, shared across all instances, never changes'),
  spacer(),
  topicGroupLabel('Log levels — when to use each:'),
  topicItem('DEBUG — detailed diagnostic info. Disabled in production. Use for tracing code paths during development.'),
  topicItem('INFO — significant events. Payment processed, user registered, service started. Normal production noise.'),
  topicItem('WARN — something unexpected but recoverable. Retry attempt, cache miss rate high, approaching rate limit.'),
  topicItem('ERROR — something failed that needs attention. Exception caught, payment failed, external service down.'),
  spacer(),
  topicGroupLabel('What to NEVER log — what you must understand:'),
  topicItem('Card numbers — even last 4 digits need care. Full card number: never.'),
  topicItem('Passwords — never log passwords in any form, not even hashed'),
  topicItem('OTPs — one-time passwords must never appear in logs'),
  topicItem('Full JWT tokens — can be replayed'),
  topicItem('Personal data (Aadhaar, PAN) — regulatory violation'),
  note('Logging PII or card data in a fintech system is a regulatory violation. This is not a guideline, it is a legal requirement.'),
  spacer(),

  // DAY 44
  dayHeading('DAY 44 — Actuator + Health Checks + Application Metrics'),
  topicGroupLabel('Spring Boot Actuator — what you must understand:'),
  topicItem('What Actuator is — built-in production monitoring endpoints exposed by Spring Boot'),
  topicItem('/actuator/health — returns UP or DOWN. Used by load balancers and Kubernetes liveness probes.'),
  topicItem('/actuator/info — application version, build time, git commit info'),
  topicItem('/actuator/metrics — application metrics: request count, response time, JVM memory, thread pool stats'),
  topicItem('Why health endpoints matter — Kubernetes uses /health to decide whether to route traffic to a pod'),
  spacer(),
  topicGroupLabel('Health checks — what you must understand:'),
  topicItem('What a liveness probe is — is the app alive? If not, Kubernetes restarts it.'),
  topicItem('What a readiness probe is — is the app ready to serve traffic? If not, Kubernetes stops routing to it.'),
  topicItem('Why the two are different — an app can be alive (process running) but not ready (DB connection not established yet)'),
  topicItem('Custom health indicator — how to add your own health check (e.g. check Redis is reachable)'),
  spacer(),

  // DAY 45
  dayHeading('DAY 45 — README: Architecture Diagram + Design Decisions'),
  topicGroupLabel('What makes a professional README — what you must understand:'),
  topicItem('What the README communicates — a hiring manager should understand what the project does and run it in under 5 minutes'),
  topicItem('What to include: project description, architecture diagram (ASCII), design decisions with reasons, how to run, what tests exist'),
  topicItem('Architecture diagram — shows how components connect: Client → Filter → Controller → Service → DB + Cache'),
  spacer(),
  topicGroupLabel('Design decisions to explain in the README:'),
  topicItem('Why Strategy pattern — adding new payment types without modifying existing code (OCP)'),
  topicItem('Why optimistic locking — better throughput than pessimistic locks for concurrent balance updates'),
  topicItem('Why Redis Lua for rate limiting — INCR + EXPIRE must be atomic. Two separate calls create a race condition.'),
  topicItem('Why cursor-based pagination — OFFSET scans all preceding rows on every page. O(n) per page, O(n²) total.'),
  topicItem('Why Testcontainers — integration tests run against real MySQL/Redis, not mocks. Finds bugs unit tests miss.'),
  note('A README that explains WHY decisions were made signals senior engineering thinking. Most junior projects only say WHAT was built.'),
  spacer(),

  // DAY 46-47
  dayHeading('DAY 46 — Final Test Run + GitHub Polish'),
  topicGroupLabel('What to verify before the final checkpoint:'),
  topicItem('mvn clean test — all 20+ tests green, zero ignored, zero warnings'),
  topicItem('Commit history — no wip, fix, fix2, asdf commits. Every commit tells a story.'),
  topicItem('Secrets check — no .env files, no passwords in yml files committed to GitHub'),
  topicItem('README renders correctly on GitHub — check the preview'),
  spacer(),

  dayHeading('DAY 47 — Phase 1 Final Checkpoint'),
  topicGroupLabel('You must pass every item below before moving to Phase 2:'),
  topicGroupLabel('Java Internals:'),
  topicItem('Walk through HashMap.put() including treeification — 2 minutes'),
  topicItem('LRU cache — code from memory on paper — 15 minutes'),
  topicGroupLabel('Concurrency:'),
  topicItem('Race condition — show one in code, fix it three ways — 3 minutes'),
  topicItem('CompletableFuture thenCompose vs thenCombine — when to use each'),
  topicItem('Deadlock — what causes it, how you prevent it in a money transfer'),
  topicGroupLabel('Spring Boot:'),
  topicItem('@SpringBootApplication — what it expands to — 30 seconds'),
  topicItem('Bean lifecycle — all 10 steps in order'),
  topicItem('@Transactional 3 failure modes — name, explain, fix each'),
  topicGroupLabel('SQL:'),
  topicItem('B-Tree index — how MySQL finds a row — 90 seconds'),
  topicItem('EXPLAIN type=ALL — what it means, how to fix'),
  topicItem('Cursor pagination vs OFFSET — why OFFSET is dangerous'),
  topicGroupLabel('Project:'),
  topicItem('docker-compose up — entire stack starts'),
  topicItem('20+ tests pass with mvn clean test'),
  topicItem('README explains every design decision'),
  topicItem('POST /api/v1/payments works end to end with JWT'),
  topicGroupLabel('System Design:'),
  topicItem('Rate limiter design — deliver in 45 minutes using the 7-step framework'),
  warnP('If you cannot pass every item — do NOT move to Phase 2. Gaps here become walls there.'),
  spacer(),

];

// ─── Build document ──────────────────────────────────────────
const warnP = (text) => new Paragraph({
  spacing: { before: 80, after: 80 },
  children: [new TextRun({ text: `⚠️  ${text}`, bold: true, size: 19, font: 'Arial', color: 'C00000' })]
});

// Fix warn reference in content array (rebuild it)
// Remove the last warn call and replace with proper paragraph
content.pop(); // remove spacer

content.push(new Paragraph({
  spacing: { before: 80, after: 80 },
  children: [new TextRun({ text: `⚠️  If you cannot pass every item — do NOT move to Phase 2. Gaps here become walls there.`, bold: true, size: 19, font: 'Arial', color: 'C00000' })]
}));
content.push(spacer());

const doc = new Document({
  numbering: {
    config: [
      {
        reference: 'bullets',
        levels: [{
          level: 0,
          format: LevelFormat.BULLET,
          text: '•',
          alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 440, hanging: 220 } } }
        }]
      },
      {
        reference: 'subbullets',
        levels: [{
          level: 0,
          format: LevelFormat.BULLET,
          text: '-',
          alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 220 } } }
        }]
      }
    ]
  },
  styles: {
    default: {
      document: { run: { font: 'Arial', size: 20 } }
    }
  },
  sections: [{
    properties: {
      page: {
        size: { width: 12240, height: 15840 },
        margin: { top: 1080, right: 1080, bottom: 1080, left: 1080 }
      }
    },
    children: content
  }]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync('/mnt/user-data/outputs/phase1_study_guide.docx', buf);
  console.log('Done');
});
