const { Document, Packer, Paragraph, TextRun, HeadingLevel, LevelFormat, AlignmentType, BorderStyle } = require('docx');
const fs = require('fs');

// ─── All helpers defined before content ──────────────────────
const weekHeading = (text) => new Paragraph({
  spacing: { before: 400, after: 160 },
  children: [new TextRun({ text, bold: true, size: 36, color: '1F4E79', font: 'Arial' })]
});
const dayHeading = (text) => new Paragraph({
  spacing: { before: 300, after: 100 },
  border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: '2E75B6', space: 4 } },
  children: [new TextRun({ text, bold: true, size: 28, color: '2E75B6', font: 'Arial' })]
});
const label = (text) => new Paragraph({
  spacing: { before: 180, after: 60 },
  children: [new TextRun({ text, bold: true, size: 22, color: '1F4E79', font: 'Arial' })]
});
const bullet = (text) => new Paragraph({
  numbering: { reference: 'bullets', level: 0 },
  spacing: { before: 40, after: 40 },
  children: [new TextRun({ text, size: 20, font: 'Arial' })]
});
const sub = (text) => new Paragraph({
  numbering: { reference: 'subbullets', level: 0 },
  spacing: { before: 20, after: 20 },
  children: [new TextRun({ text, size: 19, font: 'Arial', color: '444444' })]
});
const note = (text) => new Paragraph({
  spacing: { before: 80, after: 80 },
  children: [new TextRun({ text: '📌 ' + text, italics: true, size: 19, font: 'Arial', color: '555555' })]
});
const warn = (text) => new Paragraph({
  spacing: { before: 80, after: 80 },
  children: [new TextRun({ text: '⚠️  ' + text, bold: true, size: 19, font: 'Arial', color: 'C00000' })]
});
const sp = () => new Paragraph({ spacing: { before: 60, after: 60 }, children: [new TextRun('')] });
const pb = () => new Paragraph({ pageBreakBefore: true, children: [new TextRun('')] });

// ─── CONTENT ─────────────────────────────────────────────────
const C = [

  // TITLE
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 0, after: 80 },
    children: [new TextRun({ text: 'Phase 1 — Study Guide', bold: true, size: 56, color: '1F4E79', font: 'Arial' })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 0, after: 60 },
    children: [new TextRun({ text: 'Payment Wallet System — Java Backend Roadmap', size: 26, color: '555555', font: 'Arial' })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 0, after: 300 },
    children: [new TextRun({ text: 'What concepts to understand on each day — before opening your IDE', italics: true, size: 22, color: '888888', font: 'Arial' })] }),

  // ══════════════════════════════════════
  // WEEK 1
  // ══════════════════════════════════════
  weekHeading('WEEK 1 — Java OOP Depth + Git + Maven + Testing Habit'),

  // DAY 1
  dayHeading('DAY 1 — Git Workflow + Maven Basics'),
  label('Git — what you must understand:'),
  bullet('What git is actually for — not backup, but communication between engineers over time'),
  bullet('What an atomic commit is — one logical change, one commit, one clear message'),
  bullet('Conventional commits format — type: description — and what each type means: feat, fix, refactor, chore, test, docs'),
  bullet('Why commit history matters — senior engineers read history before reading code'),
  bullet('What git rebase -i does — combining messy local commits before pushing to remote'),
  bullet('What HEAD~3 means — referring to the last 3 commits relative to current position'),
  bullet('Why squashing exists — keeping history readable and meaningful for the team'),
  sp(),
  label('Maven — what you must understand:'),
  bullet('What Maven actually does — dependency management, build lifecycle management, packaging'),
  bullet('What each dependency scope means:'),
  sub('compile — default. Available everywhere including the production jar.'),
  sub('test — JUnit and Mockito go here. NOT included in the production jar.'),
  sub('provided — container (e.g. Tomcat) provides it at runtime, not packaged.'),
  sub('runtime — not needed to compile, but needed at runtime.'),
  bullet('What a transitive dependency is — when you add spring-boot-starter-web, it pulls in Tomcat, Jackson, Spring MVC and many more'),
  bullet('What mvn dependency:tree shows — every dependency and exactly where it came from'),
  bullet('What a fat jar is — Spring Boot packages ALL dependencies inside the jar as a zip file'),
  bullet('Why the fat jar runs anywhere — no separate classpath or installation needed'),
  bullet('What BOOT-INF/lib/ contains — every dependency jar bundled inside your jar'),
  note('When a NoClassDefFoundError hits in production, mvn dependency:tree is how you find the cause. This is a real debugging tool.'),
  sp(),

  // DAY 2
  dayHeading('DAY 2 — Interfaces vs Abstract Classes + Strategy Pattern'),
  label('Interfaces vs Abstract Classes — what you must understand:'),
  bullet('What an interface is — a contract defining capabilities, not implementation or data'),
  bullet('What an abstract class is — partial implementation that cannot be instantiated directly'),
  bullet('What changed in Java 8 — default methods added to interfaces for backward compatibility'),
  bullet('What changed in Java 9 — private methods inside interfaces for shared internal logic'),
  bullet('What "instance state" means — fields that belong to a specific object instance (e.g. upiId, maskedCard)'),
  bullet('Why interfaces CANNOT hold instance state — an interface is a contract shared by all implementors. State belongs to instances, not contracts.'),
  bullet('Why abstract classes CAN hold instance state — they represent a base object with shared data'),
  bullet('Multiple inheritance — Java allows implementing multiple interfaces but extending only one class. Why this is safe for interfaces but dangerous for classes.'),
  bullet('The one real post-Java-8 rule: if you need instance state, use abstract class. Otherwise, prefer interface.'),
  sp(),
  label('Strategy Pattern — what you must understand:'),
  bullet('What problem Strategy solves — eliminates if-else chains that grow every time a new payment type is added'),
  bullet('What the three parts of Strategy are: interface (strategy contract), concrete classes (UPI, Card), context (PaymentContext which holds and runs the strategy)'),
  bullet('Why Strategy satisfies OCP — you add new payment types without ever modifying PaymentService'),
  bullet('How Strategy enables testability — you can pass a mock strategy in tests instead of making a real UPI network call'),
  bullet('Why UPIPayment implements the interface rather than extending a class — it has its own instance state (upiId) that no other payment type shares'),
  note('The connection to testing: code depending on an interface can be tested with a mock. Code depending on a concrete class cannot. This is why Strategy matters.'),
  sp(),

  // DAY 3
  dayHeading('DAY 3 — SOLID Principles'),
  label('Why SOLID exists — before learning the rules:'),
  bullet('The real problem SOLID solves — code that is hard to change, hard to test, and breaks unexpectedly when modified'),
  bullet('How SOLID violations show up in code review — the exact vocabulary senior engineers use: "this class has too many responsibilities", "this is tightly coupled", "this cannot be tested"'),
  sp(),
  label('SRP — Single Responsibility Principle:'),
  bullet('What "responsibility" actually means — a reason to change, not just "does one thing"'),
  bullet('Why multiple responsibilities in one class cause problems — two different teams can conflict editing the same file'),
  bullet('How to identify an SRP violation — ask "how many different reasons could make me change this class?"'),
  bullet('Project example — PaymentService doing payment logic AND email AND logging is 3 responsibilities, 3 reasons to change'),
  sp(),
  label('OCP — Open/Closed Principle:'),
  bullet('What "open for extension, closed for modification" means in plain language'),
  bullet('How your PaymentStrategy interface already implements OCP — adding NetBanking payment never requires touching PaymentService'),
  bullet('What an OCP violation looks like — a switch or if-else block that must grow every time a new type is added'),
  sp(),
  label('LSP — Liskov Substitution Principle:'),
  bullet('What "honouring the contract" means — every implementation must behave as the interface promises for all valid inputs'),
  bullet('What an LSP violation looks like — a subclass that throws exceptions for inputs the interface declares are valid'),
  bullet('Why LSP violations break caller code — callers trust the abstraction and cannot know which implementation will behave correctly'),
  sp(),
  label('ISP — Interface Segregation Principle:'),
  bullet('What a "fat interface" is — forces implementations to provide methods they do not use'),
  bullet('Why fat interfaces create silent bugs — implementations must throw UnsupportedOperationException or return dummy values'),
  bullet('How to split interfaces — by what each specific caller actually needs'),
  sp(),
  label('DIP — Dependency Inversion Principle:'),
  bullet('What "depend on abstraction, not concrete class" means and why it matters'),
  bullet('Why depending on UPIPayment directly makes PaymentService untestable — you cannot replace a hardcoded dependency with a mock'),
  bullet('How constructor injection enables DIP — the interface is passed in from outside, not created inside the class'),
  bullet('Why DIP is the principle that makes mocking and unit testing possible at all'),
  note('SOLID is interview vocabulary. Know all 5 principles using your own project as the example, not textbook definitions.'),
  sp(),

  // DAY 4
  dayHeading('DAY 4 — Strategy Pattern (complete) + Factory Pattern'),
  label('Strategy Pattern — completing your understanding:'),
  bullet('What PaymentContext is and why it exists — the holder of the current strategy, delegates execution to it'),
  bullet('What runtime switching means — user can switch from UPI to Card within the same session without app restart'),
  bullet('Why a null strategy check is necessary — defensive programming: fail fast with a clear error instead of a NullPointerException deep in the stack'),
  sp(),
  label('Factory Pattern — what you must understand:'),
  bullet('What problem Factory solves — the caller should not need to know which concrete class to instantiate'),
  bullet('What "factory decides which class to create" means — based on runtime input, not compile-time hardcoding'),
  bullet('Why a static factory method is common — no need to instantiate the factory itself, simpler to call'),
  bullet('Why the default/unknown case must always be handled explicitly — missing it causes runtime MatchException with no useful message to the caller'),
  bullet('How Factory and Strategy work together in your project — Factory creates the right strategy, Context holds and runs it'),
  note('Interview question: what is the difference between Factory and Strategy? Factory decides what to create. Strategy decides how to behave at runtime.'),
  sp(),

  // DAY 5
  dayHeading('DAY 5 — Singleton Pattern + Builder Pattern'),
  label('Singleton Pattern — what you must understand:'),
  bullet('What Singleton guarantees — only one instance of the class exists in the entire JVM'),
  bullet('Real use cases — config holders, connection pools, JWT token providers, thread pools'),
  bullet('Why the naive version is broken under concurrency — Thread A and B both see null, both create separate instances'),
  bullet('What volatile does in this context — prevents the JVM from reordering the write to the instance field before the constructor finishes'),
  bullet('Why reordering is dangerous — Thread B can see a non-null reference to a partially constructed object and use it'),
  bullet('What double-checked locking is — first check without lock (fast path), second check inside synchronized (safe path)'),
  bullet('Why both checks are needed — first check avoids acquiring the lock on every call. Second check prevents duplicate creation under concurrent access.'),
  sp(),
  label('Builder Pattern — what you must understand:'),
  bullet('What problem Builder solves — telescoping constructors with many parameters become unreadable and error-prone'),
  bullet('What telescoping constructors look like — new PaymentRequest("u1","u2",500.0,"INR","","") — which parameter is which?'),
  bullet('How Builder separates required from optional fields — required fields in Builder constructor, optional fields as named fluent methods'),
  bullet('What method chaining (fluent API) means — each setter returns "this" so calls can be chained: .currency("INR").description("rent")'),
  bullet('Why the resulting object is immutable — private constructor, all fields final, only Builder can create it'),
  bullet('Where Lombok @Builder saves time — generates all this boilerplate automatically in Spring Boot projects'),
  note('PaymentRequest is the perfect Builder use case — 3 required fields and 3+ optional fields. The readability difference vs a constructor is obvious.'),
  sp(),

  // DAY 6
  dayHeading('DAY 6 — Observer Pattern + Week 1 Integration'),
  label('Observer Pattern — what you must understand:'),
  bullet('What problem Observer solves — when one event must notify multiple independent handlers without the source knowing who they are'),
  bullet('The wallet example: payment success must trigger audit log, fraud check, and notification. Without Observer, PaymentService calls all three directly — tight coupling.'),
  bullet('Why direct coupling is a problem — adding a fourth handler requires modifying PaymentService. OCP violated every time.'),
  bullet('What the three parts of Observer are: subject/publisher (fires events), observer interface (contract for handlers), concrete observers (AuditLogger, FraudDetector)'),
  bullet('How Observer satisfies OCP — adding a new observer never requires modifying PaymentEventPublisher'),
  bullet('How Observer relates to the real world — Spring ApplicationEvents, Kafka consumers, and webhook notification systems all use this same pattern'),
  bullet('What unsubscribe is for — removing observers when no longer needed, preventing memory leaks'),
  sp(),
  label('Week 1 integration — what to verify:'),
  bullet('Every class built this week exists in the correct package inside payment-wallet'),
  bullet('Every class has at least one corresponding test that is green'),
  bullet('All commit messages follow the type: description format without exception'),
  bullet('No WIP, fix, fix2, or asdf commits anywhere in the GitHub history'),
  sp(),

  // DAY 7
  dayHeading('DAY 7 — Week 1 Checkpoint (Sunday)'),
  label('Answer every question from memory. No notes. No IDE.'),
  bullet('Why can an interface not hold instance state? What exactly happens at compile time if you try?'),
  bullet('After Java 8, what is the one remaining reason to choose an abstract class over an interface?'),
  bullet('Explain LSP using your PaymentStrategy implementations as the example'),
  bullet('Walk through Strategy pattern using PaymentContext — what problem does it solve?'),
  bullet('Why does JwtTokenProvider need volatile? What breaks without it under concurrent access?'),
  bullet('Why does Builder exist? Show a PaymentRequest construction with 5 fields — would a constructor be readable?'),
  bullet('How does Observer satisfy OCP? What would violate OCP in the same scenario?'),
  bullet('What does git rebase -i do and when would you use it before pushing?'),
  bullet('What is inside a fat jar and why does Spring Boot package it that way?'),
  warn('If you cannot answer any question without notes — do not move to Week 2. Spend the remaining time on the weak area. Week 2 builds directly on this foundation.'),
  sp(),

  pb(),

  // ══════════════════════════════════════
  // WEEK 2
  // ══════════════════════════════════════
  weekHeading('WEEK 2 — Java Internals: Collections + JVM Memory'),

  dayHeading('DAY 8 — HashMap Internals Part 1: hashCode, buckets, collision'),
  label('Internal structure — what you must understand:'),
  bullet('What a hash function is — converts any object into an integer. Not necessarily unique.'),
  bullet('Internal structure of HashMap — an array of Node objects. Each Node holds: key, value, hash, and next pointer for chaining.'),
  bullet('Default initial capacity — 16 buckets. What this means physically in memory.'),
  bullet('How put() decides which bucket — (capacity - 1) & hash. Bitwise AND, not modulo.'),
  bullet('Why bitwise AND instead of modulo — faster operation at CPU level. Works because capacity is always a power of 2.'),
  sp(),
  label('Collision handling — what you must understand:'),
  bullet('What a collision is — two different keys producing the same bucket index'),
  bullet('How collisions are handled — linked list chaining: new node added to the chain in that bucket'),
  bullet('How get() finds a value when there is a collision — walks the chain, uses equals() to compare each key'),
  bullet('The equals() + hashCode() contract — if two objects are equal by equals(), they must produce the same hashCode'),
  bullet('What breaks when you override equals() without overriding hashCode() — get() cannot find the key. Returns null for a key you just put in.'),
  bullet('Null key handling — always stored in bucket 0. Special case in putVal().'),
  note('"FB".hashCode() == "Ea".hashCode() == 2236. This is the classic collision demo. Run it and see it happen.'),
  sp(),

  dayHeading('DAY 9 — HashMap Internals Part 2: treeification, resize, ConcurrentHashMap'),
  label('Treeification — what you must understand:'),
  bullet('What treeification is — converting a bucket\'s linked list into a Red-Black TreeNode when it gets too long'),
  bullet('When it triggers — TREEIFY_THRESHOLD = 8 nodes in one bucket'),
  bullet('Why it exists — O(n) linked list lookup becomes O(log n) tree lookup. Protects against hash collision attacks.'),
  bullet('When it matters — malicious input designed to force all keys into one bucket (hash flooding attack)'),
  sp(),
  label('Resize — what you must understand:'),
  bullet('When resize triggers — size exceeds capacity × loadFactor (default 0.75)'),
  bullet('What happens during resize — capacity doubles, every entry rehashed into the new larger array. O(n) operation.'),
  bullet('Why resize is expensive — every entry must be recalculated and moved. Avoid it for known-size maps.'),
  bullet('How to avoid resize — set initial capacity to expectedSize / 0.75 + 1 when you know the size upfront'),
  sp(),
  label('ConcurrentHashMap — what you must understand:'),
  bullet('Why HashMap is not thread-safe — two threads calling put() simultaneously can corrupt the internal array structure'),
  bullet('How ConcurrentHashMap achieves thread safety — CAS + synchronized on individual buckets (Java 8+). No global lock.'),
  bullet('Why ConcurrentHashMap forbids null keys and null values — null is ambiguous under concurrent access'),
  bullet('The null ambiguity problem — get(null)==null could mean the key is not present OR the value is null. Indistinguishable concurrently.'),
  bullet('When to choose which — single-threaded: HashMap. Multi-threaded: ConcurrentHashMap.'),
  note('This is the most common Java internals interview topic at product companies. Know every piece of it.'),
  sp(),

  dayHeading('DAY 10 — ArrayList vs LinkedList + JVM Memory Basics'),
  label('ArrayList — what you must understand:'),
  bullet('Internal structure — backed by a plain Object array in contiguous memory'),
  bullet('Random access O(1) — index directly into the array, one operation regardless of size'),
  bullet('Add to end O(1) amortised — array doubles in size when full. Occasional O(n) copy, amortised O(1).'),
  bullet('Add/remove in middle O(n) — every element after the insertion point must shift right or left'),
  bullet('Why ArrayList is cache-friendly — contiguous memory means CPU prefetcher can load nearby elements proactively'),
  sp(),
  label('LinkedList — what you must understand:'),
  bullet('Internal structure — doubly-linked nodes. Each node holds: value, prev pointer, next pointer.'),
  bullet('Add/remove at head or tail O(1) — just update the relevant pointers'),
  bullet('Random access O(n) — must walk from head node to find the element at index n'),
  bullet('Why LinkedList is cache-unfriendly — nodes are scattered across heap memory. Pointer chasing defeats CPU cache.'),
  bullet('The real-world rule — use ArrayList almost always. Use LinkedList only for frequent head/tail operations with no random access.'),
  bullet('Why ArrayDeque beats LinkedList for queue behaviour — cache-friendly, no per-node allocation overhead'),
  sp(),
  label('JVM Memory — four areas you must know:'),
  bullet('Heap — all objects live here. Shared across all threads. GC manages this.'),
  bullet('Stack — one stack per thread. Holds stack frames. Each frame holds local variables and method call context. StackOverflowError when exceeded.'),
  bullet('Metaspace — class metadata, static fields. Not garbage collected normally. OutOfMemoryError if uncapped.'),
  bullet('PC Register — current instruction pointer per thread.'),
  bullet('Stack vs Heap in a method — the variable reference lives on the stack. The object it points to lives on the heap.'),
  bullet('When an object becomes eligible for GC — when no live references from any thread can reach it'),
  note('Interview question: where does a local variable live? Stack. Where does the object it references live? Heap.'),
  sp(),

  dayHeading('DAY 11 — Garbage Collection Basics + Mockito Introduced'),
  label('Garbage Collection — what you must understand:'),
  bullet('What GC does — automatically reclaims heap memory for objects with no live references. You never call free().'),
  bullet('Generational hypothesis — most objects die young. JVM exploits this by dividing the heap into generations.'),
  bullet('Young Generation (Eden + Survivor) — new objects born here. Minor GC is frequent and fast.'),
  bullet('Old Generation (Tenured) — objects that survive multiple minor GCs are promoted here. Major GC is rare but slow.'),
  bullet('Stop-The-World pause — JVM freezes ALL application threads to run GC. Real production latency spike.'),
  bullet('G1GC (Java 9+ default) — divides heap into regions, collects highest-garbage regions first. Predictable pause times.'),
  bullet('Memory leak pattern — a static collection holding object references forever. Those objects can never be GC\'d.'),
  sp(),
  label('Mockito — what you must understand:'),
  bullet('What Mockito does — creates fake (mock) implementations of dependencies for isolated unit testing'),
  bullet('Why mocks are necessary — without them, testing PaymentService requires a real UPI gateway, real database, real email server'),
  bullet('What @Mock does — creates a fake object that records all calls but does nothing by default'),
  bullet('What @InjectMocks does — creates the real object under test and injects all @Mock fields into it automatically'),
  bullet('What when().thenReturn() does — programs the mock to return a specific value when a specific method is called'),
  bullet('What verify() does — asserts that a mock method was called with specific arguments the expected number of times'),
  bullet('The key difference — mocks give you complete control over dependency behaviour. Real objects do what they do.'),
  sp(),

  dayHeading('DAY 12 — LRU Cache Implementation'),
  label('LRU Cache — what you must understand:'),
  bullet('What LRU means — Least Recently Used. When cache is full, evict the entry that was accessed least recently.'),
  bullet('Where LRU is used in real systems — Spring @Cacheable eviction, Redis eviction policies, CPU cache, browser cache'),
  bullet('Why LRU needs two data structures — HashMap for O(1) lookup + doubly-linked list for O(1) move-to-front and O(1) remove-from-tail'),
  bullet('What LinkedHashMap does internally — maintains a HashMap AND a doubly-linked list simultaneously. Both access order and FIFO modes available.'),
  bullet('What accessOrder=true means — every get() moves the accessed entry to the tail (most recently used end)'),
  bullet('What accessOrder=false means (default) — insertion order only. get() does not reorder entries. This gives FIFO, not LRU.'),
  bullet('What removeEldestEntry() does — called after every put(). Override to return true when size exceeds capacity to trigger eviction.'),
  bullet('Why the eldest entry is the LRU entry — because get() moves accessed entries to the tail, the head is always least recently used'),
  note('This is a common interview coding question. You must be able to implement it from memory using LinkedHashMap. Know why accessOrder=true makes it LRU vs FIFO.'),
  sp(),

  dayHeading('DAY 13 — Mockito Depth: ArgumentCaptor + @Spy'),
  label('ArgumentCaptor — what you must understand:'),
  bullet('What ArgumentCaptor does — captures the actual argument that was passed to a mock method so you can assert on it'),
  bullet('When to use it — when you cannot predict the exact argument value upfront (e.g. auto-generated timestamps, UUIDs)'),
  bullet('How to use it — declare captor, pass captor.capture() inside verify(), then call captor.getValue() to get what was actually passed'),
  bullet('Real use case — verifying the exact PaymentRequest sent to a payment gateway, including auto-generated fields like timestamp or transaction ID'),
  sp(),
  label('@Spy — what you must understand:'),
  bullet('What @Spy does — wraps a REAL object but lets you verify calls on it and stub specific methods if needed'),
  bullet('The key difference from @Mock — @Mock creates a complete fake (all methods do nothing). @Spy wraps a real object (methods execute normally unless stubbed).'),
  bullet('When to use @Spy — when you want mostly real behaviour but need to verify that a method was called or stub one specific method'),
  bullet('When to use @Mock instead — almost always. Use @Spy only when the real implementation genuinely matters for the test.'),
  note('Interview question: what is the difference between @Mock and @Spy? Know this answer cold.'),
  sp(),

  dayHeading('DAY 14 — Week 2 Checkpoint (Sunday)'),
  label('Answer every question from memory. No notes. No IDE.'),
  bullet('Walk through HashMap.put() step by step — hashCode, bucket calculation, collision handling, equals check'),
  bullet('What is treeification? When does it trigger? Why does it exist?'),
  bullet('Why does ConcurrentHashMap not allow null keys? What would go wrong if it did?'),
  bullet('You have 1 million entries going into a HashMap. What initial capacity do you set and why?'),
  bullet('Why is ArrayList faster than LinkedList for random access? Use the word "cache" in your answer.'),
  bullet('When would you choose LinkedList over ArrayList? Be specific about the access pattern.'),
  bullet('Code an LRU cache from memory on paper using LinkedHashMap. What does accessOrder=true do?'),
  bullet('Where does a local variable live? Where does the object it references live?'),
  bullet('What is a Stop-The-World pause? Which GC generation causes longer pauses and why?'),
  bullet('What is the difference between @Mock and @Spy? When would you use each?'),
  warn('If you cannot code LRU from memory or explain HashMap collision handling without notes — do not move to Week 3. Concurrency builds directly on these internals.'),
  sp(),

  pb(),

  // ══════════════════════════════════════
  // WEEK 3
  // ══════════════════════════════════════
  weekHeading('WEEK 3 — Java Concurrency Advanced + Docker Basics'),

  dayHeading('DAY 15 — Thread Lifecycle + ExecutorService'),
  label('Thread lifecycle — what you must understand:'),
  bullet('All 6 states and what each means: NEW → RUNNABLE → RUNNING → BLOCKED / WAITING / TIMED_WAITING → TERMINATED'),
  bullet('BLOCKED — thread is waiting to acquire a synchronized lock held by another thread'),
  bullet('WAITING — thread called wait() or join() with no timeout. Waiting indefinitely for a signal.'),
  bullet('TIMED_WAITING — thread called sleep(n) or wait(n). Will wake after the timeout.'),
  bullet('Why a thread can be alive but not executing — it is in BLOCKED or WAITING state. This matters when reading thread dumps.'),
  sp(),
  label('Why raw threads are never created directly in production:'),
  bullet('Memory cost — each thread needs ~1MB stack by default. 10,000 threads = ~10GB RAM for stacks alone.'),
  bullet('OS scheduling overhead — creating and destroying OS threads is an expensive system call'),
  bullet('No resource control — unbounded thread creation can exhaust memory and crash the JVM'),
  sp(),
  label('ExecutorService — what you must understand:'),
  bullet('What ExecutorService is — manages a reusable pool of threads. Tasks are submitted, threads are reused.'),
  bullet('newFixedThreadPool(n) — exactly n threads, always. Predictable resource usage. Prefer over cached pool.'),
  bullet('What Future is — a handle to an async computation. future.get() blocks the calling thread until the result is ready.'),
  bullet('Why future.get() without a timeout is dangerous in production — if the task hangs, the calling thread blocks forever'),
  bullet('Why pool.shutdown() is always required — daemon vs non-daemon threads. Pool threads are non-daemon. JVM will not exit until they are stopped.'),
  bullet('What awaitTermination() does — waits for already-submitted tasks to finish before returning'),
  note('Production rule: always use future.get(timeout, unit). Never call get() without a timeout.'),
  sp(),

  dayHeading('DAY 16 — synchronized vs volatile vs AtomicInteger + Java Memory Model + BalanceManager'),
  label('Java Memory Model — the root cause of all race conditions:'),
  bullet('What the Java Memory Model defines — each CPU core has its own cache. Writes by one thread are not immediately visible to other threads.'),
  bullet('What a race condition is — two threads reading and writing the same data without coordination, producing incorrect results'),
  bullet('The lost update problem — Thread 1 reads balance=1000, Thread 2 reads balance=1000, both add 500, both write 1500. The correct result is 2000. Money disappeared.'),
  sp(),
  label('synchronized — what it provides:'),
  bullet('Mutual exclusion — only one thread can execute the synchronized block at a time'),
  bullet('Memory visibility — changes made inside the block are flushed to main memory and visible to all threads'),
  bullet('The cost — threads queue up waiting for the lock. Heavy use of synchronized creates a bottleneck.'),
  sp(),
  label('volatile — what it provides and does NOT provide:'),
  bullet('What volatile provides — memory visibility. Reads and writes go directly to main memory, bypassing CPU cache.'),
  bullet('What volatile does NOT provide — atomicity. count++ is 3 separate operations (read, increment, write). volatile does not make this atomic.'),
  bullet('When volatile is the correct tool — boolean flags written by one thread and read by others: volatile boolean isRunning = true'),
  bullet('When volatile is the wrong tool — any read-modify-write operation. Two threads reading volatile count=0, both incrementing, both writing 1. Final count: 1, not 2.'),
  sp(),
  label('AtomicInteger / AtomicLong and CAS — what you must understand:'),
  bullet('What CAS means — Compare And Swap. A single hardware-level atomic CPU instruction.'),
  bullet('How CAS works — "if the current value is X, atomically set it to Y and return true. Otherwise return false." All in one instruction.'),
  bullet('Why CAS is faster than synchronized — no lock, no thread queuing, no OS-level context switch'),
  bullet('The CAS loop pattern — read current value, compute new value, attempt CAS. If CAS fails (someone else changed it), loop and retry.'),
  bullet('What compareAndSet() returns — true if the swap succeeded, false if someone else changed the value between read and write'),
  note('The BalanceManager debit() method uses a CAS loop. This is exactly how real payment systems handle concurrent balance updates without locks.'),
  sp(),

  dayHeading('DAY 17 — CompletableFuture'),
  label('Why CompletableFuture exists — the problem with Future:'),
  bullet('Future.get() blocks the calling thread. You cannot chain operations. You cannot handle failures cleanly. You cannot compose multiple futures.'),
  bullet('CompletableFuture adds — non-blocking chaining, parallel composition, and declarative exception handling'),
  sp(),
  label('Core operations — what each does and when to use it:'),
  bullet('supplyAsync(() -> result) — runs the lambda asynchronously on a thread pool, returns a CompletableFuture<T>'),
  bullet('thenApply(fn) — transforms the result with a synchronous function. Like map(). Use when the transformation itself is not async.'),
  bullet('thenCompose(fn) — chains a dependent async step. Like flatMap(). Use when Step 2 is also async AND depends on Step 1\'s result.'),
  bullet('thenCombine(other, fn) — runs two independent futures simultaneously and combines their results when both complete'),
  bullet('exceptionally(fn) — catches any exception in the chain and returns a fallback value. Prevents the exception from propagating.'),
  bullet('join() — like get() but throws unchecked exception. Use inside lambdas where checked exceptions are not allowed.'),
  sp(),
  label('The key distinction you must internalize:'),
  bullet('thenCompose vs thenCombine — use compose when Step 2 depends on Step 1\'s result. Use combine when both steps are fully independent and can run in parallel.'),
  bullet('Wallet example — fraud check and bank validation do not depend on each other. Run both with thenCombine. Sequential wastes the time of the faster check.'),
  note('If fraudCheck=500ms and bankValidation=700ms: sequential = 1200ms. thenCombine = ~700ms. This is the real performance difference.'),
  sp(),

  dayHeading('DAY 18 — Deadlocks + Docker Basics'),
  label('Deadlocks — what you must understand:'),
  bullet('What a deadlock is — Thread 1 holds lock A and waits for B. Thread 2 holds B and waits for A. Both wait forever. Neither can proceed.'),
  bullet('The four conditions that together cause deadlock — mutual exclusion, hold and wait, no preemption, circular wait'),
  bullet('How to prevent deadlock — always acquire locks in the same globally agreed order (e.g. lowest account ID first)'),
  bullet('Why lock ordering works — if all threads agree to acquire locks in the same order, circular wait becomes impossible'),
  bullet('What a thread dump is — a snapshot of every thread\'s state, what it holds, and what it is waiting for'),
  bullet('How to read a thread dump — find BLOCKED threads, find what each is waiting on, trace the circular chain'),
  bullet('How to take a thread dump — kill -3 <pid> on Linux, or Run > Dump Threads in IntelliJ'),
  note('Reading a thread dump is a production skill you will use when a service hangs at 2am and has no debugger attached.'),
  sp(),
  label('Docker — what you must understand before writing the Dockerfile:'),
  bullet('What problem Docker solves — "it works on my machine". Docker packages app + runtime + dependencies into a container image.'),
  bullet('What an image is — a read-only, layered template. What a container is — a running instance of an image.'),
  bullet('What a Dockerfile is — sequential instructions to build an image layer by layer. Each instruction is a layer.'),
  bullet('What docker-compose is — defines and runs multiple containers together. Your app + MySQL + Redis in one file.'),
  bullet('Why volumes exist in docker-compose — MySQL data persists across container restarts without volumes'),
  bullet('Essential commands to know — docker ps, docker logs, docker exec -it, docker-compose up -d, docker-compose stop'),
  sp(),

  dayHeading('DAY 19 — ThreadPoolExecutor Deep + HTTP Fundamentals'),
  label('ThreadPoolExecutor — what you must understand:'),
  bullet('Why Executors factory methods hide important details — newCachedThreadPool() has unbounded thread creation. You cannot see or control the real parameters.'),
  bullet('corePoolSize — threads kept alive even when idle. Always available.'),
  bullet('maximumPoolSize — ceiling on threads ever created. Beyond this, tasks go to the queue.'),
  bullet('Queue — tasks wait here when all core threads are busy. ALWAYS use a bounded queue. Unbounded queue can grow without limit and cause OOM.'),
  bullet('RejectionPolicy — what happens when queue is full AND all max threads are busy:'),
  sub('CallerRunsPolicy — the thread that submitted the task executes it. Slows the producer. Never drops payments. Best for financial systems.'),
  sub('AbortPolicy — throws RejectedExecutionException. Default behaviour. Drops the task.'),
  sub('DiscardPolicy — silently discards the task. Never acceptable for financial data.'),
  sub('DiscardOldestPolicy — drops the oldest queued task. Never acceptable for financial data.'),
  bullet('Pool sizing formula for IO-bound workloads — (CPU core count × 2) + 1'),
  sp(),
  label('HTTP fundamentals — what you must understand:'),
  bullet('Full lifecycle of an HTTP request — DNS lookup → TCP 3-way handshake → TLS handshake (HTTPS) → HTTP request sent → server processes → HTTP response → connection reused or closed'),
  bullet('What the TCP 3-way handshake is — SYN, SYN-ACK, ACK. Required before any data can be exchanged.'),
  bullet('What TLS handshake does — negotiates encryption algorithm and exchanges keys. Adds multiple round trips. Expensive.'),
  bullet('Why connection pooling exists — creating a new TCP+TLS connection for every single DB or HTTP request is too expensive. Reuse existing connections.'),
  bullet('How HTTP keep-alive works — the connection stays open after the response is sent. The next request reuses it without a new handshake.'),
  bullet('HikariCP for DB and HttpClient pool for HTTP serve the same purpose — both avoid expensive connection creation on every request'),
  note('curl -v https://httpbin.org/get shows every step of the HTTP conversation. Run it and read every single line of output.'),
  sp(),

  dayHeading('DAY 20 — Week 3 Integration + Debugging'),
  label('What to understand before the integration day:'),
  bullet('How Week 3 pieces connect — ExecutorService manages threads, CompletableFuture chains async steps, BalanceManager uses CAS, PaymentBatchProcessor ties all of them together'),
  bullet('What a conditional breakpoint is — a breakpoint that only pauses execution when a boolean condition is true (e.g. balance < 0 after debit)'),
  bullet('Why conditional breakpoints are essential for concurrency debugging — you cannot step through 100 concurrent threads manually'),
  bullet('The debugging approach — introduce the race condition deliberately, set a conditional breakpoint on the wrong state, run the concurrent test, let the bug surface'),
  sp(),

  dayHeading('DAY 21 — Week 3 Checkpoint (Sunday)'),
  label('Answer every question from memory. No notes. No IDE.'),
  bullet('What is a race condition? Show one in code and fix it three different ways.'),
  bullet('Why is volatile not enough for count++? What is happening at the CPU level?'),
  bullet('What is a deadlock? How do you prevent one in a money transfer between two accounts?'),
  bullet('What is thenCompose vs thenCombine? When exactly do you use each?'),
  bullet('What happens when all threads in a ThreadPoolExecutor are busy and the queue is full?'),
  bullet('You need to process 1000 payment requests per second. Walk me through your design approach.'),
  bullet('How do you read a thread dump? What do BLOCKED and WAITING states tell you?'),
  warn('If you cannot answer these questions confidently — do not move to Week 4.'),
  sp(),

  pb(),

  // ══════════════════════════════════════
  // WEEK 4
  // ══════════════════════════════════════
  weekHeading('WEEK 4 — Spring Boot Internals + JWT + AOP'),

  dayHeading('DAY 22 — @SpringBootApplication Internals + Auto-Configuration'),
  label('@SpringBootApplication — what it expands to:'),
  bullet('@SpringBootConfiguration — marks the class as a Spring configuration source (equivalent to @Configuration)'),
  bullet('@ComponentScan — scans the current package and all subpackages for @Component, @Service, @Repository, @Controller'),
  bullet('@EnableAutoConfiguration — triggers Spring Boot\'s auto-configuration mechanism'),
  sp(),
  label('SpringApplication.run() — what happens step by step:'),
  bullet('Step 1 — determines application type: SERVLET (web with Tomcat), REACTIVE, or NONE (non-web)'),
  bullet('Step 2 — loads SpringApplicationRunListeners from spring.factories'),
  bullet('Step 3 — prepares the Environment: reads application.yml, environment variables, command-line arguments, in priority order'),
  bullet('Step 4 — creates the ApplicationContext (the container that holds all beans)'),
  bullet('Step 5 — refreshes context: processes all @Configuration classes, runs auto-configuration, instantiates all beans, starts embedded Tomcat'),
  bullet('Step 6 — calls ApplicationRunner and CommandLineRunner beans — startup tasks'),
  sp(),
  label('Auto-configuration — what you must understand:'),
  bullet('The auto-configuration imports file — META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports lists ~150 configuration classes'),
  bullet('@ConditionalOnClass — the auto-configuration bean is only created if a specific class exists on the classpath'),
  bullet('@ConditionalOnMissingBean — the auto-configuration bean is only created if you have NOT already defined your own'),
  bullet('Full DataSource creation chain — add JPA starter → Hibernate JAR on classpath → @ConditionalOnClass(DataSource.class) fires → DataSource created from application.yml properties'),
  bullet('Why this matters — "Spring magic" is just conditional class and bean checking. There is no magic. Read the source.'),
  note('Failure simulation: remove spring-boot-starter-web. App starts and immediately exits — no Tomcat, no reason to stay alive. This is what the web starter actually does.'),
  sp(),

  dayHeading('DAY 23 — Bean Lifecycle + BeanPostProcessor'),
  label('Bean lifecycle — memorise all 10 steps in exact order:'),
  bullet('1. Constructor called — object instantiated. No dependencies injected yet. Do not use @Autowired fields here.'),
  bullet('2. @Autowired dependencies injected — field or setter injection happens here'),
  bullet('3. Aware callbacks — BeanNameAware, ApplicationContextAware, etc. Spring injects framework references.'),
  bullet('4. BeanPostProcessor.postProcessBeforeInitialization() — runs before @PostConstruct for every bean'),
  bullet('5. @PostConstruct method called — dependencies are ready. Safe to use them here. Initialization logic goes here.'),
  bullet('6. InitializingBean.afterPropertiesSet() — alternative to @PostConstruct'),
  bullet('7. BeanPostProcessor.postProcessAfterInitialization() — THIS IS WHERE AOP PROXIES ARE CREATED'),
  bullet('8. Bean is READY — in the context and available for injection. Handles requests.'),
  bullet('9. @PreDestroy called on shutdown — clean up connections, flush buffers, release resources'),
  bullet('10. DisposableBean.destroy() — alternative to @PreDestroy'),
  sp(),
  label('BeanPostProcessor — what you must understand:'),
  bullet('What BeanPostProcessor is — an interface that runs code before and after initialization for EVERY bean in the context'),
  bullet('Why step 7 is the critical step — AOP proxies are created here. Before step 7, the bean has no AOP wrapping. After step 7, it does.'),
  bullet('How Spring uses BeanPostProcessor internally — @Transactional, @Async, @Cacheable, and all AOP-based annotations are applied here'),
  bullet('Why you cannot safely use @Autowired dependencies in the constructor — injection happens at step 2, after the constructor at step 1'),
  bullet('@PostConstruct is the correct place for initialization logic that needs dependencies — everything is ready at step 5'),
  note('AOP proxies are created at step 7. This is why @Transactional only works on public methods called through the Spring proxy, not through "this".'),
  sp(),

  dayHeading('DAY 24 — @Transactional Deeply: 3 Silent Failure Modes'),
  label('How @Transactional works — the proxy mechanism:'),
  bullet('Spring wraps @Transactional classes with a proxy object at BeanPostProcessor step 7'),
  bullet('When you call a method through the proxy, the proxy begins a transaction, calls your real method, then commits or rolls back'),
  bullet('Calling the method through "this" bypasses the proxy entirely — the proxy never intercepts the call'),
  sp(),
  label('Failure Mode 1 — Self-invocation (the most common mistake):'),
  bullet('What happens — method A (non-transactional) calls @Transactional method B using "this.B()"'),
  bullet('Why it fails — "this" refers to the real object, not the proxy. The proxy is bypassed. No transaction is started.'),
  bullet('How to reproduce — call a @Transactional method from within the same class. Throw a RuntimeException. Verify no rollback occurred.'),
  bullet('Fix 1 — inject the bean into itself via @Autowired and call through the injected reference (calls through proxy)'),
  bullet('Fix 2 — move the @Transactional method to a separate service class'),
  sp(),
  label('Failure Mode 2 — Checked exceptions do not trigger rollback:'),
  bullet('Default rollback behaviour — @Transactional only rolls back on RuntimeException and Error. Not on checked Exception.'),
  bullet('Why — Java checked exceptions are meant to represent recoverable situations. The Spring designers treated them differently.'),
  bullet('The dangerous scenario — debit() succeeds (saves to DB), then a checked exception is thrown. No rollback. Account debited, payment not recorded. Data inconsistency.'),
  bullet('Fix — @Transactional(rollbackFor = Exception.class) to roll back on all exceptions including checked'),
  sp(),
  label('Failure Mode 3 — @Transactional on private methods is silently ignored:'),
  bullet('Why — AOP proxies can only intercept public methods. Private methods are called directly on the real object, not through the proxy.'),
  bullet('No error, no warning, no exception — @Transactional simply has no effect on private methods. The most dangerous failure mode.'),
  bullet('Fix — always apply @Transactional to public methods only'),
  sp(),
  label('Propagation levels — the two you must know:'),
  bullet('REQUIRED (default) — join an existing transaction if one exists, create a new one if not. Correct for 95% of cases.'),
  bullet('REQUIRES_NEW — always create a new transaction, suspending any existing one. Use for audit logs that must persist even if the outer transaction rolls back.'),
  note('High-frequency fintech interview topic. Know all 3 failure modes with their causes and fixes.'),
  sp(),

  dayHeading('DAY 25 — Spring Security + JWT Filter + MDC Request ID Filter'),
  label('Spring Security filter chain — what you must understand:'),
  bullet('What the filter chain is — every HTTP request passes through a sequence of filters before reaching your controller'),
  bullet('Why OncePerRequestFilter — guarantees the filter logic runs exactly once per request regardless of forward/include dispatches'),
  bullet('What SecurityContextHolder is — thread-local storage holding the current authenticated user for the duration of a request'),
  bullet('Why SecurityContextHolder is thread-local — each request is handled by one thread. Thread-local isolates auth state between concurrent requests.'),
  sp(),
  label('JWT — what you must understand:'),
  bullet('What JWT is — a cryptographically signed token encoding user identity and claims. No server-side session needed.'),
  bullet('Three parts of a JWT — header (algorithm name), payload (user claims: id, roles, expiry), signature (HMAC of header+payload)'),
  bullet('What the signature proves — this token was issued by your server and has not been modified since'),
  bullet('What the filter does — extracts JWT from Authorization header, validates signature, loads user, sets authentication in SecurityContextHolder'),
  bullet('Why the token is validated on every single request — stateless design. Server trusts the signature, not a stored session.'),
  sp(),
  label('MDC — what you must understand:'),
  bullet('What MDC is — Mapped Diagnostic Context. A thread-local key-value map automatically included in every log line.'),
  bullet('Why requestId in MDC is valuable — every log line for a request automatically shows the requestId. You can trace one request across thousands of log lines.'),
  bullet('Why MDC.clear() must be in a finally block — thread pool reuses threads. Without clear(), the requestId from request 1 leaks into request 2 on the same thread.'),
  bullet('The MDC leak bug — request 2 shows request 1\'s ID in logs. Makes log tracing incorrect. A real production bug pattern.'),
  note('MDC.clear() in finally is non-negotiable. Skipping it causes incorrect log correlation in any multi-request service.'),
  sp(),

  dayHeading('DAY 26 — AOP + GlobalExceptionHandler'),
  label('AOP — what you must understand:'),
  bullet('What AOP is — Aspect Oriented Programming. Applies cross-cutting behaviour (logging, security, timing) to methods without modifying them.'),
  bullet('What a "cross-cutting concern" is — logic that applies across many unrelated methods: logging, timing, transaction management, security'),
  bullet('What an Aspect is — the class containing the cross-cutting logic (@Aspect @Component)'),
  bullet('What a Pointcut is — the expression that defines which methods the aspect applies to (e.g. all methods in com.wallet.service.*)'),
  bullet('What @Around does — wraps the target method completely. You decide what to do before, after, and on exception. The most powerful advice type.'),
  bullet('What ProceedingJoinPoint.proceed() does — calls the actual target method. If you forget to call proceed(), the real method NEVER executes.'),
  bullet('What @Before and @After do — simpler. @Before runs before the method. @After runs after (always, like finally).'),
  bullet('How Spring implements AOP — BeanPostProcessor at step 7 creates a proxy that intercepts method calls and delegates to advice'),
  sp(),
  label('GlobalExceptionHandler — what you must understand:'),
  bullet('What @RestControllerAdvice does — intercepts exceptions thrown from any @RestController and converts them to HTTP responses'),
  bullet('What RFC 7807 is — the internet standard format for HTTP API error responses. Fields: type, title, status, detail, instance.'),
  bullet('Why a standard error format matters — API clients can reliably parse and handle errors. No guessing the error shape per endpoint.'),
  bullet('What ProblemDetail is — Spring 6\'s built-in RFC 7807 implementation. No custom error class needed.'),
  bullet('Why including requestId in error responses is important — client logs the requestId, sends it to support, support traces it in backend logs'),
  sp(),

  dayHeading('DAY 27 — REST API Design + PaymentController'),
  label('REST API design principles — what you must understand before writing controllers:'),
  bullet('Resource naming — nouns not verbs. POST /payments not POST /createPayment. The HTTP method is the verb.'),
  bullet('HTTP method semantics — GET (read, safe, idempotent), POST (create), PUT (full replace), PATCH (partial update), DELETE (remove)'),
  bullet('HTTP status codes you must know without looking them up:'),
  sub('201 Created — POST success. Include Location header with URL of created resource.'),
  sub('200 OK — GET, PUT, PATCH success'),
  sub('204 No Content — DELETE success. No body.'),
  sub('400 Bad Request — request format is wrong. Validation failed.'),
  sub('401 Unauthorized — token missing or invalid. Authentication failed.'),
  sub('403 Forbidden — authenticated but not authorised for this resource.'),
  sub('422 Unprocessable Entity — valid format, business rule violated. e.g. insufficient balance.'),
  sub('429 Too Many Requests — rate limit exceeded.'),
  bullet('What idempotency means for a payment API — sending the same request twice must not create two payments'),
  bullet('How the Idempotency-Key header works — client generates a UUID per payment attempt, sends it as a header. Server deduplicates.'),
  bullet('What API versioning solves — breaking changes in v2 do not affect clients still using v1. Always version from day one.'),
  note('The difference between 400 and 422 matters in fintech. 400 = wrong shape. 422 = correct shape, business logic rejected it.'),
  sp(),

  dayHeading('DAY 28 — Week 4 Checkpoint (Sunday)'),
  label('Answer every question from memory. No notes. No IDE.'),
  bullet('What does @SpringBootApplication expand to and what does each part do?'),
  bullet('Walk me through exactly what SpringApplication.run() does, step by step'),
  bullet('How does auto-configuration decide to create a DataSource bean?'),
  bullet('List all 10 bean lifecycle steps in order'),
  bullet('I called a @Transactional method from within the same class. Will it roll back on exception? Why?'),
  bullet('What is BeanPostProcessor and what does Spring use it for internally?'),
  bullet('Why must MDC.clear() be in a finally block? What happens if you skip it?'),
  bullet('What does @Around do and what happens if you forget to call proceed()?'),
  bullet('What is the difference between 401 and 403 status codes?'),
  warn('If you cannot answer these questions confidently — stay on Week 4 for more days before moving to Week 5.'),
  sp(),

  pb(),

  // ══════════════════════════════════════
  // WEEK 5
  // ══════════════════════════════════════
  weekHeading('WEEK 5 — JPA + SQL Depth + Indexes + Schema Patterns'),

  dayHeading('DAY 29 — JPA Entities + Hibernate Internals'),
  label('N+1 problem — what you must understand:'),
  bullet('What N+1 is — 1 query fetches N parent entities, then N more queries fetch their child associations. Total: N+1 queries.'),
  bullet('Why it is dangerous — fetching 1000 accounts executes 1001 queries. Performance degrades linearly with data size.'),
  bullet('What lazy loading is — associations are not loaded until you access them in code. Default for @OneToMany collections.'),
  bullet('What eager loading is — associations loaded immediately in the same query as the parent. Default for @ManyToOne.'),
  bullet('How to fix N+1 — use JOIN FETCH in JPQL query or @EntityGraph on the repository method to load in one query'),
  sp(),
  label('Optimistic locking with @Version — what you must understand:'),
  bullet('What optimistic locking assumes — conflicts are rare. Read freely without locking. Check at write time that nothing changed.'),
  bullet('What the @Version field does — JPA automatically increments it on every UPDATE. If the version in the DB does not match what you read, throw OptimisticLockException.'),
  bullet('The lost update problem without @Version — Thread 1 reads version=5. Thread 2 reads version=5. Thread 1 writes (now version=6). Thread 2 writes based on stale version=5, overwriting Thread 1\'s change.'),
  bullet('With @Version — Thread 2\'s UPDATE affects 0 rows (version=5 no longer exists, it is 6). JPA throws OptimisticLockException. Thread 2 must retry.'),
  bullet('Optimistic vs pessimistic locking — optimistic: higher throughput, occasional retry. Pessimistic (FOR UPDATE): lower throughput, no retry needed. Use optimistic for most payment scenarios.'),
  sp(),
  label('LazyInitializationException — what you must understand:'),
  bullet('What causes it — accessing a lazy-loaded association AFTER the Hibernate session has closed'),
  bullet('When the session closes — @Transactional opens a Hibernate session for the duration of the method. Session closes when the method exits.'),
  bullet('Why accessing the lazy field outside the transaction fails — no open session to execute the SQL query for the association'),
  bullet('Fix 1 — add @Transactional to the service method to keep the session alive through the association access'),
  bullet('Fix 2 — use JOIN FETCH in the repository query to load the association eagerly in one query before the session closes'),
  sp(),

  dayHeading('DAY 30 — B-Tree Indexes + EXPLAIN Output'),
  label('How B-Tree indexes work internally — what you must understand:'),
  bullet('Without index — finding a row by email in 1 million rows scans all 1 million rows. O(n).'),
  bullet('With B-Tree index — 3-4 disk reads maximum regardless of table size. O(log n). This is the single biggest performance lever in backend.'),
  bullet('What a B-Tree physically is — a balanced tree of sorted keys. Leaf nodes point to row data.'),
  bullet('Clustered index (InnoDB primary key) — the leaf node IS the row data. The table IS the B-Tree. No second lookup needed.'),
  bullet('Secondary index — leaf node holds (indexed value, primary key). Finding the row requires two B-Tree traversals.'),
  bullet('What a covering index is — an index that includes all columns the query needs. Eliminates the second lookup to the clustered index entirely.'),
  sp(),
  label('Composite index rules — what you must understand:'),
  bullet('Leftmost prefix rule — index on (user_id, status, created_at) is usable for: user_id alone, user_id+status, or all three. NOT for status alone or created_at alone.'),
  bullet('Why leftmost prefix — the B-Tree is sorted first by user_id, then by status, then by created_at. Skipping user_id means the tree cannot be navigated.'),
  bullet('Column order rule — equality filter columns first, range filter columns last. (user_id, status) for equality, then created_at for range.'),
  bullet('Why wrapping a column in a function destroys index usage — WHERE YEAR(created_at) = 2024 computes a new value per row. The index on created_at cannot be used.'),
  sp(),
  label('EXPLAIN output — what each field means:'),
  bullet('type=ALL — full table scan. Every single row is read. The worst case. Fix it with an index.'),
  bullet('type=ref — index used. Only rows matching the condition are read. Good.'),
  bullet('type=const — primary key or unique key lookup. Exactly one row found. Best case.'),
  bullet('key column — which index MySQL chose to use. NULL means no index was used.'),
  bullet('rows column — estimated number of rows MySQL will examine. High = slow.'),
  bullet('Extra column — "Using filesort" means ORDER BY cannot use an index. "Using index" means a covering index was used.'),
  note('Record real numbers: "Before index: 780ms. After index: 11ms on 100k rows." These specific numbers impress interviewers.'),
  sp(),

  dayHeading('DAY 31 — ACID + Isolation Levels + Locking'),
  label('ACID — how MySQL actually implements each property:'),
  bullet('Atomicity — UNDO LOG. Before any data change, the old value is written to the undo log. Rollback = apply undo log in reverse order.'),
  bullet('Consistency — constraints (NOT NULL, UNIQUE, FOREIGN KEY) enforced together with application-level rules in one atomic operation'),
  bullet('Isolation — configurable via isolation level. See below.'),
  bullet('Durability — REDO LOG (Write-Ahead Log). Committed data is written to the redo log before returning success to the client. Survives crashes.'),
  sp(),
  label('All 4 isolation levels — what each prevents:'),
  bullet('READ UNCOMMITTED — you can read another transaction\'s uncommitted (not yet finalized) data. Allows dirty reads. Never use in financial systems.'),
  bullet('READ COMMITTED — no dirty reads. You only see committed data. Allows non-repeatable reads (same row read twice may return different values). PostgreSQL default.'),
  bullet('REPEATABLE READ — no dirty reads, no non-repeatable reads. The same row read twice in a transaction always returns the same value. MySQL InnoDB default.'),
  bullet('SERIALIZABLE — full isolation. Transactions run as if they are sequential. Slowest. Use only for critical uniqueness checks (promo code redemption).'),
  sp(),
  label('Locking — what you must understand:'),
  bullet('FOR SHARE — shared read lock. Blocks other writers, allows other readers. Use when reading data that must not be modified until your read completes.'),
  bullet('FOR UPDATE — exclusive lock. Blocks all other readers and writers. Use when you will definitely update the row based on what you read.'),
  bullet('Why FOR UPDATE is critical before a balance debit — without it, another transaction can change the balance between your SELECT and your UPDATE'),
  sp(),

  dayHeading('DAY 32 — Fintech Schema Patterns'),
  label('Pattern 1 — Idempotency at DB level:'),
  bullet('What it solves — client retries a payment. Without this pattern, two identical payments are created.'),
  bullet('How it works — UNIQUE constraint on the idempotency_key column in the payments table'),
  bullet('ON DUPLICATE KEY UPDATE id=id — on duplicate insert, silently do nothing. No error thrown. No new row created.'),
  bullet('Why this is necessary alongside Redis idempotency — defense in depth. Redis can fail or expire. The DB constraint is permanent.'),
  sp(),
  label('Pattern 2 — Optimistic locking with version column:'),
  bullet('What it solves — two concurrent updates to the same balance row, one must fail and retry'),
  bullet('How it works — UPDATE accounts SET balance=..., version=version+1 WHERE id=? AND version=? — if 0 rows affected, someone else updated it first'),
  sp(),
  label('Pattern 3 — Soft delete:'),
  bullet('What it solves — financial records must never be permanently deleted. Audit trail, regulatory compliance.'),
  bullet('How it works — deleted_at TIMESTAMP NULL column. "Delete" = SET deleted_at=NOW(). All queries add WHERE deleted_at IS NULL.'),
  bullet('Why hard DELETE is never used in fintech — you lose the audit trail and may violate regulations (RBI, SEBI)'),
  sp(),
  label('Pattern 4 — Cursor-based pagination:'),
  bullet('What OFFSET does — scans all N preceding rows on every page to skip them. Page 1000 with 20 items scans 20,000 rows. Gets slower with every page.'),
  bullet('What cursor-based does — WHERE id < lastSeenId ORDER BY id DESC LIMIT 20. Uses the primary key index. Always O(log n) regardless of page number.'),
  bullet('Why cursor pagination scales — page 1 and page 100,000 take exactly the same time'),
  bullet('The tradeoff — cannot jump to an arbitrary page number. Works for infinite scroll, not traditional numbered pages.'),
  note('Know why each of the 4 patterns exists. Not just what it does — the specific problem it prevents.'),
  sp(),

  dayHeading('DAY 33 — HikariCP + System Design Framework'),
  label('HikariCP — what you must understand:'),
  bullet('What a connection pool is — a set of pre-created database connections that are reused across requests instead of created fresh each time'),
  bullet('Why creating a new DB connection per request is too expensive — TCP handshake + authentication + memory allocation on every single request'),
  bullet('minimum-idle — connections kept alive and ready even when traffic is zero'),
  bullet('maximum-pool-size — the ceiling. More connections is NOT always better. OS context switching overhead increases.'),
  bullet('connection-timeout — how long a request waits for an available connection before receiving an exception'),
  bullet('Pool sizing formula — (CPU core count × 2) + 1 for IO-bound workloads. A 4-core server needs ~9 connections.'),
  bullet('What connection pool exhaustion looks like — all connections checked out, new requests time out waiting. Cascading failure pattern.'),
  sp(),
  label('System Design 7-step framework — use this for every system design interview:'),
  bullet('Step 1 — Clarify requirements (5 min): who uses it, what are the scale numbers, what is the latency budget, what consistency is required'),
  bullet('Step 2 — Estimate scale (5 min): requests per second, storage per year, peak traffic multiplier, bandwidth'),
  bullet('Step 3 — High-level design (10 min): draw the main components — load balancer, app servers, database, cache, queues'),
  bullet('Step 4 — API design (5 min): define the main endpoints, request and response shapes'),
  bullet('Step 5 — Data model (5 min): key tables or data structures, important fields and indexes'),
  bullet('Step 6 — Deep dive (20 min): the interviewer will steer this. Go deep on the hardest or most interesting part.'),
  bullet('Step 7 — Bottlenecks (5 min): what breaks at 10x the estimated load and how you would fix each thing'),
  note('Never jump to a solution before clarifying requirements. Interviewers specifically penalise this.'),
  sp(),

  dayHeading('DAY 34 — Week 5 Integration: 100k rows + EXPLAIN + Optimistic Locking'),
  label('What to understand before this day:'),
  bullet('How to insert bulk data efficiently — stored procedure with a WHILE loop. Run in one transaction for speed.'),
  bullet('What SQL_NO_CACHE does — bypasses MySQL\'s query cache so you measure real disk + index performance, not cached results'),
  bullet('Why recording before/after numbers matters — "index improved this query from 780ms to 11ms on 100k rows" is a specific, credible interview answer'),
  bullet('How OptimisticLockException surfaces in a concurrent test — two threads UPDATE the same row, one gets 0 rows affected, JPA throws the exception'),
  sp(),

  dayHeading('DAY 35 — Week 5 Checkpoint (Sunday)'),
  label('Answer every question from memory. No notes. No IDE.'),
  bullet('How does MySQL physically find a row when you query by email with a B-Tree index?'),
  bullet('EXPLAIN shows type=ALL — what does this mean and exactly how do you fix it?'),
  bullet('What is a covering index and when would you specifically create one?'),
  bullet('List all 4 isolation levels and what each prevents'),
  bullet('Why is OFFSET pagination dangerous on large tables? What do you use instead?'),
  bullet('Optimistic vs pessimistic locking — when do you choose each in a payment system?'),
  warn('If you cannot answer confidently — do not move to Week 6.'),
  sp(),

  pb(),

  // ══════════════════════════════════════
  // WEEK 6
  // ══════════════════════════════════════
  weekHeading('WEEK 6 — Redis Caching + Idempotency + Rate Limiting'),

  dayHeading('DAY 36 — Redis Caching: Cache-Aside Pattern'),
  label('Redis fundamentals — what you must understand before using it:'),
  bullet('What Redis is — an in-memory data structure store. Read latency: microseconds. Database read latency: milliseconds. 100-1000x faster.'),
  bullet('Why Redis is NOT a replacement for a database — data lives in RAM. Process restart = data loss by default. Use for data you can rebuild from the DB.'),
  bullet('What TTL (time-to-live) is — a key expires automatically after N seconds. Prevents stale data from living forever.'),
  sp(),
  label('Cache-aside pattern — what you must understand:'),
  bullet('How it works — check cache first. If HIT, return cached value. If MISS, load from DB, store in cache, return value.'),
  bullet('Why it is called "cache-aside" — the application manages the cache manually. The cache is beside the DB, not in front of it.'),
  bullet('Cache invalidation on write — when you UPDATE the DB, DELETE the corresponding cache key. Force the next read to reload fresh from DB.'),
  bullet('Why DELETE not UPDATE on write — correctly updating a cached value under concurrent writes is complex. Delete is simpler and always correct.'),
  bullet('The cache inconsistency bug — you UPDATE the DB but forget to DELETE the cache. Every subsequent read gets stale data until TTL expires.'),
  bullet('Why TTL alone is not sufficient for balance data — TTL means stale data for up to 60 seconds after every write. Unacceptable for account balances.'),
  note('The most common Redis production bug: updating DB without invalidating cache. Always delete on write.'),
  sp(),

  dayHeading('DAY 37 — Idempotency Service + Rate Limiting with Lua Scripts'),
  label('Idempotency service — what you must understand:'),
  bullet('What idempotency means — performing the same operation multiple times produces the same result as performing it once'),
  bullet('Why payment APIs must be idempotent — network timeouts cause clients to retry. Without idempotency, one timeout = duplicate payment.'),
  bullet('How Redis-backed idempotency works — store idempotency_key → serialized_response for 24 hours. On duplicate request, return the stored response immediately.'),
  bullet('Why 24 hours TTL — covers realistic retry windows. After 24 hours, the key can safely be reused for a new payment.'),
  sp(),
  label('Rate limiting with Lua scripts — what you must understand:'),
  bullet('What rate limiting is — enforcing a maximum number of requests per user per time window'),
  bullet('The race condition without Lua — INCR key and EXPIRE key are two separate Redis commands. Between them, another thread can call INCR and the EXPIRE never gets set. The key never resets.'),
  bullet('What a Lua script does in Redis — executes multiple Redis commands as one atomic operation in a single server-side transaction'),
  bullet('Why "atomic" matters — INCR and EXPIRE are guaranteed to execute together with nothing in between. The race condition is eliminated.'),
  bullet('The sliding window counter algorithm — INCR on each request, EXPIRE only on first request (count == 1), compare count against MAX limit'),
  note('The race condition between INCR and EXPIRE without Lua is a real production bug. This is exactly the problem Lua scripting in Redis solves.'),
  sp(),

  dayHeading('DAY 38 — API Consumption: WebClient + Retry + Timeout'),
  label('Why outbound HTTP calls need resilience patterns:'),
  bullet('External services fail — fraud check API, bank verification API, SMS gateway: all can go down'),
  bullet('External services become slow — a 10-second response from the fraud API ties up your thread for 10 seconds'),
  bullet('Without timeouts — one slow external call can hold a thread indefinitely. Thread pool exhaustion follows. Your API becomes unresponsive.'),
  sp(),
  label('WebClient — what you must understand:'),
  bullet('What WebClient is — Spring\'s non-blocking reactive HTTP client. Replaces RestTemplate for new Spring Boot code.'),
  bullet('responseTimeout — maximum time to wait for a complete response from the server. After this, throw WebClientRequestException.'),
  bullet('CONNECT_TIMEOUT — maximum time to wait for the TCP connection to be established. Separate from and shorter than response timeout.'),
  sp(),
  label('Retry with exponential backoff — what you must understand:'),
  bullet('What exponential backoff is — first retry after 200ms, second after 400ms, third after 800ms. Gives a struggling service time to recover.'),
  bullet('What to retry — network errors (WebClientRequestException), 503 Service Unavailable, 429 Too Many Requests with Retry-After header'),
  bullet('What NOT to retry — 400 Bad Request (your request is wrong), 422 Unprocessable (business logic rejected it)'),
  bullet('What onErrorReturn does — after all retries are exhausted, return a safe fallback value instead of propagating the exception to the caller'),
  sp(),

  dayHeading('DAY 39 — Bean Validation + API Versioning + Graceful Shutdown'),
  label('Bean Validation — what you must understand:'),
  bullet('What Bean Validation is — JSR-380 standard annotations on DTO fields. Spring validates automatically when @Valid is used on @RequestBody.'),
  bullet('Common annotations — @NotNull (not null), @NotBlank (not null and not whitespace), @Positive (number > 0), @DecimalMax (upper bound), @Pattern (regex)'),
  bullet('What @Valid on @RequestBody does — triggers validation of the entire DTO before the controller method is entered'),
  bullet('What happens on validation failure — MethodArgumentNotValidException is thrown, caught by GlobalExceptionHandler, returns 400 with field-level error messages'),
  sp(),
  label('API versioning — what you must understand:'),
  bullet('Why versioning is necessary — you will make breaking changes. Without versioning, existing clients break when you deploy.'),
  bullet('URL versioning (/api/v1/, /api/v2/) — most common approach. Visible, easy to route, easy to document.'),
  bullet('The non-negotiable rule — never modify v1 in place. Add v2 alongside it. Clients on v1 keep working.'),
  sp(),
  label('Graceful shutdown — what you must understand:'),
  bullet('What graceful shutdown means — stop accepting new requests, but allow in-flight requests to complete before the process exits'),
  bullet('Why it is critical for payments — without it, a rolling deployment kills active payment transactions mid-flight. Money in unknown state.'),
  bullet('What SIGTERM is — the signal Kubernetes and Docker send to a container when stopping it. JVM receives it and begins graceful shutdown.'),
  bullet('What server.shutdown=graceful does — Spring Boot stops accepting new requests immediately on SIGTERM but waits up to the configured timeout for in-flight requests to finish'),
  sp(),

  dayHeading('DAY 40 — System Design: URL Shortener + Notification System'),
  label('URL Shortener — topics to understand before designing:'),
  bullet('How Base62 encoding converts an auto-increment integer to a short alphanumeric code — why 7 chars covers trillions of URLs'),
  bullet('Why 302 redirect is used instead of 301 — 302 is temporary, browser does not cache it. Every redirect hits your server = analytics. 301 is permanent, browser caches it = untrackable.'),
  bullet('Role of CDN — popular short URLs are cached at edge nodes globally. The redirect never reaches your origin servers.'),
  bullet('Why read replicas help — URL shorteners are overwhelmingly read-heavy (100:1 read:write). Distribute reads across replicas.'),
  sp(),
  label('Notification System — topics to understand before designing:'),
  bullet('Why Kafka decouples the notification sender from delivery channels — the sender fires and forgets. Kafka absorbs traffic spikes. Workers deliver at their own rate.'),
  bullet('What a Dead Letter Queue (DLQ) is — failed messages after all retries are moved here for manual inspection. Nothing is silently dropped.'),
  bullet('Why different priority Kafka topics exist — OTP must deliver in under 1 second. Marketing batch can wait minutes.'),
  bullet('What each channel requires — email (SendGrid API), SMS (Twilio API), push notifications (FCM for Android, APNs for iOS)'),
  sp(),

  dayHeading('DAY 41 — Week 6 Integration: Full Payment Flow with Redis'),
  label('What to understand before integration day:'),
  bullet('The full payment processing order — idempotency check → rate limit check → async fraud check (starts immediately) → balance debit → wait for fraud result → process payment → store response → cache update → publish event'),
  bullet('Why fraud check starts asynchronously before debit — fraud check and debit are independent. Starting fraud check early saves latency.'),
  bullet('Why idempotency is checked first — if it is a duplicate, skip all processing and return the cached response. No DB writes, no fraud check, no debit.'),
  bullet('What happens when fraud returns FLAGGED after the debit has already happened — debit must be reversed (credit the amount back). Order of operations determines complexity of rollback.'),
  sp(),

  pb(),

  // ══════════════════════════════════════
  // WEEK 7
  // ══════════════════════════════════════
  weekHeading('WEEK 7 — Testcontainers + Observability + Project Polish'),

  dayHeading('DAY 42 — Testcontainers: Integration Tests Against Real MySQL and Redis'),
  label('Why Testcontainers — what you must understand:'),
  bullet('What Testcontainers is — starts real Docker containers (MySQL, Redis) automatically during your test run and tears them down after'),
  bullet('Why unit tests with mocks are not sufficient — mocks do not catch real SQL syntax errors, missing indexes, constraint violations, or actual Redis behaviour'),
  bullet('What integration tests catch that unit tests miss — real query performance problems, actual foreign key violations, real transaction isolation issues'),
  bullet('Why H2 in-memory DB is not sufficient — H2 SQL dialect differs from MySQL. Queries that pass in H2 fail in production MySQL.'),
  sp(),
  label('How Testcontainers works — what you must understand:'),
  bullet('@Testcontainers annotation — activates the Testcontainers lifecycle: start containers before tests, stop after'),
  bullet('@Container annotation — declares a specific container (MySQLContainer, GenericContainer for Redis)'),
  bullet('MySQLContainer — starts real MySQL 8.0 with a randomly assigned host port'),
  bullet('@DynamicPropertySource — injects the container\'s dynamic connection URL, port, and credentials into Spring\'s application context at runtime'),
  bullet('Why @DynamicPropertySource is required — the container port is randomly assigned. You cannot hardcode it in application.properties.'),
  sp(),

  dayHeading('DAY 43 — Structured Logging: SLF4J + Logback'),
  label('Why logging discipline matters:'),
  bullet('In production, there is no debugger. You debug entirely with logs.'),
  bullet('An engineer who cannot instrument their code cannot debug production issues independently. This is a real hiring filter.'),
  sp(),
  label('SLF4J and Logback — what you must understand:'),
  bullet('What SLF4J is — a logging facade (interface layer). Your code depends on the interface, not the implementation.'),
  bullet('What Logback is — the default implementation behind SLF4J in Spring Boot. Replaceable with Log4j2 without changing application code.'),
  bullet('How to declare a logger correctly — private static final Logger log = LoggerFactory.getLogger(ClassName.class)'),
  bullet('Why static — one logger instance per class, shared across all object instances'),
  bullet('Why final — the logger never changes after initialization'),
  sp(),
  label('Log levels — exactly when to use each:'),
  bullet('TRACE — extremely detailed, step-by-step. Almost never used in production. Disabled by default.'),
  bullet('DEBUG — diagnostic info for development. Disabled in production. Use to trace code paths.'),
  bullet('INFO — significant business events. Payment processed. User registered. Service started. Normal production output.'),
  bullet('WARN — unexpected but recoverable. Retry attempt 2 of 3. Cache miss rate above threshold. Approaching rate limit.'),
  bullet('ERROR — something failed requiring attention. Payment failed. External service unreachable. Exception caught in critical path.'),
  sp(),
  label('What to NEVER log — this is a compliance requirement in fintech:'),
  bullet('Full card numbers — ever. Under any circumstances.'),
  bullet('CVV or expiry date — ever'),
  bullet('Passwords — never, not even hashed'),
  bullet('OTPs — one-time passwords must not appear in any log'),
  bullet('Full JWT tokens — can be replayed to impersonate users'),
  bullet('PAN (Permanent Account Number), Aadhaar — logging PII violates data protection regulations'),
  note('Logging payment card data in India violates PCI DSS standards. This is a legal requirement, not a guideline.'),
  sp(),

  dayHeading('DAY 44 — Actuator + Health Checks + Application Metrics'),
  label('Spring Boot Actuator — what you must understand:'),
  bullet('What Actuator is — a built-in set of HTTP endpoints that expose the operational state of your running application'),
  bullet('/actuator/health — returns UP or DOWN. Load balancers and Kubernetes use this to decide whether to route traffic to this instance.'),
  bullet('/actuator/info — application version, build timestamp, git commit SHA. Used to verify what is deployed.'),
  bullet('/actuator/metrics — JVM memory usage, HTTP request counts, response time histograms, thread pool stats, custom metrics'),
  sp(),
  label('Health checks — liveness vs readiness:'),
  bullet('What a liveness probe is — is the process alive? If the liveness probe fails, Kubernetes kills and restarts the pod.'),
  bullet('What a readiness probe is — is the application ready to serve traffic? If readiness fails, Kubernetes stops routing requests to this pod but does not restart it.'),
  bullet('Why the two are different — a process can be running (alive) but not yet ready (DB connection not established, cache warming in progress).'),
  bullet('Custom health indicator — how to write a component that checks Redis reachability and contributes to the overall health status'),
  sp(),

  dayHeading('DAY 45 — README: Architecture + Design Decisions'),
  label('What a professional README must communicate:'),
  bullet('A hiring manager or senior engineer should understand what this system does and be able to run it locally in under 5 minutes'),
  bullet('What to include — project description, architecture diagram, every design decision with reasoning, one-command local setup, test coverage summary'),
  sp(),
  label('Design decisions to explain with reasons — not just what, but WHY:'),
  bullet('Strategy pattern — adding new payment types (NetBanking, Wallet) without modifying existing PaymentService code. OCP.'),
  bullet('Optimistic locking — higher throughput than pessimistic locks for concurrent balance updates. Occasional retry acceptable.'),
  bullet('Redis Lua for rate limiting — INCR and EXPIRE must be atomic. Two separate calls create a race condition that breaks rate limiting.'),
  bullet('Cursor-based pagination — OFFSET scans all preceding rows on every page. O(n) per page, O(n²) total as data grows.'),
  bullet('Testcontainers — integration tests run against real MySQL and Redis. Finds bugs that unit tests with mocks cannot catch.'),
  note('A README that explains WHY decisions were made signals senior engineering thinking. Most junior project READMEs only say WHAT was built.'),
  sp(),

  dayHeading('DAY 46 — Final Test Run + GitHub Polish'),
  label('What to verify before the final checkpoint:'),
  bullet('mvn clean test — all 20+ tests are green. Zero ignored. Zero warnings.'),
  bullet('Commit history — every commit follows type: description. No wip, fix, fix2, asdf anywhere in the history.'),
  bullet('Secrets check — no .env files, no plaintext passwords in yml files, no API keys committed to GitHub'),
  bullet('README renders correctly — check the GitHub preview. All sections display as intended.'),
  bullet('.gitignore — target/, .idea/, .env files are all excluded'),
  sp(),

  dayHeading('DAY 47 — Phase 1 Final Checkpoint'),
  label('You must pass every item below before moving to Phase 2:'),
  sp(),
  label('Java Internals:'),
  bullet('Walk through HashMap.put() including treeification — explain in 2 minutes without notes'),
  bullet('LRU cache — implement from memory on paper using LinkedHashMap — 15 minutes maximum'),
  sp(),
  label('Concurrency:'),
  bullet('Race condition — show one in code, fix it three different ways'),
  bullet('CompletableFuture thenCompose vs thenCombine — explain when to use each with your wallet example'),
  bullet('Deadlock — what causes it, how you prevent it in a money transfer between two accounts'),
  sp(),
  label('Spring Boot:'),
  bullet('@SpringBootApplication — what it expands to — 30 seconds'),
  bullet('Bean lifecycle — all 10 steps in correct order'),
  bullet('@Transactional — 3 failure modes, cause, effect, and fix for each'),
  sp(),
  label('SQL:'),
  bullet('B-Tree index — how MySQL physically finds a row'),
  bullet('EXPLAIN type=ALL — what it means and how to fix it'),
  bullet('Cursor pagination vs OFFSET — why OFFSET is dangerous at scale'),
  sp(),
  label('Project:'),
  bullet('docker-compose up starts the entire stack cleanly'),
  bullet('mvn clean test produces 20+ passing tests'),
  bullet('README explains every design decision with reasoning'),
  bullet('POST /api/v1/payments works end to end with a valid JWT'),
  sp(),
  label('System Design:'),
  bullet('Rate limiter — deliver a complete design in 45 minutes using the 7-step framework'),
  sp(),
  warn('If you cannot pass every item on this list — do NOT move to Phase 2. Phase 2 builds on every single item here. Gaps here become walls there.'),

];

// ─── Build and write document ─────────────────────────────────
const doc = new Document({
  numbering: {
    config: [
      {
        reference: 'bullets',
        levels: [{
          level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 440, hanging: 220 } } }
        }]
      },
      {
        reference: 'subbullets',
        levels: [{
          level: 0, format: LevelFormat.BULLET, text: '-', alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 220 } } }
        }]
      }
    ]
  },
  styles: {
    default: { document: { run: { font: 'Arial', size: 20 } } }
  },
  sections: [{
    properties: {
      page: {
        size: { width: 12240, height: 15840 },
        margin: { top: 1080, right: 1080, bottom: 1080, left: 1080 }
      }
    },
    children: C
  }]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync('/mnt/user-data/outputs/phase1_study_guide.docx', buf);
  console.log('Done');
});
